### ISSUE TITLE
PurePerms 1.2.0 causes PM 1.6 crash when player limit hit 

### ISSUE THREAD

**Issue by BlindTail** [PurePlugins/PurePerms#110]
When player attempts to join server, but receives "server full", PurePerms crashes server:

```
Error: Call to a member function toString() on null
File: /plugins/PurePerms_v1.2.0.phar/src/_64FF00/PurePerms/PurePerms
Line: 437
```

Steps to reproduce:

1) Install clean PocketMine-MP 1.6 (any build from bleeding)
2) Drop new PurePerms 1.2.0 into Plugins
3) set max-players=2 in server.properties
4) start server
5) When one player joins all is fine. Second player no problem.
6) When third player joins server crashes because of "Call to a member function toString() on null"

Here is the full crashlog:
https://gist.github.com/BlindTail/18451447c30d44698cda

**Comment by BlindTail** [comment]
You can also test with just two devices by setting max-players=1 in server.properties

**Comment by Pub4Game** [comment]
or 0

**Comment by Pub4Game** [comment]
@BlindTail Test the plugin with my fixes

**Comment by BlindTail** [comment]
@Pub4Game With your fix it does not crash; however it throws the following error when a player joins:

```
[22:28:48] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PurePerms v1.2.0': Illegal offset type on _64FF00\PurePerms\PPListener
[22:28:48] [Server thread/WARNING]: RuntimeException: "Illegal offset type" (E_WARNING) in "/plugins/PurePerms_v1.2.0/src/_64FF00/PurePerms/PurePerms" at line 483
```

**Comment by 64FF00** [comment]
@BlindTail @Pub4Game Thanks a lot for your help!

**Comment by BlindTail** [comment]
Cool! It works :-)  Nice job on this plugin.

**Comment by Pub4Game** [comment]
:+1:

**Comment by 64FF00** [comment]
Thank you @BlindTail and @Pub4Game <3
