### ISSUE TITLE
Server full join error.

### ISSUE THREAD

**Issue by andris155** [PurePlugins/PurePerms#112]
2015-10-10 [11:00:33] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'PurePerms v1.1.12': Undefined variable: uniqueId on _64FF00\PurePerms\PPListener
2015-10-10 [11:00:33] [Server thread/NOTICE]: UndefinedVariableException: "Undefined variable: uniqueId" (E_NOTICE) in "/PurePerms_v1.1.12.phar/src/_64FF00/PurePerms/PurePerms" at line 662
2015-10-10 [11:00:33] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': spl_object_hash() expects parameter 1 to be object, null given on SimpleAuth\EventListener
2015-10-10 [11:00:33] [Server thread/WARNING]: InvalidArgumentException: "spl_object_hash() expects parameter 1 to be object, null given" (E_WARNING) in "/phar_SimpleAuth-master_9DdYZ2TESTD94eC.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
2015-10-10 [11:00:33] [Server thread/INFO]: szasz6[/86.101.44.190:19132] logged out due to Server is full!

**Comment by Pub4Game** [comment]
Use new version plugin https://github.com/PurePlugins/PurePerms/releases/tag/v1.2.0

**Comment by andris155** [comment]
New version crash:
PocketMine-MP Crash Dump Fri Oct 9 20:00:32 CEST 2015

Error: Call to a member function toString() on null
File: /PurePerms_v1.2.0.phar/src/_64FF00/PurePerms/PurePerms
Line: 437
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.2.0

Code:
[428] 
[429]     /**
[430]      * @param Player $player
[431]      * @return null|string
[432]      */
[433]     public function getValidUUID(Player $player)
[434]     {
[435]         if($this->isUUIDSupported)
[436]         {
[437]             $uniqueId = $player->getUniqueId()->toString();
[438]         }
[439]         else
[440]         {
[441]             $uniqueId = $player->getUniqueId();
[442]         }
[443] 
[444]         return $uniqueId;
[445]     }
[446] 
[447]     /**

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #43 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux node20.infinityhosting.hu 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
iProtector 3.1a by LDX for API(s) 1.9.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.2.0 by 64FF00 for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.3.1 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwlv20iW/isFOcDYDVG3JVsNN9brOD1Z2G1N7GwWaDWCElmUGPMKi7Ss9Oa/z/deFQ/JzthJ
G9gdoQOzrnefRfafrTyIVGvaH+HXH46Hg3ZLZVmStaZ/tvJNiqXW+cfzd++u3rXarUhpLZc0dybD
UOSJkCJS0UJlwi9iNw+SGJPXeRbEy/0DgVFchCEO+kFIp7qzIlMzlUX6412/M+j0OulKZl2dud2P
49GbN71evaN+wvkwiHF+NJx8bbfSsFgGMaA1N7iJp4jk0eAIK5gYDY7xIPDr/vQTjYc9OxY/if9I
ZSYjMQvlBqS/Svkvb+o3NmUqLzLDwv9q5om3DKotXR4P7TgtFmHg1oJYqvy/ZRh479+/fb2/jeqA
D47swT95dFiCxS/w91/lq0A7vwSajl8XaZpkufLMwXFjqzk8aczQ71URB58L9dYTJyVO5xcQ9N5O
7x84v9SK+plhHDVgfOWZ48aMCrWiyVFvF/mo/93IGeFosItwNLS6G40aS1YNFVRzuBSXOTguD04a
Soet5Jl0YRe/t/Z6Yv9gKtLEvVV5BGuaz69VdkeUuZnUq9dFlO4vkiRUMj5o/dFuLVWsMhmSTWGX
hkIBud8Ze+oOiBZFEHpkkDDHLMkTN8HO4ajdkmnA+/rDTg/7lkGOYe+ZPxzI5G0YLOhMZ8IQiliS
f7Yugri4FzHMfNDrBLEfxEG+WSU6hwY7q0IMO/1eZzB07vFzdO45QXo3dsYjsdcX15czcVMocSkz
0T8S/dF0dDQdjMTZ+Y0Y9PojcX80hv8BW7pKgeuwM+4MMPqiYjDZGmDYM4sfE13SggkehDyo/FKT
xIIZhKLc3IQRy0Fjst2QKQiXmJBFvkoyTbq6eP0/pAEW5e+Q5TGwY6xiuQgVCMqzQrVbnkpBHh3A
mk78/HVzIpIcIgBqPq8Rz+eXNI94kkjibHZ1ffPh6t3Fa0yt1UIHORG6yvNUT7tdKG9VLDpuEnUB
x7k8m513G0yA5bOV0vkF2VST0eZse8t6BtuMnt8l4TUo3+L26Me5bSDe5fT65vTdzfvZo3yu1+uO
AikEtpPfEmOXZ79Oxh8/JFnonXtkwxVzuytNBnudw10WydXgYH4OfwoKPRm/FK+Ru5yM53NjdPP5
mghSIGg+r2ibYe3tU9qm6A6Gr0OZpltaLGd2NNg53GbwU/IpURP6bXHWH/w4a9pgns+jp43Vkv+f
Mn6bq6hBfjnTJH/Q6f9rT+v9RU+zSJ/lZpbyS7kM3BsVqhkSnIm3paXtrGwrYrhraUi1RbjZVsJf
4MeAgw7y9HvYOddaxXkgQz07b/CyNb3NCFjZUYpaEjVXPgUccaNk9GKW1SRjPr8AO2zg3x0NmUJD
YHeLNYqJSKHZhVwumxGxmtvlvfcY7wbyS1lmhfylOK65ocARRGmoTsFCM3bUk9sMT3Y9cMYFySWi
pNE02Fgly1Xgpi+m9JoY1DxNwp6RGhoiqCntNqBUErg0rYF+IIVqoSEJxNEtKbwu8uT2pfS9jbbk
uUHGc+JpCG7PfR+ZvsnR1vS2Znu7ieHX6MPli+mQgCG8NtBvj54ZnNwkTqLN6extMzTVk9u5otc5
3uYoidUC/x7oqV15Mvd09m+f/w7teGjHIzseYfyDsrBkzOfKUA5a5vMtLp4hirp3rCXR7Ce3c/5O
lDKt6osp17a+83lFQOPx+/2UTppSvNFC19r/r2TxUPs0uav90b+F9j8li0r7hovnVHtVAPu7CnfK
vt2lJ8TyWNnxlC0088MzSpAVE/LDvYsM1ScZe1kCcN26AXZsv9bNM6W6kdS5yroPuK/t5kJSM7hr
ODz7A3HjaRk1PPo7zCEEPZU9WOKeHxnR3IHpfPOQz2pll9fxC/Jq6f0xzlNLYcV9g+TnS+BaheFD
7nl2l/PJ/52WNeip+LTEfQePqyR9hEea/f/EI+ipeTTEPTOxna1kvpPXeGq3g+o/ndb6TzFXp5gH
vLXeSL4J1bDE1jfSHdFVP/3lZMdAvtJlFF3wKoS0Mp3wZV/HOklAdWprb1aNxFkS+8FS0D31PJvH
e2+yQFy5uTgWg96015v2J+Ls/Jqvyw5pQ5Tk3sm86PXk5Mj8CR3H+d08ujcrdRV6wox8xz7IM7oI
AUl2PEQTtgXhD4Ag4IZYh658T/rH/eGAJtcrSMEJA52f9Ggs4zgpYpfiON+wSncVqDsVoRnTJ0nM
cFK5jp3U3FhBESd9Jl3e2zP6ZGhAhWGydvwwWK7yk8T367MyDiJ0dlvwomRRTiwh4yjxlKHITzKQ
U81ZQCuZeW6SVeP0LrWnvcD3A7cI880Jc2iuXPMkc7TK6V5Tn9B0CK5Ch2z5hG956jmtlNfYQq8r
Tl6fvzl9f3FDs8Zonc+FyjYWpZ3K4FUlPfTcSaXWAO6d/MQ/iAQdiaPlnSpZNyoJ0pP+0VGnPz7s
jMedQ5bnXaDWjge9SGjjZExTdFlaJdrOJgrJ2gTlb+GyoRXgk94RkL0JyE3U3ZVzOWMLFDAirUQp
CiEzJfKVEogRGg8yFy6ZQC4WSgSxGxae8vAgHli6gXadRDjrE4hdqFr6qi0SrMA0AVQsMiVvxSYp
MgtNBL6ATgM/YBxQZwaLQm3CoH9T6wpg11O+hEq1WCfx33JBN1kyEyTOCCy7MLUNvReitxuG+/VK
xaJIl5n06CqbQBqBG4BTGoi9mxWqFCfEJKhBkl8WaOYEvfVh8Vn16ABjtEWonL6wgM3hs5VyLT/b
R0FIGVRU3FkHt0GqvEB2kmzZpVH3Amr9mPgf315ffRwPj53BRzrHIq1ATcUc8XE5bxlkH1aKJEkv
xzQCoaAXZebtEdSWyViHMocUeZlly/SCFjypnFXsqbvAVWKFciBkpUcM2vhXjdaHZ3K0EnpV5F5C
vmm6XCLpVOgvjCAHXAowqo+kSX+9PMlzM3PbEfvXZhsHJV9+ymClnt1nNumDkrdTChSCYhDYEbaA
FHeBFP8gJ+NN7G5lcdkkcg9JbC0keYBOwJel1RiAtNBEoWHeyC8wMJYTsiZ2Ikd5Rur1kgOiF4kG
s5SUDIpz9u8SFuQnKPQIOANsjWhebIS1UD5g40G1vkXvhwCqS2IYrPQ8kSlt7JrIhSXfgiypkXMo
4gpY80KRcKBG9bmQ/HJ0Gdxh750MCyX2LVpkkAMGb3AiFimK8w4sZLlU2RTrBvtvBb9Xhcue6k3s
3kh9C5/KbuGkHbPjvYZ8yPpLdmnfKkPBUMDUsF+3BUdMYSMrHKINgUSQoKYygAWE/EpzURHDO2mL
hX7Nxgi+4MJZco88kCuIAmyxI8UVeSThkqS3PkUCfjEMj2+LIP8bvSfO+JynKA+xhe+cFvvgApoX
AyMb5sSx3E4ZVhkXKLlkGxsVfg2TBURNZYcwCzDOKMgpDkZqKRebHKSJa0NSj4kINKm8jCrgbx0w
iSx+QYnQQCo1ollKfgAzQmhEookZmI94VOI0JgG2CjboZQKOEnIpkh9jWjKhDhM3Fb2SGbHHOSFH
cJPevwEbVME9wQSl+7/IhM6TlOmwAbKiy8LTAm5HGVt5NVWE9xHSUJoGCedFcllNWF3OBpbEyi37
wIbI5BkD5D0OXEaVDmkzSRIj9MGdIUgKJ9+Ss5EvSraQkwwFBrPNQDdQ4Ka125cxzOC5oqhDSZcP
dR4eICnYohwyTZVLuVmzlIhqI3RztmIFglWprlke9izP+uAbZFkJDGsJLGW2gHE4bhKGpqg0rvio
pNnaiCR7SthTcPZIxgXXAk1qUC0VMJKDdhlEHliJNRMTlPnqk+FHtQF2xJVJvzyCqaySIvQqUgIE
nXUsavKNYYuUqQer416v5lbsvWGHeRBY2Y4MjIo5P0uiMkKb03aH0wxnO5oGQ1ahD83kEevaOU2l
vLsq4ltdauGCXYTiKk8TndRREX/CFP1t9ukMlZI2mxwqU6j0qqEZYKURWK86Hjeofp2Yw7uqpaxC
5Z05ug3HYLMbX1QOnOUcFy2QKiVhraZESkuNQuFJkPQvVjnprFGBwphCk3IXMke/RUWQpMIdmRYW
aEMcO6+ps+2qiWsLVSVfG7n2mtGwXKPgkW1ygt4WTr/hAibJMmonL8lBgDocl9GpTu3cElFO9Uz8
tEo2pzFpKeuIv6Prg9hPUODD1M9m79s4CyoWiGPrwMtXJh3YCFEhcBjBVEyqWqSuUzSLqLG5I049
+OJKhn4X/YspnzwFe7TIgNbYaRI3nblRDDSgbRVp5/fkulSDybBtAgMh/4AiNlmDPZiVYjeg8uL9
LJ6VxUndjlD9RYfWSCEMtEjj1LET20Uht61qUSynVb3zi+hTnWNTF5W4vKEsbzVHxJUqy17TOhjZ
9ZtFqxZdtJB5AVPqLt1S3IiTnt4hoGx+dxokVVa2xAu4M00ib7YGSCJgY3Ah3NzaoD3kmENTEWFx
WbVOYJCvfIh86iW0CXNyCwciMjWieYMECDl/SBH7tlXr3m9XN+dTwfEc/7kFesoYPSWD4mtoUqol
0mKviGwYwOmWLl00TYhGlmu2M059oIfsKifbGvRsiqKgaDKgMTTq+WnFpr0qWmwvlPGwLNSvycGJ
2YXUqoFyvw+negRXWwyw0H9sQeVu58A6uVZNWqyp3BB06ijtBY5QCGwGJ5UcRrvcydctPgUP7tuo
jDMhRIZrudEGvoW0Y2NbmcGa2GmUFHEzuWhbRJbEECsE0/Q3iPg0mIrRvzouM8x6hg8DZzezif7x
4BsQ2PpiZdrphTIQF8qnSMaXVRTxSDUNyOYSqxE+y+h5Le+Q6qnoDOj+QFHvmG7snYnNdlVZxUHG
55cmZWitAqFfhLwx0TBnh5w6cE2K4u4xoysKmAwAl4L7lFD7ZjxIy4isKLIRlxJXJYlHVEQirlV0
Ke+F3JUS2jeXc05tLbsasqb8TnpBoRtHrXakpZTdujxurZNOoG4ycY1uEJ0i9WCzW72/S59MGHuj
24PtXGsYqXvUmpfOQ2ZsNF3LgO8gPheqUFb7FoINGbziaChyKo5+EGKapEVYQbQjSn4PgNM/9mcH
UjUMmLtTh+1Nk4yNkCPkgZzuqux8vwoxdN04FWUBWqqevkgtUpRfdV1qTJjDUFnuWKiANzGnLXpC
cGgm1pLQVtN2VkaLAF5TbuPrYAp35lpiWoY4ukmh72SFmTcZ3hpWafu2H2kETvIMh27Mdueq5LUz
n67SIPaTpunQN65Tg7zTuFRFcVbRGyfxJqK2hX1NQw+6QTh1ZHaDqDcwA7BTKeRyiYxnb0eqWyiq
aenr4dsH3O2SRjD1t0gjURp/sFbxCBjYk9kyLRWVxY4tF5o1K88naVNoe2d0Xcs3hipMUsqYbYzB
FV2K5nXRiNrJR9WvoA5kyJiqD9pWJfmCtAg/bwAS9mVRo7opUCjr3CTZMrRaeEaHZkOJo0mpkRV9
avoNSYUBUl6pt/N7SRVAOaSyCrgsQdOSMiM9+MbvduIPnomLW7Uzxy9QOALX5VLzGpzZK/si07KW
LyO4F33sXp0bfc6smqsaEkiEYicA4bYA2WLGYmYy7LOgNxgUGmyKrLFOxZuL05vp4OdJ+/D4vt8e
3g/bg5/7P3uoFEyU3Kf39i7FspOjnljCP7QZjQ4P6qaIMlyr3VL3uYpJGvy9yxnyY+MzbzK9xhAJ
atmasnm2W6lLW+1Afw6DXA3N1+mO+RL+i/lc3Xz5sXBRia2q/XSvHXsyqyfM/1FSjoosrAZ+EOb0
IQZA983nJH6eVqvLqH5eIRKYT66w6ZOuPtKht5nRwv6PGuVmVLObNK85yCUR5DXYvZ5dMFZ6Tl1U
oPXZDRjmL+DtkzjsEHXEuXDoVeCgd9gb4vHVW3Lo4WSo5KHnHR4Ojybj/qg3lke9wUCOFkdyOBmN
+keLwainxCtgmq1ILPyOmREnOrivhW4vL+yGPjH6Tvm2v8Ys4ztSh74rUWGPgLbnTybu5OhofHgI
1MPjwVANe4vjybHnMT69ipJahJpdUG9zGhjhY3Oe3KoYuS2rZj4oeYsIYgTFX7ptJL/Vom9/aMOX
IDWjQWfU+vr1n3iSsDg=
===END CRASH DUMP===

**Comment by Pub4Game** [comment]
In that case, use the source files from github and build the plugin with help of DevTools

**Comment by 64FF00** [comment]
Already fixed in the latest version. Please do not create duplicated issues
