### ISSUE TITLE
toString on null

### ISSUE THREAD

**Issue by vvzar** [PurePlugins/PurePerms#113]
PocketMine-MP Crash Dump Sat Oct 10 14:45:40 MSK 2015
 
Error: Call to a member function toString() on null
File: /mcpe/shared/Plugins/PurePerms_v1.2.0.phar/src/_64FF00/Pur$
Line: 437
Type: E_ERROR
 
THIS CRASH WAS CAUSED BY A PLUGIN

**Comment by vvzar** [comment]
Oops..
File: /mcpe/shared/Plugins/PurePerms_v1.2.0.phar/src/_64FF00/PurePerms/PurePerms

**Comment by Pub4Game** [comment]
Боже мой! Используй исходники с гитхаба, там это исправлено

**Comment by 64FF00** [comment]
Already fixed in the latest version. Please do not create duplicated issues
