### ISSUE TITLE
Please help! im a n00b

### ISSUE THREAD

**Issue by RafeeSamith** [PurePlugins/PurePerms#114]
Hi There 64FF00! I am not very good at stuffcbut when i add a group it says that its added but when i do /setgroup and the group i added it says the group doesnt exist... So idk wht to do please help!

Thanks,
Rafee

**Comment by JoahDave** [comment]
If the command /addgroup doesn't work, then just add the group in the groups section of the PurePerms folder. I had a problem with the command not working, and this worked for me.

**Comment by 64FF00** [comment]
@RafeeSamith Do you still have your groups.yml

**Comment by RafeeSamith** [comment]
I tried but then PurePerms doesnt work :( when i type /plugins then
PurePerms comes in Red coloyr while all the other ones are green. I believe
rad means disabled so whenever i edit groups.yml it disabled

**Comment by 64FF00** [comment]
@RafeeSamith Are you sure you are using the latest version of PP? (v1.2.2)

**Comment by RafeeSamith** [comment]
PurePerms Version: 1.2.2
PureChat Version: 1.3.3

**Comment by 64FF00** [comment]
@RafeeSamith So could you please post your groups.yml here

**Comment by RafeeSamith** [comment]
Thanks for the update! It works

**Comment by 64FF00** [comment]
@RafeeSamith :heart:
