### ISSUE TITLE
defect

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#115]
1)Make the player group /setgroup Pub4Game Admin
// Creates file player
2)Change the group for standard /setgroup Pub4Game Guest
The player file is not deleted ((

**Comment by 64FF00** [comment]
@Pub4Game You actually don't need to worry about it, at least it won't cause that much lag. Plus it won't be easy to find player groups from the config files and remove them one by one if there's like 1000+ config in the players folder... It would be better not to add this feature.
