### ISSUE TITLE
Players yml file modified when joining game

### ISSUE THREAD

**Issue by MCDad** [PurePlugins/PurePerms#116]
Using PurePerms_v1.1.12-PMv1.6dev.phar and PM 1.6dev-48

1) modify existing player yml file in ~/pocketmine/plugins/PurePerms/players e.g.:

<code>
--
userName: Richard
group: OP
permissions: []
worlds: []
...
</code>

2) Start pocketmine and enter "world"

3) Player Richard has no access to commands

4) examine player's yml file using text editor.  It now reads:

<code>
---
userName: Richard
group: OP
permissions: []
worlds:
  world:
    group: Guest
    permissions: []
...
</code>

World is the only world I have.  This happens 100% of the time.

Running on Raspberry Pi using Debian.

Cheers

McDad

**Comment by 64FF00** [comment]
Are you sure you've enabled enable-multiworld-perms option in config.yml?

```YAML
# Setting this option will allow you to use per-world permissions
# - true / false
enable-multiworld-perms: false
```

**Comment by MCDad** [comment]
I set the per-world permission in configure.yml to true on installing PurePerms.  However I haven't checked if it has been reset to false in connection with my observation.  I'll check it when I get home.

**Comment by MCDad** [comment]
Yes, per-world permission is set to true and doesn't change when I enter World.  My player.yml does change.

**Comment by 64FF00** [comment]
@MCDad Thanks a lot. This issue has been fixed in the latest commit.
