### ISSUE TITLE
no perm to pvp???

### ISSUE THREAD

**Issue by astersx** [PurePlugins/PurePerms#117]
Hi,  just installed pureperms and Guest are not allowed to pvp....  :0...  I had for long time that problem but i gived up on pureperms....  but now i wanna add helpers...  i dont wanna op them :(.

**Comment by astersx** [comment]
Ohh...  it seems...  Guests cant kill Guests...  and Admins cant kill Admins....  Is like a team,  awesome but this plugin wasnt supposed to add teams,  just perms. 
P.s. Can u make team plugin?  :3

**Comment by SavionLegendZzz** [comment]
i noticed this bug too but if you want a teams plugin check out: https://sellfy.com/SavionLegendZzz

**Comment by astersx** [comment]
Savion,  if you wanna sell plugins,  need a description of bugs and how it works... What if is not what i wanna or got lots of crashes ? just waste $1.. . its not about a stupid $1 is about the time i need to search my credit card =)). And... is legal? Maybe i make some php scripts and put for sale too ;)

**Comment by SavionLegendZzz** [comment]
thanks for the tips. and i noticed perms are still broken so you have to restart the server

**Comment by astersx** [comment]
I never put my hopes in pureperms,  just, i wanted to do something :D........  i tought they solved the crashes and errors :0....
My sv is buildmcpe.roxweb.fr  port is normal. If u wanna see me :)))) Jk. 

And developer did you read this issue??? :0

**Comment by 64FF00** [comment]
@astersx What plugins are you using now?

**Comment by astersx** [comment]
Does not matter what plugins i use,  becouse i tested with no plugins :/....  Now i use economyS,  slapper,  1vs1,  keepinventory,  novoid,.......  Slapper and 1vs 1 added recently,  advanced kits,  essentialstp,  world protect, broadcaster added recenlty,  vote,  chat defender, ifriend, alias,  magictp, killrate, i protector,  pocketguard, block effects, ..... custom ranks.... but i had this problem for loooooooooong time. .... oh ya and always spawn

**Comment by astersx** [comment]
Ifriend dont work with pureperms :/

**Comment by astersx** [comment]
Omg,  just say,  Ifriend will work with pureperms?  Yes or No!  :/

**Comment by 64FF00** [comment]
@astersx Alright, I'll take a look at this issue very soon.

**Comment by 64FF00** [comment]
@astersx I guess you just have a problem with one of your plugins. Have you tried removing all of your plugins except PurePerms and PureChat?
