### ISSUE TITLE
An API question.

### ISSUE THREAD

**Issue by RandomAltThingy** [PurePlugins/PurePerms#126]
How can I check if a player is in a group? I need to basically do
```php
public function onJoin(Blah blah $e){
   if($this->pperms->getUser($e->getPlayer())->isInGroup("Guest")){
      $e->setJoinMessage(NULL);
   } else {
      $e->setJoinMessage(blahblah->getUser($e->getPlayer()->getGroup()). $e->getPlayer()->getName(). " joined");
   }
}
```

**Comment by RandomAltThingy** [comment]
So the output for somebody who is not a guest is
<code>RANK playername joined</code>

**Comment by 64FF00** [comment]
@RandomAltThingy PurePerms::getUserDataMgr()->getGroup(IPlayer $player, $levelName)->getName()

**Comment by RandomAltThingy** [comment]
You not gonna answer?

**Comment by 64FF00** [comment]
@RandomAltThingy ```if(PurePerms::getUserDataMgr()->getGroup(IPlayer $player, $levelName)->getName() === '...') ...```

**Comment by RandomAltThingy** [comment]
Where is the variable <code>$levelName?</code>

So I could do
```php
if(PurePerms::getUserDataMgr()->getGroup($e->getPlayer(l, $levelName)->getName() === 'Guest'){ //etc
```

**Comment by RandomAltThingy** [comment]
Ignore syntax error of the (l

**Comment by 64FF00** [comment]
@RandomAltThingy That's the current world name of a player

**Comment by RandomAltThingy** [comment]
But do I need to define that variable @64ff00

**Comment by 64FF00** [comment]
@RandomAltThingy Yeah

**Comment by RandomAltThingy** [comment]
**Last question:** *MySQL support.*.

---

If you have 2 servers, pureperms on both, linked to the same SQL network, how can we make it so we get a rank on one server and on the other.

**Comment by RandomAltThingy** [comment]
I need this for buycraft

**Comment by PEMapModder** [comment]
@RandomAltThingy connect to the same MySQL server and get everything done?

**Comment by RandomAltThingy** [comment]
Yeah, so like the big server networks you set a Rank on one server it appea

**Comment by RandomAltThingy** [comment]
Appears on all

**Comment by PEMapModder** [comment]
and it doesn't work?
