### ISSUE TITLE
Error, followed by a crash every 2 minutes.

### ISSUE THREAD

**Issue by egr7v8** [PurePlugins/PurePerms#128]
PocketMine-MP Crash Dump Mon Oct 26 13:54:44 EDT 2015

Error: Call to a member function getGroupPermissions() on null
File: /plugins/PurePerms-master/src/_64FF00/PurePerms/PurePerms
Line: 397
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.2.3

Code:
[388]      * @param IPlayer $player
[389]      * @param $levelName
[390]      * @return array
[391]      */
[392]     public function getPermissions(IPlayer $player, $levelName)
[393]     {
[394]         // TODO: ...
[395]         $group = $this->userDataMgr->getGroup($player, $levelName);
[396] 
[397]         $groupPerms = $group->getGroupPermissions($levelName);
[398]         $userPerms = $this->userDataMgr->getUserPermissions($player, $levelName);
[399] 
[400]         return array_merge($groupPerms, $userPerms);
[401]     }
[402] 
[403]     /**
[404]      * @param $userName
[405]      * @return Player
[406]      */
[407]     public function getPlayer($userName)

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #396 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux smokelines 2.6.32-042stab111.11 #1 SMP Tue Sep 1 18:19:12 MSK 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
SmokePanel 0.2 by  for API(s) 1.0.0
EasyMessages 1.1.0 by Gamecrafter for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
MoreItemsInCreative 1.0 by TopPlugins for API(s) 1.0.0
AdvancedKits 3.1 by luca28pet for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
RegionGuard 0.0.1 by Skaleta for API(s) 1.6.0
SmokeLogin 1.6.0 by  for API(s) 1.8.0
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
PurePerms 1.2.3 by 64FF00 for API(s) 1.12.0
SmokeAPI 1 by egr7v8 for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVGmtv4zbyrxDOApcUlt9xHB9SXJBk271LGl+cxR5QHwJKomw1kqiKVBy36H+/mSElUU66r9sP
d8FuIg7J4bwflH7v6DgVnflwMjmezUaD2aTbEUUhi878947e5TDVuXq4uru7vet0O6lQiq8RdsGT
hGnJOEtF6ouCRWUW6FhmbC30D4Us84Uo0lgpAKnDIwYTWZkkgCOKE0TQz5NyHWeqvygLgWuVl3Kl
RdFXRdB/mE7evh0MmsnmCVAkcQYoxqcnf3Q7Bg0gdBcEMhTIwHg2gxmGP9+xv+W84Cl7t0j4Dgh+
k9NfWD2enb5Y9SYRTyL5iYNsYMHpwFlQCF0WGeNFwXc0Oawn+zQe2XFe+kkctCTjCmWPkK5z5hHh
GVs8v9NoUp0CP/0+u7+9vJ2zXq9Hk8fO5Js1ip+dsTd6Eyvv+1KJ4pJrfrMuvO8r7Ry+dupfCdcU
cNHDyQukJF/ETKMGm8vWC3wzFw0SU2N5nb73dkmN8E8pPTWUTgYD5whXPQ+pKNbi0CG+65BAWCaD
Sn1/0GhU4ayk3//uOxpPXtoIYrImMhkcvzSRRWVhk8G0ZSOTwclHbIR2HdbYjzpg5rrgAZj0z52D
ATs8mrNcBo9Cp+AIq9VSFE8CZBcUXG0uyzQ/9KVMBM+OOv/udtYiEwVP0B1gFYoUjh72pqF4Akr8
Mk5C9KUpuFIhtQwkLB1DFOB5TAuH494AFq5jDcPBZ/7AhoI/JrGPe3onhKHMUFTzznWclc9MpfJR
oCMrNupNe+ORN5iMlOb+cAhnDtnBkC1vFuy+FGwpcjZkw9l8eDofjtjN8h9sNBges+fZFOIEYM43
OeA9BjRDPOg3kQFLHUQ7MLMPUlUHA4AGCQ3qAKJQPufLO/xj6cRR15HZqDfojQDCS72RhUJlxH+X
alPyHy9R0CSwn1FisBIBIuN+IoAUXZSi2wlFDoThPphTMtKXLiDlFMVqjKtVfHOxuFqtgIzV6lry
kCwpgQdYtrw/v7t/vwDAVvgq1kjvRutczft90NSm9HuBTPs1tj4yA8wuUeoLnonEYdQBOvwCsy6v
LoODr+fvToSQLdar1Q2Oa34Wt8v7D7d315cuR5gwgOYrrnY3JvEoh+oWuNuy7SHp3dHTD7AFvCOC
9PLNNCXgfJsP1WrlUnO+ePcJzl7TlUNjf0HefQPe4S1smtSFEH2bIVuso4QCmcl093fpu/JpgPtW
PGlLR2bCh/+dfRV3a1EOe6P675D+ju14bMcTO57A+CsFaslYrYSh/Bfpg1xdLj7DWBYC4mRUJsuc
bzNHGm24I5BRb9ISxvXlv1qCcBn8SsYA5WrVIuCLzN9IAI3qhXKNpbWVO/u/UC7QUiv30/5iRXEp
nu4hs7lRoAbtRYDBfghoXIrdC56+0PFX8lWdv1o5lHxZkG4o69c4Gr0vNzJ/qXiC7mv+5NOa/2TA
cy3rC9SpgJ5an5a4z1DoOy3SC67E4sph0QG2lfrCtnkSl8muzWBt2+Ovd1iDFzIwUBIAJbn4Eoe9
kYVAHtS77KIQXMdPwuHutdk9NttM3svc5oDON8rBDUZg6yU5+7y+YsaW0/PwiWeBCP8Ra9cnW2CH
N3CzFmdJGfDRLBf6m+Vk9+TPUtlr/liT1W8xAvxCyhWZjnmi7hcOvy3wxyuRb1Z8OEeCE7YJ+Awb
vRNrIPGHkhehw4gLdfkAW6NM4Ohu+cgToXlLc9Ov50cZdJAmi/iJa2EoWUBDIgItiz+Do4bfygRK
44+t+DyRUBV8LekyoV0aG2BbsdOPKHb29XJYxmmeiHNAC21d/fw5vngBDV9xzddrh/oG9glt7hc9
/w0H2HHvHi5FoTnUOcuaBvfZ1Vsb+jmsNjc9Tn3n3P64ehr1xm1WzcXSN4s49qIKzK8iwHn88lIA
d+7fi9V9W7sErEEOw+34KtbFydPs2wXXxbvV6kdJ1x2f9CdsrPGSREC/UuGla4peXsgcjCPGZq5z
sKhH7EJmUbxmeD+4KlbZwY3M2G2g2WjKhuP58WQ+GbGry3vq/XFBKnV4ZhwUq7qDIbtIuFJxgJPm
MC+XhT4bng7HIwRuN0Cgl8RKnw1wzLNMlhDgPXPD5PFgE4snkUIwVWcyIzxYrnu5CScg47PhMW1N
+bPdpc5ODLIkkVsvSuL1Rp/JKGp28yxOITa3MKbSrwBrkFIqQ2FoimQBBNUwi2gDITmAVF2N86fc
7g7jKIqDMtG7M+LRXPdA5POU0DrO1uoMwXR15qHpnOktZv4apoQInSV453v29vr8HkHGTLxfS1Hs
7HkWVECpZyH42MtB8ltZhGff0Q+Io9TSU/xJ2FV4EVPfWfV2aYLaZ+jyLCDFl0A13oCh/hlIgTlN
8M0C7IHdb4QSrGKL8UIwvRFM4h2S3nDNAlSoZr5gcRYkZShCeGAv7A5xLcGOmYwQwT5OxSPRZRJm
CoUomQ+F0SPbybKwuFgcMdBOHMV0AiimAOuAihEQ/yS2Nbp+KCIOqlFsK7O/aMbzHEIdQ9GkwGwA
JrPDm3G8BzV8bzciY2W+LngICHqrDC3ZIJuvMnZwvykEWDCAgIqEZ+uSrwXD624SmbV6FcM4kYA/
/o2EilsvNiKwXLQ3AgFVKBJZbxs/xrkIY96TxbqPo/41OMyDjB7eLW8fpuNTb/SA+0CMNaI5W3WK
Uq06eNCHjUDZ4dsBKEtChm8KlC5IvrrgmUogTYdmmqRJlAId8CQ0qTQUT3Eg2IZnYUJKTgGx8Yzm
yAh8SgBcbUodSvQpcyWCxKzKwWQ0xN/jY/w9GdDzyIWwBjTx6ZnTb3qeCPp90mwYh4a9c/RzhkEE
OGL29pA9xZz9E90ElpC7eHZmzjDE4kZoi7aMo7UrCVxZao3KuUXESgXGDOEYDIqkBEEXVkJID1He
zYQHgvOlEg36K3LMCg9IjmHAYGD2YFlIqr9j1h5huXXjerYR58GHGBQmMzBNHoasEMpYMJIJNvsI
5HAFuQmjJAO79QXKA5Qnfi05vRNaQxORsSeelIId2iMhah8BcnMehA+BkdkDq1ivRTGHWTz5p5Je
JYFbnqtdFtxz9QieUzyCI/Zw/r0CiaCdV0ziqk0BTWcJpgWrVRfXJyGzURBMvwtiSEFq9DKBxAKJ
CmFpmYEH4hLCvSTTA37ASQv5DBFbCxABsEMuk9WkoVQNOe8i9HR6CwYe3WWx/gu+FCtoVygwY5A1
7+1lh8AB6JmNUCLEg2e5nBMm9HoM/8WOfP6HRPogWEzLzIDB+tJYY2xLxZr7Ow0EsaUhZUCHxwrV
ayIG8LSNiTASNsM0ZfBU8lcklygGc4FwB2kgI1QRxJrqRKN+YKYko11L4EOi86LM4Jw1EekRYXM2
GZzOVhR1KMBriFo8/B/nAKucj9OPSfi/ol9pmRMJNvDVJFlsioFjYSYVYUUQnvmSKqgLY0nJDT1S
4YEBhXdLXe11QzgKAk6IlkYrPPAKCBrDkUEENReEMfBTEB3GiD+TrJEo1E8J5Qv0eLNsRekbcYAP
Nv5sghKecIuBBPMlLe+9XIxs23IURJiLANOqIrEgrUbGZm/NAEhS5KphczywfKqjVwmyXI8HRNOa
Fz6YgBfIJDFVHfrZq1Ili0JS7B5m94AHpzwrKYG7VEBxU4ItHHWryLBnDNYaTHSNoipCpI2V9dit
yZ40AovYyDIJa0JiiCPbjDWko+mynCgHBqeDgeGRHbwlZ3gRIclWzO6aqaiQaRVoca+d99zY5OgU
mLCq2zeFV+zH2Yc1c7Aps0dl5H1NVo9hkYBIGfYVyA2r3vmihxZQziizyMOKAiujBheiqtRcOcrU
0nkpzbZ99WEqwLrLbHMxmFPssm/AM6UjL4DOQhiurS1UB+FEncM/imqVZUKjLupCEEwjMfnQ5xpa
FyxHONbMkAbBnmxUIgc0Za6dNcHIF3VmpHBz4IavagYdv9hpxN1l3tAxZsyAdKynK1IgjR9PTVRp
Mi51FZjuQhPurALNXgBamnrsR2icQLxnUFmD4V4s3ndhL1DgQ/zZxqHemMBN/l2j9wj9nJ3Y8qAp
HBQJxlnaY+ch+NOGJ1EfWgZTy4QC7MweBEca+5OZ65B1jnZwOdXS1TM6HxZDPOkax8aDP8QZ1KTA
FpiNINPGjP9+kS2qeqHpALAUwk1biPUrLP+z3LNDtzKDXk/45XpuS4/v2RBLDptZsLak6aquVBTH
NqKqN1dWFXM2aKpFxfpKc12CwfTXgREtxLVQNWZXNYmtJkRUlSSSDYyY9ouWWutCbknfAd4qk4HZ
LZ7ZMmcpTK1tcwL80E0EUgsWBzZKMYm38EPgxPZOO8eDLPVLashFSXMHP93eX80ZBV34F5TQqWXQ
qREiul9DzRF59uSavFrD5y1lBdCUQCCxvJIRUUYCStBoNBrOaGAzCEYyk5jQirAjRrjNRtbp2+Aq
hJmCeIneigz6XAnnsMMh+Mkrp3TZCCaGr00IHfSOyGeVcKkYkkYRM/Zp9kqDCYhL5jzM/EaT1BE3
rTLGAWqFsH7CaMCTLd8pg9vicWy3Fb7JjM5TWWZu/Fe2aquIQPIRG/YNEJrxEWL7n2/lBUBDQ7vB
0U467HT66mYyrkyYntQXBpkvIoxDdFuD8Qq1UCM1dzhO4DNxb8mfIOVidRdj6y2wBct39prBZqK6
nKEwEdEL/Soo2iAWlQktkwos1UMHjQOTSKgNK7C3B7sAtJWkfpHYDRnXUDxFU0kpUmJ6qdnf0wXK
s9LFDX9mfF8u0AcFlB0ac2irgmz0jodxqZxtVg3cUkc+arZas8P1UKtgRMLLMq/MQzDFhkAW4I2w
MSTss5tgZAhvmruK9t5L4m302/KY+nToyUth9Wv3k9cT3FOgrDmbfRW2XOZlYrHZZ0xMe4hXGbmk
B9JDos2VoEd2pFCSKMoUIrXG6xsLHdrogLdoc2ZKu0ql+HlXmYNJm3rPGCTFDlNmWFyA5QR32QMR
6TEOtxwPqoEE46kfg+WbJfYCz/TpcxOL8EoBPzFjBmoyrDUSY722jq9jG9q1h5dFbUidTVrQfJPH
WSQbM9hI1D0d2XPuDqEMIvoyme1SLPLJQxTIV9WEYtdip1kzTQSDrXHG12tIPvaCoL56wQoRP7R7
fJ0bQw+iU6/Rg/Iypkwq3t8NNmFm50YBRebZ1NzUfwSVuXNpdIH3j3QhJhKZY7Lqwhg4wNs+XRVi
UJdEUCcLEDakpwyzPC6ymbVE7YA/OkiYfWXgVBAllJtKm/xWBTyLDTVkpiv8ak8o2+32NZEkMWQb
o5WrZ47p1gywXAH8loh5RQ1NgbFjnzxnP+OjBzmmS43zvxGjiYJVFeLe3BITVbdgWrbqJpx6sdcu
gqm1pSSmqGBAtlOoI2Ig1GZ4h3RDOTranNEFOd5pi2ctMvpOFV/NXEDKcL9ERHW7Y4jd686c7Lvb
yQNcbAfq1yTWYmw+l/TMt5m/me8nzdc5fgA1yKZejzemWciLBmA+1q5GZZHUgyhO8MM3RD00L6Qj
ndez67B5TBvwBryu/hzhF1W/TsM3hySa0HzbOewdW3JT39zy1iigwNvlumFRc6Q4dAWyXFwTFvyu
Mg+gMms270Ak9B2nfWLH+N5yiIcxD18CjQbHgzE8vnmHnW8wnc38qe8H40E4nvJozIPxJArDiX/i
H/sns5NIHMMPewMnLTYouPqDzlyq+LlRi+287YIhMnwnIts2ApTOE1E088NgeuwPfMGjWTThoZhG
g2k0m8zENJyMwyicjaZ0ntqkspGsIj9RbU5jI0xYrOWjyCBtFDXkg+CP4OBGUL0pQHac3p/g9wW4
4Lc4N6NR77jzxx//AS6MIRY=
===END CRASH DUMP===

**Comment by 64FF00** [comment]
#127 .-.
