### ISSUE TITLE
Add lang

### ISSUE THREAD

**Issue by samalero** [PurePlugins/PurePerms#129]
Please add ukrainian language support.

**Comment by Pub4Game** [comment]
@samalero If you know Ukrainian, help us translate the language file

**Comment by 64FF00** [comment]
@Pub4Game :+1:

**Comment by samalero** [comment]
Translated file: https://cloud.mail.ru/public/Fw8C/WAKXk9KJe

**Comment by Pub4Game** [comment]
@samalero сделайте запрос, что бы @64FF00 принял ваш языковой файл.

**Comment by samalero** [comment]
Я не особо разбираюсь в работе с гитхабом поэтому разьясните поточнее...

**Comment by Pub4Game** [comment]
Заходишь сюда

![image](https://cloud.githubusercontent.com/assets/11244874/10868756/2e97b618-80a9-11e5-99d0-89b122f0c957.png)

Создаешь новый файл 

![image](https://cloud.githubusercontent.com/assets/11244874/10868757/3abc0944-80a9-11e5-97c8-d05dadb03bee.png)

Вставляешь перевод 

![image](https://cloud.githubusercontent.com/assets/11244874/10868761/54738c7c-80a9-11e5-963c-53755d4d2625.png)

Затем пишешь название и описание 

![image](https://cloud.githubusercontent.com/assets/11244874/10868766/643dd87e-80a9-11e5-9433-21b0cf6c2734.png)

**Comment by 64FF00** [comment]
@Pub4Game :+1: :+1: :+1:

**Comment by Pub4Game** [comment]
@64FF00 ^_^

**Comment by 64FF00** [comment]
@Pub4Game Thank you so much :D
