### ISSUE TITLE
YAML to SQLite?

### ISSUE THREAD

**Issue by legoboy0215** [PurePlugins/PurePerms#134]
Title says it all. Like a converter! Woohoo! :)

**Comment by 64FF00** [comment]
@legoboy0215 Added it to the To-do list ;)

**Comment by legoboy0215** [comment]
Sorry!

**Comment by legoboy0215** [comment]
BTW, also YAML to MySQL :P

**Comment by 64FF00** [comment]
@legoboy0215 Gr8

**Comment by legoboy0215** [comment]
Gr8???

**Comment by legoboy0215** [comment]
But I thought all SQL statements are same :)

**Comment by 64FF00** [comment]
@legoboy0215 SQLite3 provider has been removed... Do you want me to add it back or meh?

**Comment by legoboy0215** [comment]
Why??

**Comment by legoboy0215** [comment]
Now, I want a YAML to MySQL :)

**Comment by SURVAml** [comment]
Would also need a YAML to MySQL converter. I think it's very important for bigger servers which have YAML files because MySQL is a little bit more performant and you can access to it from your homepage for example.

**Comment by legoboy0215** [comment]
I made a custom one.

**Comment by SURVAml** [comment]
Cool, would be really nice if you could send it to me.

**Comment by SURVAml** [comment]
Sorry, maybe you need my email :smiley:
support@surva.ml

**Comment by legoboy0215** [comment]
It is limited, because it won't import the multi-world stuff :)

**Comment by SURVAml** [comment]
No problem, I don't use multiworld perms

**Comment by 64FF00** [comment]
@legoboy0215 @SURVAml on it now :)
