### ISSUE TITLE
I would like to see you the update from pocketmine in the reviews

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#140]
Because other people like me doesnt know how to download from github,you fixed errors in the release v 1.2.2 but what i have to download the source code zip,the pureperms v1.2.2.phar or i have to eliminate the v1.2.2 or i have to download the source code zip and put messages-it.yml? In the folder PurePerms?or what i have to do explain me and dont put me invalid, or duplicated because you dont want to update form pocketmine in the reviews!

**Comment by 64FF00** [comment]
@SoyPro It's already on the PM forums... Updated it a few days ago.
