### ISSUE TITLE
create gitter room

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#144]
^^^^^

**Comment by SavionLegendZzz** [comment]
yes i would like this too

**Comment by 64FF00** [comment]
https://gitter.im/PurePlugins

**Comment by PEMapModder** [comment]
@64FF00 that is a group-private room that is only accessible by members of PurePlugins. You need to create the room from the repo.

**Comment by 64FF00** [comment]
@PEMapModder Ow sorry, I'll make a new one later

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/commit/cdb0acd3688632e261be461f183490de38b98d19
