### ISSUE TITLE
PurePerms resets for no reason with strange console output

### ISSUE THREAD

**Issue by UltimateMcraft** [PurePlugins/PurePerms#145]
PurePerms started doing this, then I reinstalled it and it worked fine for a while now it resets the tag FOR EVERYONE so [Owner] UltimateMcraft turned into UltimateMcraft and every time someone speaks this line appear in the console

2015-11-10 [17:16:07] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PureChat v1.3.3': yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 33, column 10) on _64FF00\PureChat\ChatListener

**Comment by Pub4Game** [comment]
You have incorrectly configured the plugin.

**Comment by UltimateMcraft** [comment]
@Pub4Game  how?

**Comment by PEMapModder** [comment]
Reinstaslling plugin doesn't reinstall the config...

**Comment by 64FF00** [comment]
@UltimateMCraft yaml_parse() related errors = You did something wrong with the config file when editing it

**Comment by UltimateMcraft** [comment]
Thanks!

**Comment by RafeeSamith** [comment]
Wait, You have to uninstall and Open the Server, then close it, and install it and Open the Server then close it again. Then the config.yml will be reset

**Comment by RafeeSamith** [comment]
If thats confusing,

Menu→Plugins→🔍→PureChat→PureChat→Uninstall;

Start Server→(wait 1 min)→Stop Server;

Menu→Plugins→🔍→PureChat→PureChat→Download;

Start Server

config.yml succesfully reset!

**Comment by RafeeSamith** [comment]
Hope this helps!
