### ISSUE TITLE
New's getUserDataMgr

### ISSUE THREAD

**Issue by CrackzNovitch** [PurePlugins/PurePerms#147]
The code is correct ?
$this->pureperms->getUserDataMgr(IPlayer $player)->getGroup($levelName)->getName(), $chat);

but error  :-1: 
Parse error: syntax error, unexpected '$player' (T_VARIABLE)

**Comment by PEMapModder** [comment]
@CrackzNovitch http://php.net/manual/en/language.oop5.typehinting.php
IPlayer is the type hint. You don't put that in the parameters passing into the functino, but only in the functino declaration.

**Comment by 64FF00** [comment]
@PEMapModder :+1:
