### ISSUE TITLE
Crashing Bug

### ISSUE THREAD

**Issue by DevCraftProductions** [PurePlugins/PurePerms#148]
My server keeps randomly crashing and it always generates this exact crash dump

'PocketMine-MP Crash Dump Thu Nov 12 09:44:04 EST 2015

Error: Call to a member function toString() on null
File: /PurePerms.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.1.12

Code:
[652]     }
[653] 
[654]     /**
[655]      * @param Player $player
[656]      */
[657]     public function unregisterPlayer(Player $player)
[658]     {
[659]         $this->getLogger()->debug($this->getMessage("logger_messages.unregisterPlayer", $player->getName()));
[660] 
[661]         $uniqueId = $player->getUniqueId()->toString();
[662] 
[663]         if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
[664] 
[665]         unset($this->attachments[$uniqueId]);
[666]     }
[667] }
[668] 
[669] 
[670] 
[671] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpe 2.6.32-042stab111.11 #1 SMP Tue Sep 1 18:19:12 MSK 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
Sheep 4.0.3 by KnownUnown for API(s) 1.0.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
NameCorrector 1.0.0#build010 by PEMapModder for API(s) 1.8.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
Farms 1.0-non-alpha by hm for API(s) 1.4.1
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
AdvancedMOTD 1.0.1 by Philip Shilling for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
BanHammer 1.8.5 by Comedyman937 for API(s) 1.2.0
ImportMap 2.2-1.5upd2 by aliuly for API(s) 1.10.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ZipPluginLoader 1.1.2 by aliuly for API(s) 1.10.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
HealthStats 1.1.1 by Striker209_MPE for API(s) 1.3.1
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
Greenifier 0.0.1 by itmedevcraft_ for API(s) 1.0.0
PlayHarder 1.0-TEST by hm for API(s) 1.13.0, 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
ExtendedCreative 1.2.5 by NikoTBC for API(s) 1.13.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
PaintMyLawn 1.2.0 by shoghicp for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPA1T3EaWf6UPp2ohNZpvBpgUqSXYjr0Bm/OQ812iLaoltUYKklpRS+BJyv9933vdklqChMFw
uT3Kyaifut9Xv8+WZn7fKeNU7Cwn8/nBbHY0n88HO6IoZLGz/H2n3ORwa+fV1asPH95/2BnspEIp
vkbYKU8SVkrGWSpSTxQsrDK/jGUGwFVZxNl6d4/BKKuSBBaGcYKrRhdVIS5EkaphHvFipAp/dLWY
v349Hre32itYmMQZLFwsJp8HO3lSreMM0NgTfBkI5HWxP4U7DP4+A3SxP4MRXcwNePT11zTeN2P2
Nft7zguesouEb0CCr3L6pEmLZtKIxgdmnFdeEvutsFVWiHWsSlFoJLtdXHu0+NAs/p1GRzVq+Puq
jGLlfLsW5Zlcr2H5nvNtILxqvdveOdc633V3EppzZTZBDfvE3Z1BTZhWvuOp2N3b2/sG6S7GRiGL
ic1AlcW/VuJtwI47S380YGSo3VCNaFojmlmI4nA3VkqUNeO8LLkfpSIr1c8NkX/u7bVUCpHKG3HS
zHtgpaY9r2nvW7Sr7GHCevnCNpEFbqq+gh1CQ8XLo+byYNxeTvQlGGFZcB8M7uedF2O2u7dkufSv
RZmCmbruShQ3KJpfcBW9rNJ815MyETzb2/nnYGctMlHwBI0VZikwH6A/GS4CcQNMeFWcBDvL+SHY
eSFL6UuYOQNv5HlM8yaz4RjmreMShuMt/2BBwa+T2MM1wwPCUGUcPX7nLM6qTyz1c8Gmw8VwNnXG
86kquTeZALUJezFhq/MLdlkJthI5m7DJ4XJytJxM2fnqBzYdT/bZp8MFuC/gzKMcMO4DmgmS+E1k
IMsOoh3ru1dS1SQBQIOEBo1fK1TMSRJzujA86vGgo7Ap4eRVGclC4U78xP033L9GHZOyfkZt4SwA
iIx7iQBmyqISg51A5MAaroJ7SoblSxuQcgovRNR1z2F0mnBFYUhyFOji/ery4/sPZy8BdCs8FZei
MYyT1Qeb8dWHDtvAznDaZTv+h1RRxd+8fDbGG4yuG5+fXrxyXWDDdc+AeYprRorV5cmHyx8vbBl2
orLM1XI0AvOKKm/oy3TUYBuhMCDhOc82H2WRBPYOWcC+vLOuvDyJq2TTFXb85cJqdK6bAgO3xIDe
su1265Lnl/KltASpIV0ppsNJV4rXPOla2hNEKHleykC6bkt7C9bb7Ncyb2dE21fQnrr862zb3YXZ
l4tgsrfrNhxYl482OVqpo4FVBYDMZ/GNWMXrzJa5hfXjw+Rhw5s+3fASoK+Q/lZ2d5+4PBG/8Cwo
JGActYnEMQFxVBZCjFKOGX7USgvq0IkGqCaWPiygrZDx3chTKj8qgBzbra8m09nf1yBfgnztPZt9
G+x1ZkTe7OttVAYau729HdaohpkoUQMnAWjqdZXZIbcGdc1h3E8XkdzEWTqZp/5dkxi0iXb6FMlr
XiACt1xt4duvfJnJdPMP6VmCWcB+iJ13RZOZ8OC/O/tHYpnPafM5oc+ZGc/MeG7Gcxh/ofSGDdcV
mvNfpOe6HSm2UUUGSetC8MK2cQvYd/petvkfqVQUHx0d/aEyvlC4loXH5JtVJERuOyuNbRnmdzPm
D5m8zX7E/z2XR7YYwQ+RBfOxbfBCV7QCWItupNGApG+zm5UQlqgG0I9Jk//rmKT5qj+fEIuwzzqV
RSH8UvfNRvAu/E5UekEl/3jSC08Xr855fi4DLNlsmQ+/XOYOI67b52sL8z2FLqY44+u1JV4L69cc
PYnOBLQ+wfsQS9Ln2saG+N3yduv0a/M1aqVpw/DJxdu7YRiB/TB89P8iDAMvTRjWUmyx899Vm9OC
h6WliAb0QN2FpXJcXKvn2nOv2vhI13UtDrZPqiuRJHe3k6D9/Tx4eD8frCBte3nEJingp9klw9wW
Mr7m3YZAj3sxx8lk5vAkj3ivIko7oj3B5KLUdYm0+diOeeofLwpZQkSyZOiA+23ZeLvmcvBMxT51
mLnmpZ/3t2xuHlPtd0QHDb0UN5dSJvYON6Be9L1T714QqXMgxS4F72717Mu3uqbvuhYnj2z3Gs5G
DQ6q7W945ovg/P3ly059b4H72bQXei6iOIlztoKPJM7Wz9b75YRXGbSuyw1PqSyDrQ5a6pCklMjK
mCcKUqIVk2xwP6tO78uqSqevuzv7FCltNp4rv3ZEAw18EDy5pEcPjfQNqOvrk/7mfg91U8KrVMz2
J8+VW2rajz/2MxbwQ1yqe4yVwP0yvydPUvl8ephDMflsJ5gW9S8+nWjYGnWEwYJXlJEoTiOhOjJ3
wHfOof6SM5lM+Ej+LzmR6YgLWvkviNYfxC0vAksnFtDSCBh115df/vdWxeITDuqAhOu23Dymd4Vm
1xdhlaxyfmsfuHThHfHmfyqeXeM+RZwOA4+R6DueveFpKuxurYV1TfdwuN813VOZimCT8uxodtAR
q2+/IQS7beVpqD9GjLdpLosS2kW7225gvYrJmQz3qzyY/q8eyjfUH7UbBczxyans/bCgvWCy6Mrw
6kYmK2Do2aKJRXrbWs8cDQhgBbEOy2sMCT/FuT7ONjm0la5/54Fk/8zb1KP+FxS0fXnrqv9VEJcn
xZ2qvwbfOTS58kTJrwJxc/ViPD/c7uTkCYrKRcrzlFCaHkAAZ7yADNPj87GZxmJ2tEp5kjg/nToX
f9QK1HRAbW+gUimjVck7udeGPpB68Wn+tSim46Or896BzBPaAYsB1+1ys835kkw9bl6CsI+YbPAD
T4HPeOrJZwsBhM11bQYeE9Lq/j2S+T1HDgj9dzpyAH7aIwfN3DZH2vE6+8iLzql2Deru1f421d+X
d+s7r8FTLgueqZDMpNM8360R8ZkdlED5X1IkNhoxD25PI172ntsSqKuwWd+473tq+9AzDOuh8H0q
oxeYFKhp5w+e5iJf7dWTn+USEtDC96CdLA7jjqNbwAeeE8QlVF/ihg4Cr54rzLfkXbfDyjbVccI3
b6Ci7shjAftncJevVpd/evz2HM8fW/qwgzYvW/l1mifiBPjreHYD7Ap0cOfopXfcBExGch3Ffv5s
wbllxnU7jH3x8ZOFBaP3pxJoiuC0ELyMb+wziju3+lmp1yy8i6/l5Xenz/a+RZ8+xO27HG11Xtz6
v31q3EL7EalXkV5S9yuCq2fbVYs4nh7T4BFNKswszzdnvRbVgj5QP9xrpU9wwRofOGDLxPY5p2uq
NbKRLdBnfHcO32AVkGlqbujlimFeyFwUZSzwRbsXF82IncosjNcM38d1Czd7cRlV7J28YZMpGx8t
57PldMYgQNHrfThB43NQncfoKRR3l+ziFdOvcVhzsPM7nhxNZlMErmEFFM7ieIyjlH9y9Iuf6niy
TyCFTbtjjtRhV45nRPA2Ah04SaxKvVKr3vm1EsXmWGYWqICCxUDwcphzpaBED46/pj8gKsvg2K3G
Y35w9PvZyfefmR7Mv4Mewlwv3hdeXJrBUW2CiJNnmawyXxi+He5HsbgR9GbpsQxDmpMk8tYJk3gd
lTVMy8WzGIp61QWm0msgoSwAd6MlA40gTvuyaMb5TW5EDOIwjP0qKTfHE9IvvU1aysJRoizjbK2O
EZwAi4neLpKshSkhAmsKvtt9/Prs5JLkqErpKH4jDDF8Z7Opa4abNEErYmi6zCcDqoA0vv+MdsRA
FNbGUuf8AuyKXUZCCVbzxnghGAQMBnWnggteMh8VXDJPsDjzkwoiGFywO/aLuFYyhZUhIujjVDwU
AyYxFilEyTwIg9dsI6vC4GJxyEDFmNGRgq8ffEMhCIjfidsG3SgQIQf9KnYrs7+VjOe54AVD1aQg
rA97vcE32vE1Yy33bSQyVuXrggeAYOhm6Aoa2dLNGPgWlBJOAiDgIuHZuuJrwfCFdVKZcRsVwziR
gD/+jZSKS08j4RspuguBgTqTiWx4G1/HOXSkfCiL9QhHozPwnCsZXr1dvb9azI6c6RWuAzU2iJbM
hYC2dneQ0MeI4ji+yq8ghDF8rV/R696wTVhSJ7wEvdFt0iZxCnzAlShpS6Eai33BIiiJE9rkFBBr
825J0lkYwFVUlYFEX9BvsSMz2vn8E/06vS+BDDo4o+8hAF7FpO9DBRkMjZ/yFWzihnFPViUZ03/U
DnyRCA4m8osEU4J/GgqBRfu6Y8aTMUgDhhyoodbCCfoxw6ADgjNTx7ObmLP/xLgDUyj+1BX+kmEe
wIXQLd0yjk6hJHBshNKWwQ0iVimwecgZIBspE9ozmAmJJ8BtaW84ILgnlWjRv6JIV+MBBTMMDgy8
AwwQWfU2zJgtTDdxsbnbav3Fxxj2VWZgwTwIWCGUNnRkE0z7GtjhCjSMwY2BeXsC9QHKF79WnL7n
sYbKImM3PKkE2zUkIUnsAXJND+KxwAzggPFgt7yEu0j5XUVfDwHvPVGbzL/k6hocrLgGfx3i/R8V
aATdoRYSZ0UF9KIVWCDMVgNGBy/MRDzwkAGoIQWtKczmpBbInQhLqwwcFacQ7hVZKMgDvlzITxCR
SwEqAHHIs7KGNdSqZudtiAGBvtkCjj9gcfk3/KJLQasCgbmKjL63lu2CBLDPbIoaIRkcI+WSMGFw
wFBfbCg0fJ9IDxSLtQPTYLC+FBIRaCAVa+5tSmCIrTQrYyIeK9xeHVhAptuYGCNlM0xDGk+tf0V6
CWMwF4iKEPIzQhVCSKop6u0HYSoy2rUEOdD5SGdAZ01MOsTYko1dikyUBEqIbDz4N2cf67A/YR5T
7ZOYV6XMib6JjA0/Bpti4FJYlIig5gZp9liCBj2WlPrQERVS8yn4G9YaZ5uYmIUGRjMccAah3YxS
hswgeoF7gtIwNPyRTrUuocxKKJugo+tpLiV3xAGu17qxjkVI4T3GD8ymNH14dzLKbEpl0F8ufEy6
inSCvGoF67WNAKBGkatWzFkTm/fuZchIPdNSr3nhweY7vkwSXUaie92rVbIlZMWsYWYNOG7Ks4rS
u80FlD4VGMLeoA4IPUswpqCDahjWgSFtTWzI3uvcSiMwh0hWSdAwEkP4uM1YyzoaLcuJcxBwMR5r
GdmL1+QGdwIj2Ype3QgVFjKt4yuuNfcdOyRZewpCmK3rm8I99mOtw3rej6rsWml9n5HJYzQkIHKG
HQ5Kw3T9PCDfLKDYUXqSg/UG1k0tLkRVb7PxkvnC8PlS6mX97cMMgFWZXmZj0FTMtGeQmbKQ43N8
wkxSG1uoCeGNNuX+KS43y0SJm9HUiWAbic6DHi+h08AyhGNJDekPDMrEJPJAXQWbuzoUeaLJiBRs
XtjBq76Dnl9sSsQ9YM7EsmbMfETWKWtWljBDR5U20VLjgFku0LHObKBeCkDD0pC9gX4I1HsMdTcY
7unFjwNYCwx4EH9u46CMdMgm/27QO4R+ySamKmjrBUV6saYO2UkA/hTxJBxBQ6FLmECAnRlCQFLb
n8xsh2xSs4XLKrY+oe9hCcSTgfZrpPsxzqBgBanAagRZNub5Hy+yi7pKaNsDLIBwET1hx94gyx0z
tOsx6ObwS55LU3B8yyZYaJisghUl3a6rSUVhLBJ1lemanTCq0jWiYiNV8rICcxmtfa1ZCGuBsojW
fWCnRRF1AYl8gyS6OaOpxrhQXNpvH0+YyL7MEkcvWbLUx2+i6tYFBKJTEmQXDA5MlGIS7+CHwInN
X2mRB2WWd7khF6Wde/Hu/eWrJaOgC/+gIShgq0DpiIiO73DriD1DuWGv3uGTzmb50LFAHDGikg1R
QgJG0GZKtJvp2CQQDGQ6L6ERYbuMcJOMDP4uuI5gugxeoa+ifB72Jy2x3Qm4yT1UBmwKNyb33RCl
P9wjj1XC5oKs4RIxYxNnTluYgLCk6WHi1xtJ7XLbR2MUoAYICyeMBTy55RulcRs8bezqBG8yopNU
Vpkd/ZWp1moekHtEhs0CBGa8hMj+x0t5AdBAs65xdFMOg47uvsVkWpnQ/aonNDJPhBiF6AQGoxVu
QoNUn8tYUY+UuOI3kG+xrouxKxfYduUbcwJh0lBTy1CQCOlpTx0RTQQLq4SmSQVm6qB7xr7OItR6
Fdj2g1UA2lpR1Ldy7ReKp2goKYVJzC2N9N2dQG3WO3HOPzHe1wq0Pj4lhtYWuhtBBvqBB3GlrGVm
E7hhjvxTLzU2h/NhKzAc4fmXU+UB2GHbHPv4Rr02Iuys+3y37VzN+vAu7yby3fKYOnPowithNtes
J4cnuKNgq5bs8Iuw5TKvEoPNXGNOshHvI+/kjg4oD5nWh3wOGZFCRaImU4jSJZ7rGOjERAY8Xlsy
XdXVG4rfDa/yJTvSpZ62RoobusIwuADLAa4yBBEpOgAIgoQaIMF46sVg9nqKOdnTnflSxyE8RMDv
pzMN1cnV2Ii2XVPCNxuJVu3gKVIX0iSSDjSP8jgLZVsIRRL3nkgOrUNFKICIv0xmmxTre/IPBfpV
DaPYsJjbrL1NDIOpccbXa8g75kigOWzB4hC/pX99vzSaH0Sn7uMH9aUtmba4vxpsQt9d6g0oMsek
5WaKhsrcOiY6xYNJOikTicwxTw0YvsiCRyz4jXtdgkFJEkKJLEDZkJoyzPA4ySTVCncH3NFCwswD
Dat6qKDQVKXObXW0M9hwh/TtGr/qKQXfYLpHJfh1eF3yQo3EMdPqAZYqgN8wsay5oVtg7NgfL9nP
eOlAfhlQw/xPxKhjYF2A2Ee6JETdKOhurT7npjbsvhNi6mopgSmqFVDsFEqIGBg12d1inagSA3TF
8FgcXZfSUUttyfBsfDn95mCwf/RpMph9mg2m30y+CSAJ66i1i4/5fYwwx4djtgb7Vno039+jE3SB
D+ZQIfSezikkIfsnEtCG7DGkg3XzymDu42QzUL8mcSlm+hccHP1rEb/pn3TQD7E8H4qaqJmP57NZ
wIsWoH/HpR5V+I1KMwjjhN66A9QT/bJpWObN3XX7EuM6bcERuLJ+mA3zf1Gdr/+QvgP9cxOT4b5h
N/X0mXKDAgrGTV62IpYcOQ5shawuzggLPnfMfaj02sUbUAn9wIS5Yvv4nsAEiTEHH11Nx/vjGVx+
9RY7aX9xeOgtPM+fjYPZgocz7s/mYRDMvQNv3zs4PAjFPvyxr4DSRYSKa36uIZcq/tRui+nkzYQJ
CvxBhKYNBSjRE2F46AX+Yt8be4KHh+GcB2IRjhfh4fxQLIL5LAiDw+mC6Kkola1mFTmf6koaa2XC
5FJeiwxyUdFAPgp+DVFDK2qI70VuOD2tqd/7+i3O9QifTH/+/C/e5QS3
===END CRASH DUMP==='

**Comment by Pub4Game** [comment]
Please use new version plugin PurePerms 1.2.2

**Comment by DevCraftProductions** [comment]
@Pub4Game I've tried that and it just crashes my server.

**Comment by 64FF00** [comment]
@DevCraftProductions Please update your PurePerms to v1.2.2 and open a new issue with the latest version of PurePerms
