### ISSUE TITLE
Call to a member function. AGAIN!?!?😢😭

### ISSUE THREAD

**Issue by RafeeSamith** [PurePlugins/PurePerms#150]
Hi! its me again, So this Error happened in v1.2.2

Crash Dump(its usual but who cares):

PocketMine-MP Crash Dump Fri Nov 20 12:45:21 UTC 2015

Error: Call to a member function getGroupPermissions() on null
File: /plugin-862.phar/src/_64FF00/PurePerms/PurePerms
Line: 387
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.2.2

Code:
[378]      * @param IPlayer $player
[379]      * @param $levelName
[380]      * @return array
[381]      */
[382]     public function getPermissions(IPlayer $player, $levelName)
[383]     {
[384]         // TODO: ...
[385]         $group = $this->userDataMgr->getGroup($player, $levelName);
[386] 
[387]         $groupPerms = $group->getGroupPermissions($levelName);
[388]         $userPerms = $this->userDataMgr->getUserPermissions($player, $levelName);
[389] 
[390]         return array_merge($groupPerms, $userPerms);
[391]     }
[392] 
[393]     /**
[394]      * @param $userName
[395]      * @return Player
[396]      */
[397]     public function getPlayer($userName)

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.7dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-3569041 #1 SMP PREEMPT Fri Dec 12 20:16:40 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
RecipePro 2 by Array for API(s) 1.10.0
FurnaceIndicator 1.2 by onebone for API(s) 1.6.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
MineReset 2.1 by Falk for API(s) 1.0.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
WalkingParticles 2.0.0 beta by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
BanItem 2.1 by LDX for API(s) 1.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
VanishNP 1.0.0 by iksaku for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWglvG8eS/iu9tLFPCji8KUoMFKyfLCfG88GV5PUCYWA0Z5qctubK9IwoJvB/f19V9xyk5MSJ
jcUaCTTTR/VXd1UPf+8UOlad+XAyOR2MxtPRsNtReZ7mnfnvnWKXYapz+eHy6urtVafbiZUxckNj
FzKKRJEKKWIVr1Qu1mXiFzpNxEYVP+ZpmS1UHmtjMGSOjgUmkjKKQGOtIyLQz6JyoxPv9GTUy0KZ
903u9z+cTF68GAz6izJXtN80T9gZ6QQ7x6ezT92O3Q067QV+GijCPZ6dYkbQv+/Ef2Uyl7F4uYjk
DjifZvwXq8ezswernkbqTkVvJESCBaeD1oJcFWWeCJnncseTw3qyz+8j956Vq0j7ewJpy+IASLd1
5jHTGTs6v/PbpDoF//p9cfP2+du56PV6PDltTT7dkNTFuXhahNp4P5RG5c9lIV9vcu+HSilHj536
PdM6AS1+mD0gyvIlyvzWUGuz9YDeaZsMgampPI7vnVtSE/ws0jOH9GzQOqKtng+xyjfqqAW+24Jg
qZxV6vvEb6OKZiX9/nff8fvkoY0QpcpEzqYPTWRRW9jZyb6NnM3+wEZ411FN/bgDMy9y6cOkf+48
GYij47nIUv9WFTEcYbm8Vvmdguz8XJrweRlnR6s0jZRMjju/dDsblahcRuQOWEUixdHD3ixQd0Cy
KnUUdOYDOFKeFqmfRuRY3Y7MNC8bjnsDLNvoAq+DL/yHDbm8jfSK9vRmTKFMSFDzziudlPciSn0Z
hakpBOj3xkNvPD05G0yG4slQXL9eiMXV5eXrxY14kWvxXPliOBKjwXx4Mp8MxL+ub/AynEDF8d2M
IkkWZqA87Z30Rnj7TSXgqDPC68BOfkhNdTIG+EUmQZ7qoFNHEEMCutZxFqlnZRHSm0PcGuzui7A3
xIjERJob0s2ClfIaShE3SsaYNGG6CbWfkSJYpD+TTEcAhgGVyFWkgLXIS9XtBCoDciKEOZOui+ft
gVhylGvAQO9tYFEqievrm2dXN+8WGNiqldEFMRAWRWbm/T6UGJarnp/G/QZpv0UFwrhSvs7UIk9b
AmjGWvyP2pz/3JGRLiMKhz9GuvDDWJpC5R8Wl51f9jgf/H3OaxTL5WsaqVlevL2+ef/26tXzNtOU
Y8DOC7ghHOdlEmhfFjaZOa4eTO0rd7Sv2jRRK/y/p8eTv8+MI7dcri0KXaFYLh/B9QWMPou2cmeu
M7lNWjy2R9vsjXqjQwYXoY50Jq7xB+l1880MNmO6xpFdLiVDMgRpuXwFxlT+h9br+PunNNr/6d3z
FnP10L7iBr2Tfc6caX4rhiy55TIsgy+yxMfcT0bqI0cg0Oo3odxzoahf5Er1rQ/1azYhhetIZplq
W3E1cmC8vem+DD6mH1M1o3/fTA7Gnrxcxl/sjfoiTQow/a7FQDPWYmHYG+/BfyGjW53fmm/lftq3
h5bLZfv8L2CBQuaVMqposdCMteNjb/iAhT34XxEKyVZyOhAG2Dr7C+A3RXIDv1047xvRQYiwNfk3
MyBX4y+XNYDW41/PaLTTuU9DBSy/J9tJNguZF9qPVJvzB1P7MRIaEitVyH0pXOzQ5VyUK+X99C9O
8+I/RZjudBIPJ7G/Lx1bPI2+RteHGJfLR1B/geZv0N1dpHGMsLMXQPbHP5fgO6+e/+8D6+0Si+7v
yP0du7+Tv88xjlou92D9lYz/T5m8LFS8lyfsyL5yD0q3x/j7Gvzu0L+CvCnEflLRQZQ/nDo01MnX
p7x2nfsl6Y+B/J9kwAfcQ1j/IxNtwjeLlpDqocN6YLAvHH1r5G35lWGsc2mMSgotI0NFbi2eCsTD
2ubPVf9e5tkDpfPggekecvRoevwbPL2AvG9ymZg1A7+O0m3r9TMcr93hy6VhwFsArnoTB/4LE9NF
KIuDvMRD+/oc98Z/npaGf2bsTYp4TAzcixvqeD6TrghX8/TVyYqJfKJelC4WFIy+UhC39j305rD7
QlP26jxZ1G8CxctabwRdpS3zZfKE+uU36R36Y7TM88lkPp2JdzcX1C9PaYGl55GEz5flYCBn0x8l
oqx9PrnI5bporcvSvDgfng3HIxrcYFecBuqc32J579mbGXM+nA54F1X1Hl0kKJbg+XTIS7chJBFp
U5yn6zUNWL14v5Yq352nSWsoR2XmRgJl/FxnTOg6FUgFO+GXpkhj4aKEQAQROG4DoZn/YFBpEXwJ
Y3SheZ6keSwj3ga+8p0X6ViD38Fo8ppGI7iDV2aBLFQFXCZJWia+cpx70g+1ulMxHMM42Hdabb0A
zEqsAzHeFsGVvHWkN2EtAysshAtgqPbasThdVQOhzAM/zevzs7usko5er7VfRsXufMjK4Wse9Ise
isEC9YE5Zx7oyszqe5vmUdCMGaWC1hKWyItXz25oiLTQy6Qx2BOcf8f/wEVZpJ6Rd8pBYLV6bb2u
0xyyqe3EjdIlTB3he7s4IiMWlDiEz/ZbAjhdfpEZC9AQzfWE93oBsxY3IWpcUXEmZK5EESqBFtrg
QRbCJ80UKNeETvyoDFSAB/HAfYjWdRpj55oIHNI0cq26IsVMboikWOVK3opdWuaOltBrAd70WvMJ
0E0OW0dCBOE3aluT6wdqLaEdI7Zp8o9CUK8kc0EijMGsD4vY0V04XYFavrehSkSZwZYDEOgtEzJW
S2y+TMSTmxAp0YswBBSRTDal3ChBN90sMmfYRuOdb9f0byxU2noRKt9xsb8RAKropJLeVt/qTAVa
9tJ806e3/iso90O6/vDy+u2Hk/GZN/pA+yDGmtBcLBFmN8sOHfQ+VCQ7+h6AXBEI+jZgipzlW1Am
ieBLgZ1maTJS4MCTKlilgbrTvhIhXDtiJccgbO2qORI5xyiMm7AsgpRcxn6PIDD2NlT4UWpUYGE9
I/cTZKhAUgePOy3Ff1MEwhKORFXxMReULmjjdYh9kqzUpEDjTrGqko6QKA2MEKkFhsDcPVu8xEqk
p4Dk1Ex4gLUCqIb8Jce8ig4FM/J1imiwCIK62glnR1juImQ924jhyXsNQacJTEoGgUBraC2PYMLW
bgFHGqQZClMC9rZSJA8IXf1aSv56s9F3WHsno1KJI3ckksYxiNvzEJkVZQMP2txsVD7HLJ38puSP
PnCnZ2aX+DfS3MLi81s4UI/m30EJbJ8Vk7QqzFOEUZgEVpuu4MAkXACDyXYhhhhS4/t/FguSKY3F
ZUJ3Yhhl2tdsMuAHzpWn9wikyDI7YodNPamhkVQtnJdr8lD+XgVP7Apd/IM+X+W8K1CUt9gKD/aK
I3AAPYsRSYR58ByXc6ZE3mqTCPvqj1G6gmCprhB2WHBuoZgUq41c7QoAEtcWyoAP14bUaz0dPG01
A2NhC8oeLke5IZv71hrmgjCFCJ4wqTViRHWiVT+YKdloNyn4SMk1SGY4Z8MgbdKbi8GSQwVH5QKh
Rgb/z+FTWfYH4ClzfhV4FBoZn+9CVY3HUTMCLkU5ElHGoaEzK0hURVhUKDN1yumIfNHQgT4HZIeu
9rchjkKoCcjGeIUHf1DW0ziMpyi/E3go5EbR4XNiteJEdo44wpOv22VLTrhEA97XeLINR3TCWwoh
lOF4ee/hYmLbFdUQYaZ8SoSGxUJYrYzt3poBSFJlpmFzPHB8muNHATmux5brjcxX0L/np1Fkq0ry
sEelyuZEUNwe4fbAd1E8lpxy2yhQjpSwheNuFRMOjMFZg42r63UVG+LGynrirc13/AaLCNMyCmog
GhFkm4gGOtmtyBg5GDwZDCyP4skL9oQHsZFtxe6umVrnKIBd8KG9bt5rR6WWTsGEU92hKTxiP619
VN77YZncGivvV2z1FBB5kJBRz0PciOoDLblnjgLE2EUe1QBUyzS0iFSlZucoZycO5/PUbjtUHyUB
qpTstjYFe4pb9g145kTk+SjqleXa2UJ1EE3U2fsPSS2TRBWki7p0g2lENhOuZIGugQoRSVUuEiDs
yUUldkBbmLpZG4xWqs6JHG6etMNXNUOOn+8Kot0V3rBlzJT7+FivqKAgrExPbFRpci23ApToAhvu
nALtXgw6TD3xEzoZiPcctTAM92Lxrou9QLBC/NnqoAht1Gb/rsl7TH4uZq4waEoGw4JpLe2JZwH8
KZTRuo8i31YxgYKduYNwpLW/NGk7ZJ2dW7RaddLlPTkflUEy6lrHpoPf6wRVJNiC2Sg2bcr17xbJ
oqoUmpqdiiDatEWsX1LBnmSee23XZNS+rsrN3BUdP4ghFRsus1BVydNVRWk4joWqqjSXThVII02d
aEQfTWVRwmD6G9+Klu5HTevQqrXb6xtUVUQSbnBiOyZe6syL2GWF+xBiwRbmtnh2y1zEmNq4fgIM
8YUKwYXJwUg5KMk9+oic1JEVreMhzOIhGvZRVt2TN29vLueCoy7+80s0VwmaKybEF0qkOobnTq7h
1Sp+tqctH30EIonjla2IU1KRstUUZDmjgUshFMpsZiIzomaXxl06cl6/P1zFMFsLX5O7EoMraVTr
sKMhHOWRU7pihInhYxOq8HvH7LRGtVGwOdwQZWqt3PWLUAhM9jxK/VaT3MQ23S0FAu6CqHqicGC/
w1rajk7LjvbiN5vRszgtk3YCMK5mq0AQfKJGLQPdsOBxLiaf3ypzjAYWu6Wxn3XE8Gz06G62rkTZ
PnKlLLWVWlMk4gsUilikhpqqvVZphT4b+a7lHZIu1Xea2mVF7Ve2c1cDLhfVBQ0HijVfSFdh0YWx
dRnxstTAVD1yUe3bVMItWE79OAwDZCtRfUypE7K+YWRMthJzrKQEU/N/oAwSaKWM1/JeyEO5oAfy
OT809rCvCzbSKxno0rS2OT1Ih46d1G51dkfrUa1QTKL7K3cj1gBEq62kPYQvg5osaIE3jV2FvfcQ
vIt/W6m5R0c/XiqnX7ef3Z7HPQNlzcXp36KWpVkZOWrumVLTAeFlwj7pQXoE2t7SeWxHhiRJoowR
qwu6cnGjQxce6IZsLmxxV6mUfo1VZih2bMVnDZKDhy00HC1QmdEudyARndLrVtJB9SCPyXilYfl2
ibucsz363AYjuk6gX4QJO2pzrDMSa72ukq+DG9m1Rxc8+yN1OtkbzcJMJ+u0MQP6OdfcHtlr3feh
EGJ8SZrsYirz2UMM5GtqoNS3uGnRTDNg2JoUcrNB9nGXA/W1C9WI9Lu428e5sXiInHkMD8nLmjKr
+HA3bMLOzq0C8sRzybmpAHk0zVoXRhd0Z8iXWCpKM8pWXf6ETJctQOJKMVQma1TKCsJGfkooz9Mi
l1pL0g78sUVEuA8grRqiRMFpCpvgqoDnqJGG7HRF3xwIZbvdPiaSSCPdWK1c3kvKt/aFChbQdyDm
FRqegrFTpzwXP9OjhyTT5db5F6Joo2BVhrRvW5mJql+wTVt1gc3d2GOXt9zcchYzXDEQ2zEKCQ2g
LsW3oPOpDICfBN13k+tySmpOmwu69J6Pvp91p2f3w+74ftwdfT/8PkAmtlHriL5F+hRhzk8HYgP7
NvZtMj3my211X6iEf6tKX68ukIdav0YkE2q9Ih1sOnN2mW4n82mpezG/RrpQY/uTSc/+OvM3+xtK
+3F95aOuCev1dHGaBDJvBuyvtKu3Mo/ql7WOCvqgDNJD+/VwXWT17CZunkN4r/1sikUfTf1TEPpc
Hq/sXW69GDXhLisaDgpJgIIWu9eLV3wqPWc+arlm7w4M8w813ZOY9ggdcS48+mA1GkwHYzw+fQm9
rcezsZLTIJhOx6ezk+FkcCJPB6ORnKxO5Xg2mQxPV6PJQImnOGkRklj4wzgfnBp93wjdNetuwZAY
vVJr12lilM87VdO1L1GpTnDsYD2b+bPT05PpFEePz0ZjNR6szmZnQcDnmTBOGxEadiyzz6m2wsfi
Ir1VCfJMXo+8V/IWEcEKin+5tZP8kYR+XkELftOZfRv1Jp1Pn/4NQf0vJg==
===END CRASH DUMP===

**Comment by RafeeSamith** [comment]
Should i find the syntax error too?










Thanks,
Rafee

**Comment by PEMapModder** [comment]
Wait, what, syntax error?

**Comment by RafeeSamith** [comment]
nah, jk

**Comment by Pub4Game** [comment]
dublicate #143

**Comment by RafeeSamith** [comment]
Thats of PurePerms v1.2.1. This is for PurePerms v1.2.2 think before replying for God's Sake!

**Comment by RafeeSamith** [comment]
Duplicate*

**Comment by Pub4Game** [comment]
The author had already checked the last issue and said it as a bug, why else create a new issue?

**Comment by RafeeSamith** [comment]
So u call urself 'The author'? Wow
