### ISSUE TITLE
Nametag Color Issue

### ISSUE THREAD

**Issue by iWoof03** [PurePlugins/PurePerms#156]
Hi, I am now running 0.13.0 and noticed a bug where the nametag above people's heads are not colored where they should be. (the chat works fine) I also noted that if you re-apply /setgroup name group, everybody who is on during the time that command is run will start seeing the nametag in color, bold etc. until they/the player leave. Please fix ASAP! 

Thanks- Will

**Comment by 64FF00** [comment]
@iWoof03 Please open this issue on the official PureChat repo instead of posting it here

**Comment by iWoof03** [comment]
opps.. Sorry!
