### ISSUE TITLE
Multiworld perms not work

### ISSUE THREAD

**Issue by GAalexandres** [PurePlugins/PurePerms#160]
If I have 3 worlds: spawn, survival and nether, if I want to have the permission to do /tp on the world "survival" the following happen:
1)Join the server and spawn on "spawn" world
2)Teleport to "survival" world
3)Do /tp and have no permission
Now these can happen:
1)Go to "spawn" world and have the tp permission on the "spawn" world
OR
2)Go to "nether" world and have the tp permission on the "nether" world

This work with all the permissions set for the specific world. Sorry for my bad english.
I use the latest indev version.

**Comment by isoz** [comment]
Can confirm, was trying to assign /fly from EssentialsPE to certain worlds only and it won't recognize that changes.

**Comment by 64FF00** [comment]
@GAalexandres @isoz Are you really sure about this? Could you please post your groups.yml here?
