### ISSUE TITLE
My server is crashing often (20+ times per day) and the crash logs are always the same! How i can fix it? :(

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [PurePlugins/PurePerms#161]
One of the many crash logs:
PocketMine-MP Crash Dump Fri Jan 1 20:36:28 UTC 2016

Error: Call to a member function toString() on null
File: /PurePerms_v1.1.12-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.1.12

Code:
[652]     }
[653] 
[654]     /**
[655]      * @param Player $player
[656]      */
[657]     public function unregisterPlayer(Player $player)
[658]     {
[659]         $this->getLogger()->debug($this->getMessage("logger_messages.unregisterPlayer", $player->getName()));
[660] 
[661]         $uniqueId = $player->getUniqueId()->toString();
[662] 
[663]         if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
[664] 
[665]         unset($this->attachments[$uniqueId]);
[666]     }
[667] }
[668] 
[669] 
[670] 
[671] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux host13.adm24.de 2.6.32-43-pve #1 SMP Tue Oct 27 09:55:55 CET 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
RestartMe 1.1.0 by Gamecrafter for API(s) 1.10.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
WorldProtect 2.1.0 by aliuly for API(s) 1.10.0, 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PvPWorlds 1 by  for API(s) 1.0.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVO4tS3Ea2v9I7pGohNZo3A55bpC6FcdYpMLMGx7dulKJaUmtGRlIr6hYwSfnf95zTLak1sDHG
5D5wUkhH3ef9bIk/ejrJRG8xnu2P54ej/cPDfk+UpSx7iz96elPAo97p9en79xfve/1eJpTiK4Sd
8DRlWjLOMpEFomRxlYc6kTkAL3WZ5KvdPQZ3eZWmsDFOUtw1XFalWIoyU9e34wH8m3jLc7iaR+J2
UKx5OVRlOLyez968GY3axe0VoEqTHFDN5+PP/V6RVqskB8TuglBGArmf70/gCYOfzwCd70/hji5m
Fjz8/nu637f37Hv2nwUvecaWKd+ATN8V9JsWzZtFQ7o/sPdFFaRJ2Ipf5aVYJUqL0iDZ7eLao82H
dvMfdPeqRg0/3+l1orwfVkKfydUKtu95P0QiqFa77ZNzY4Vdv5fSmmtrFjXYJu73+jVh2vmOZ2J3
b2/vP5DufGQVMh+7DFR58lsl3kbsqLP1gwUjQ62JDaJJjWjqIEri3UQpoWvGudY8XGci1+qXhsiv
e3stlVJk8lYcN+u+sNPQntW09x3aVf5lwmb73HWRORrVXIGF0HXx8lVzeTBqL8fmEpxQlzwEh/ul
tzNiu3sLVsjwRugM3NT3L0V5i6KFJVfr11VW7AZSpoLne71f+72VyEXJU3RWWKXAfYC+iQZgIqiS
NOotRuDmpdQylLBwCuHJi4SWjaeDMSxbJRpuR0/8gQ0lv0mTAPcMDgYIqHKOKaB3luTVPVtLpQE1
j7LJbBAJNhnMB9OJN5t6xa1gO2N2eb5kV5VgF6FmkwM2erXY34f/2MnpFZuMxvvs/nAOIQyIi3UB
aPcBwRjp/C5ykKeHCEfm6bVUNV0A0E1KN01sK1SO0eJxpdd4Z7l1gH1HfZPBGLXCAS5LhWY5vZXp
pYw1apx09wsqbww8AEDkPEgFsKXLSvR7kSiASdwGzxRseu0CMk7JpqVcG9hykUqOAl5eHb+/+rAE
wJ0IVKKR27XWxWI4vLu7GwjgB1EP9A3KmYWrg/n1ZZIVqVjKUht/sEI+8rAr7Ggw7UqLfgfeFmtw
rqRSB/Ou2JPni028+H6lkxTkdljq3i3Bbm/zVhvLi8urjxfvz167+rCh8/Pb5WUqtXIkbkCunCOQ
c9aVM/lJqnXF//H6xeRrMPq+w8QXbKrAqBCB6yoYhDIbJp8IxzoaNihAzNNQ5jLbHC/fOoI6wG2T
vuqKKnMRwP8dQUcUQlhDze9J83tMv6f2fmrvZ/Z+BvfP1I9lw/eF4Rx48f2OFE+w+HuhNC+hhDma
aGH9Th40sjmK+BHWk29DTe5YffR8q5eGeAZyuXx8ndkdxoZLSv/nEIbe0qSwoS6FGGYc6/KwJQLa
+CjLNDqNEn1cakchHXBXJyDpdSA0v4Yacb0zmh12NbQ8PefFuYyiLQ19g4IKkfEiI5S+f4ecCeAM
RPD9LT7/zPyPac1hdniZQUPp/ffJozrr0AG1XSar/FJzXbmJwwG6KpvaUHGUdF9sQl1lL6WgljAm
QoeJJ4TDO/mzTCJHCgtwJIAM3+G+TMpEw7+XYr/G5/uGtu+f44MnsX+aFXpD1nETWwt84LtdQ/A0
qdLNiyVwgw7yEzJAnrotyxPDmafiE8+jUgLCYdvOecUjvvn23evTn4eOzKgW6HtznfBULU9dxbjg
7VS3VcbPxArlu4jPT5an7Erw7MXU5LLh+2egGRpxvjZ6DYeGwWFHtLbi/SSDhxUPgdsVb/b/ouJ9
kkFT8YwUT4kRs/6M59FDXRD0GeX/i/Z324uvkDAFfhoRLXNPkJE8fwlTiggf1LEavNWkPyUXNCZ/
gaRA+aAwvPwPpIWO6KChkzUH9mJgT5SOhjrg7ZSwNce84elNUt6ojo7mz9dMbPH5fghcRJYL39/i
6QnmX8qiKo5TUXY6eRfaFW36lAHtG2zuUH6qqR+fzc55brK6K5cD3I7cydN8+htdOQMGyJ3V19Tq
k0ppmT2wUgfcNdP8LzaTSxrcrsvIs+y1vF0+MFcLc6Qbu5K9VB/Is0qkn9Zj329oorGeaiAzOPxY
8TLqRFEL3U6hWwnivB79RfnT8t2LuV0XLQjX4ehr24YutqGDbEgWFDwUcZVeFvwud9XQgTuKmAxm
3cbp9X91JHfbgWcqAFCC1C4DXxN357Sjk0AspBtt+3/xqZWl+jW175EIMyc99gS6O351HrixNph0
JHtdaXnzcsOXS7Y+iXLYeHqHdrmWxcMOjaDbef7gf69DU8BP06FZ5p6SXJoXJE5MOS9NtjqPrUJm
Xsh05Zs+32j2BQ8EVc2Bc/nVbRnttC1Yi8U5dkvKQnbOV7YePGMY+ausyw1L7blaw+ITbYzN25aJ
CbTVgG13348Z+Eu5xvGfBxJCs0qvwxS0wL1/Y3jkq736ZrMTks/44gBf4QmoL7UX0hH9AHr/AnqL
BLNWb2fZ3LETmcfJiuErSr/08503ZcJ+4jkbs8loMZkvxiP24eoEX23M8XkmdXT0I7T6+TuugS47
P2HmLQA+NcQ8NNrR+NV4OqEtIpPlxkuTLNFHk9Hs8Byhd2uQDYBKH8k4RgjPc1nlIU4U9EaMh+tE
3Ap6dVWvUZjFPTvIgIaPDokCv7ebFBAgXGkq77w4TVZr3d3L8ySDQf1I5i0sk0ENWHFkNxJHhCaW
JfDTwCyiNZTrUJbNfXFb2N1REsdJWKV6Y/abV1xalp4SWif5Sh0hOAWxUg+d9OhMBsGmhSkhImcJ
voI+enN2fIUg44reb5UoN5aeBZUQLhaCl4OCKwUtcnT0Pf2AOqDoeIrfinqViKDdhOEt5Cmwy0mV
5hG+mmqGu8EmS9FfGFZNFpKrVCUtJ49hoCDmHPmeL8GD2NVaKMFqiRkHL9FrwYCegguuWYim1iwQ
LMnDtIpEBBfsgacirkuZwc4YEWzjVDwWfSbhSakQJQtKwW/YRlalxcWSmIHhkjghCmCzEtwGhghA
/E7cNeiGMP5xsJpidzL/u2a8KAQvGWotA2FBSekGX+fjG1Uj991a5KwqViWPAMHAz9H3DbKFn7Od
qzWEiJcCCLhIeb6qoCAzfDdPKrNxohK4TyXgT34npeLWk7UIrRTdjcBAnQhEPrhLbpJCRAkfyHI1
xLvhGQTTtYyv315eXM+nr7zJNe4DNTaIFsyHjLbye0jo41qg7vA7BgWJi+E3DYrebIOZSp4r8AvQ
Gz0mbRKnwAdcCU0mjcRtEgq25nmUkpEzQGyCpiUJk7YSAFfrSkcSw830J8iMX41G/CA1v2YmkTD7
UgIYQVqgcogzozZ0Bvxi429GgmOMcoY5BNfagwh2m3D2TwwSWELBUh9RLBgmcdwIncMd4+jQSgLj
liFjVW4RsUqBv0LCB58hRUAxg5VQNCJUafvAA54DqUSL/pTCssYDymGYLhh4NjgPshpsmHU5WG6D
uHnaamznYwI2kTl4H48i1ItxUmQT3PIG2OEKkjCmSNRTIFAfoCjxW8XpA5VVcgtrb3laCbZrSUIu
3wPkhh4kD4Hp2gPD49cUC3iKlN9V9F0LRN6x2uThFVc3EBzlDcTaAJ9/UKARtEktJK5al1C2K/Ae
WK36jKZ0ZnMgeHcf1JCB1hRWYlILlDiEZVUOQYZLCPcleRfIA3FYynvI11qACkAcioq8YQ21ath5
G2Mw0yc5ELR9lui/4xc6Je2KBFYLctitvWwXJAA7swlqhGTwrJQLwoSBbeoXhfWPqQxAsVjtmQEz
KmuYvjKx4sFGA0Ps0rAyIuKJQvOapAAy3SXEGCmbYZGy5dGCFOklTsBdIKNBEcgJVQzppKZozA/C
VOS0KwlySIwb1BnQWRGTpt6iOWeHPiUWyuEaEhOP/o9LgP3Sn/OPJfib+IfyVxALNrc1LFlsikFg
YR0VUc0Q0nzIFbSAiaT6hRGpkGBIGdxy10TdGEhBwonQ02iFB1EhTLxR3pc5pDGIU1Ad5oh/p1mj
UWifUioJGPFmmU8VGnFADLbxbJISUrjARIIlkZYPHi5GsW3DCyosRIiVU5FakFejY7O3EQA0KQrV
ijkdWTnV3qMMWamnRuoVLwNwAS+UaWo6OoyzR7VKHoWs2D3M7oEIznheUY12uYD+pQJf2OvXmWHL
Gaw3mOwax3WGyFovG7ALUyDpDjxiLas0ahhJII/c5axlHV2XFcQ5CDgfjYyMbOcNBcODDEm+YnY3
QsWlzOpEi3vtc8/NTY5NQQhrum1XeMR/nH3YMYfrKr9RRt9n5PWYFgmInOE8gtIw01n3KUJL6FiU
WeRh04DNT4sLUdVmtoHyam75fC3Ntm3zYSnA1spsczEYKnbZC8hM5Qg6XvBdI7X1hZoQPmhq+J+i
8vNcaLRF0+uBa6SmHgZcw9yC7QjHthjKIPiTzUoUgKaTtU9NMgpEUxkp3ey46at+goFfbjTi7jNv
7DgzVkAi6+maFUgr+3OTVdqKSzMFlrvIpDtrQLMXgJanAfsHjE2g3iNonsFxT5Yf+rAXOAgg/9wl
kV6bxE3x3aD3CP2CHdj2oG0cFCnGWTpgxxHE05qn8RCmAtPLRAL8zBICksb/ZO4GZFOjHVxOt3R6
j8GHzRBP+yawkfDHJIe2E8QCtxHk2ljxPyzzZd0vtE0+tkK46Q5yvY8dfl549tbtzGDSw69SF7b1
+IGNseWwlQV7S3pc95WK8tha1P2mb02xYOO2W1RsqOjTiT4brkKjWshrkWrdrh4RO3OGqDtJZBsE
MRMWLbXehdKSvUPQoSYHs1s8s2XBshC/nDXzB8hDZx3I7S2+jjA5iXfwQ+LECU475EGX+iE3FKJk
uZ13F1enC0ZJF/4LKxjGchjGCBGdW6LliD1LuWGvsfBxx1ghzB2QSKys5ERUkYATdBqNjjMZ2QqC
mcwUJvQinIcRbquRDfouuK31NiRNJQy4Eg6x3THEySNU+mwCD8aPPRA6HOxRzCrhckHecIWYcRSz
BxpMQF4y9LDyG0vS0NtOw5gHaBTC/gmzAU/v+EYZ3BaP47ud9E1udJzJKnfzv7JdW80Eso/YcG6A
1IyXlt/Ht/ISoJHh3eDoFh1QzOjR3eRduTBzZyAMtkDEmIjosAYTFpqhwWqOcJzMZxLfJb+Fmovt
XYLjtcAZrNjYowRbipp+hvJETO+u66xos1hcpbRMKnBVDyM0CU0loTmsxPld44TaqOqTxHHIxIbi
dmBFp8b60si/ZQxUaG2Mc37P+LZeYBAKqTy0/tCxxT7ufM+jpFLOLmsGbpmjGDU7rdvheuhVMCPh
UZlXFRG4YssfC1PBDQ06q2uTkeG7He5q1gcPebfZ744nNKfDTF4Ja167n6Ke4J4CWy3Y4bOwFbKo
UovNXmNh2kLs5xSSHigPmTYHgh65EQg+I8fMIFNrPKGx0LHNDniGtmCmtastih+0VwW0OqbfM/5I
ucO0GRYXYDnAXZYgIkWjgSBIqAESjGdBAo5vltjjOzOnL0wuwiMF/KieGaipsNZHjPPaPr7JbejW
Hp4HdSFNNelAi3WR5LFs3QA/i18YkgPneBDaIOIvl/kmwyafAkSBflXDKE4t9jFrHxPD4Guc8dUK
io89IGiOXrBDxD8tuHlcGsMPolOP8YP6Mq5MJt7eDT5hni6MAcrcs6W57f8IKgvn0OgEjxjpzEuk
ssBi1Wf4MSoeuAAnthGDviSGPlmAsqE85VjlnR22wFZoJAhL5wmzbyicRqKCrlNpU+bqtGeRoqHM
45qM2tINvr18RDNpAkXHGOf0nmPVNTfYtQB+y8Si5oYegc/juLxgv+ClB6WmT/Pzr4jR5MK6GXHP
aEmIemgwk1t9HE4j2WNHvjThUi1T1Deg2Bm0Ewkwagu9wzpRJQboiuHpOUbwjO4aaguGR+iLg/70
kX8TOvIW91rkKDC9ITyBauP+6Qa6insPaX/VW1Bs9HtFiIvtjfotTbSYmj8v8cxfsvxu/t7EfLEX
hNC/rJv1eKCaR7xsAeavzuq7qkybmzhJ8dNvRD02H5DFumierqL2MmvBa4hY8/kprP+k7Bsw89Vg
Fpjj3mYxtIGbQrfCaI68Ra7ol8sz4gBfkRYh9G/t5g0IT3/iYq/Y/gA5RS0wD18gTUb7oylcfvcW
5+NwfngYzIMgnI6i6ZzHUx5OZ3EUzYKDYD84ODyIxT78sO+A0nKNKmo+MiqkSu5bA9j53C6gP4B5
L2I7XAKU6Ik4PgyicL4fjALB48N4xiMxj0fz+HB2KObRbBrF0eFkTvTUOpOtDhWFkepKmhhDwGIt
b0QOxaVsIB8Fv4E0YBRFHxJtOL1Iqb9r+z0pzN1ksN/7/Plfs+0XDA==
===END CRASH DUMP===

**Comment by SavionLegendZzz** [comment]
update to the latest version please :+1:

**Comment by GreenNature-MC-Server** [comment]
Is this fixed in 1.2.2?

**Comment by SavionLegendZzz** [comment]
Yes

**Comment by GreenNature-MC-Server** [comment]
Ok thanks! I did it! I hope thats the server will not crash so often longer! xD
