### ISSUE TITLE
My server is crashing often (20+ times per day) and the crash logs are always the same! How i can fix it? :( | Installing the newest version not helped

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [PurePlugins/PurePerms#162]
Here again a crash log xD Sry:

PocketMine-MP Crash Dump Sat Jan 2 20:28:59 UTC 2016

Error: Call to a member function toString() on null
File: /PurePerms_v1.1.12-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms
Line: 661
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[652]     }
[653] 
[654]     /**
[655]      * @param Player $player
[656]      */
[657]     public function unregisterPlayer(Player $player)
[658]     {
[659]         $this->getLogger()->debug($this->getMessage("logger_messages.unregisterPlayer", $player->getName()));
[660] 
[661]         $uniqueId = $player->getUniqueId()->toString();
[662] 
[663]         if(isset($this->attachments[$uniqueId])) $player->removeAttachment($this->attachments[$uniqueId]);
[664] 
[665]         unset($this->attachments[$uniqueId]);
[666]     }
[667] }
[668] 
[669] 
[670] 
[671] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux host13.adm24.de 2.6.32-43-pve #1 SMP Tue Oct 27 09:55:55 CET 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
mcg76_SimplePortal 2.0.3 by minecraftgenius76 for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
RestartMe 1.1.0 by Gamecrafter for API(s) 1.10.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
WorldProtect 2.1.0 by aliuly for API(s) 1.10.0, 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PvPWorlds 1 by  for API(s) 1.0.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVOw1T3La2f0V36cyFznq/Wci+ofMYQnrTgWRvIM2bV3cY2ZZ3HWzLtWRg28l/v+ccyba87G1I
Qt8HaQfrSDrfX5LNHz2dZKK3GM8Ox0fz+eH0Rb8nylKWvcUfPb0pYKp3fnP+7t3bd71+LxNK8RXC
zniaMi0ZZ5nIAlGyuMpDncgcgFe6TPLV/gGDUV6lKWyMkxR3DZdVKZaizNTN3XgA/ybe8hKe5pG4
GxRrXg5VGQ5v5rNXr0ajdnH7BKjSJAdU8/n4U79XpNUqyXsLXVai3wtlJJDt+eEEaDH4+QTrQSYY
0cPMgofff0/jQztm37P/LHjJM7ZM+QaE+a6g37Ro3iwa0vjIjosqSJOwlbvKS7FKlBalQbLfxXVA
m4/t5j9o9KJGDT/f6XWivB9WQl/I1Qq2H3g/RCKoVvvtzKVR/77fS2nNjbWHGmwT93v9mjDtfMMz
sX9wcPAfSHc+sgqZj10Gqjz5rRKvI3bS2fregpGh1rYG0aRGNHUQJfF+opTQNeNcax6uM5Fr9UtD
5NeDg5ZKKTJ5J06bdZ/ZaWjPatqHDu0q/zxhs33uusgcjWqewELos/j4onk8GrWPY/MI3qdLHoLD
/dLbG7H9gwUrZHgrdAb+6ftXorxD0cKSq/XLKiv2AylTwfOD3q/93krkouQpOiusUuA+QN+EATAR
VEka9RYj8O9SahlKWDg97vd4kdCy8XQwhmWrRMNw9MQf2FDy2zQJcM/gaICAKucY+72LJK8e2Foq
Dah5lE1mg0iwyWA+mE682dQr7gTbG7OryyW7rgR7G2o2OWKjF4vDQ/iPnZ1fs8lofMgejucQu4C4
WBeA9hAQjJHO7yIHeXqIcGRmb6Sq6QKABikNmqBWqByjxdNKr3FkuXWAfUd9k8EYtcIBLkuFZjm/
k+mVjDVqnHT3CypvDDwAQOQ8SEVU545IFMAkboM5BZteuoCMY5ZxKNcGtlykkqOAV9en767fLwFw
LwKVaOR2rXWxGA7v7+8HAvhB1AN9i3Jm4epofnOVZEUqlrLUxh+skDsmu8KOBtOutOh34G2xBudK
KnU074o9+XqxiRffr3SSgtwOS93REuz2Om+1sXx7df3h7buLl64+bOj8/Hp5lUqtHIkbkCvnCOSc
deVMfpJqXfF/vHw2+RqMvu8w8RmbKjAqROC6CgahzIbJR8KxjoYNChDzPJS5zDany9eOoA5w26Qv
uqLKXATwf0fQEYUQFk/ze9L8HtPvqR1P7XhmxzMYf6V+LBu+LwznwIvvd6R4gsXfCaV5CSXM0UQL
63fyoJHNUcSPsJ58G2pyx+qjr7d6aYhnIJfLx5eZ3WFsuKT0fwlh6C1NChvqUohhxrEuD1sioI0P
skyj8yjRp6V2FNIBd3UCkt4EQvMbqBE3e6PZcVdDy/NLXlzKKNrS0DcoqBAZLzJC6fv3yJkAzkAE
39/i88/Mv0trDrPDqww6Se+/z3bqrEMH1HaVrPIrzXXlJg4H6KpsakPFUdJDsQl1lT2XglrCmAgd
Jp4QDm/kzzKJHCkswJEAMnyH+zIpEw3/nov9Gp/vG9q+f4kTT2L/PCv0hqzjJrYW+Mh3u4bgaVKl
m2dL4AYd5CdkgDx1W5YnhjNPxUeeR6UEhMO2nfOKHb75+s3L85+Hjsxtvv9JBo/zPQK38/3s/0W+
/yiDJt8bKZ7iIWb9Bc+jx7og6FcUv886iVtcv0DCFPhpRLTMPUFGsvsSenQRPsriNXirRX1KJDQm
f4aQoGgoDC//A0HRER00dLbmwF4M7InS0VAHvF37t7r4Vzy9Tcpb1dHR/Os1E1t8vh8CF5Hlwve3
eHqC+ZeyqIrTVJSdPtaFdkWbPuV48g02dyg/1dS7TyaXPDc5zZXLAW5H7uRpPv2NrpwBA+TO6ksq
1VmltMweWakD7ppp/hebySUNbtdl5Kvsda6UyHXCU7U8d5OtC96Osi1nvBArZPRtfHm2PGfXgmfP
Jq/Lhu9fgICfDbBdachwaBgcdkTDULxbPnLYFubIPnalfq4+kGeVSD+ux77f0ER3faqLtrebDvPO
jadruMl2sJm70mczlr17BUlqBpzHLy4dtNOWiRYLpU4sIz9WvIw6qbOFbtfNrapwWd92iPKn5Ztn
yzVdtCB6h6MvddkutqGDbEhKEDwUcZVeFfw+d9XQgTuKmAxm3aB9+V8dyd0e8CsVAChBapeBL0m2
l7SjUzUspOvFh3/xRZ2l+iUNz460ai637KV798TZmXDTy2DSkexlpeXt8503XbL15ZvDxtPb8qu1
LB635QTdLu5H/3ttuQJ+mrbcMvd0GU+TspCd65Wtia84jf1VknLDUnut1rD4xPqB3etW+SDQVge6
XfZ3VY/PxZ1Tmx5JCN06vQ1TcAbo/Zuqgny1T99cUwjJJ3xvgG/wBOTaOozohn4Ah58CmqsEI7i3
t2xG7EzmcbJi+GrSL/1874pr9hPP2YSN6c3G+Ji9vz7DNxtznM+kjk5+hLNO/oZroMsuz5h5CYCz
hpiHRjsZvxhPJ7RFZLLceGmSJfpkMpodXyL0fg2yAVDpExnHCOF5Lqs8xCMVvRDj4ToRd4LeXNVr
FGY0z57kQMMnx0SBP9hNCggQrjSV916cJqu17u7leZJBw3Qi8xaWyaAGrDiyG4kTQhPLEvhpYBbR
GkpXKMtmXNwVdneUxHESVqnemP3mDZeWpaeE1km+UicITkGs1EMnPbmQQbBpYUqIyFmCr55PXl2c
XiPIuKL3WyXKjaVnQSWEi4Xg46DgSsEZITr5nn5AHZCAPcXvRL1KRNBvw+k15Cmwy0mVZgrfTDWn
28EmS9FfGFYQFpKrVCUtJ49hoCDm3PheLsGD2PVaKMFqiRkHL9FrwYCeggfwrxBNrVkgWJKHaRWJ
CB7YI09FXFcyg50xItjGqXgs+kzCTKkQJQtKwW/ZRlalxcWSmIHhkjghCmCzEtwGTlGA+I24b9AN
4fzLwWqK3cv875rxohC8ZKi1DIQFJaUbfI2PL1SN3PdrkbOqWJU8AgQDP0ffN8gWfs72rtcQIl4K
IOAi5fmqguLE8NU8qczGiUpgnErAn/xOSsWtZ2sRWim6G4GBOhGIfHCf3CaFiBI+kOVqiKPhBQTT
jYxvXl+9vZlPX3iTG9wHamwQLZgPGW3l95DQh7VA3eH3C3CMiBh+y6DoxTaYqeS5Ar8AvdE0aZM4
BT7gSWgyaSTuklCwNc+jlIycAWITNC3JGMJNAFytKx1JDDdTq5EZvxqN+FFqfs1MImH2nQQwgrRA
5RBnRm3oDPilxt+MBKcY5QxzCK61NzHsLuHsnxgksISCpb6jWTBM4rgRqug94+jQSgLjliFjVW4R
sUqBv0LCB58hRUAxg5VQNCJUaTvhAc+BVKJFf05hWeMB5TBMFww8G5wHWQ02zLocLLdB3My2Gtv7
kIBNZA7ex6MI9WKcFNkEt7wFdriCJIwpEvUUCNQHKEr8VnH6MGWV3MHaO55Wgu1bkpDLDwC5oQfJ
Q2C69sDw+DHFAmaR8puKvmeByDtVmzy85uoWgqO8hVgb4Px7BRpBm9RC4qp1CWW7Au+B1arP6JqC
2RwI3t0HNWSgNYWVmNQCJQ5hWZVDkOESwn1F3gXyQByW8gHytRagAhCHoiJvWEOtGnZexxjM9CkO
BG2fJfrv+GVOSbsigdWCHHZrL9sHCcDObIIaIRk8K+WCMGFgm/pFYf1jKgNQLFZ7ZsCMyhqmr0ys
eLDRwBC7MqyMiHii0LwmKYBM9wkxRspmWKRsebQgRXqJE3AXyGhQBHJCFUM6qSka84MwFTntSoIc
EuMGdQZ0VsSkqbdoztmxT4mFcriGxMSj/+MSYL/05/xjCf4m/qH8FcSCzW0NSxabYhBYWEdFVDOE
NB9zBS1gIql+YUQqJBhSBrfcNVE3BlKQcCL0NFrhQVQIE2+U92UOaQziFFSHOeLfadZoFNqnlEoC
RrxZ5lOFRhwQg208m6SEFN5iIsGSSMsHjxej2LbhBRUWIsTKqUgtyKvRsdnbCACaFIVqxZyOrJzq
YCdDVuqpkXrFywBcwAtlmpqODuNsp1bJo5AVu4fZPRDBGc8rqtEuF9C/VOALB/06M2w5g/UGk13j
uM4QWetlA/bWFEgagUesZZVGDSMJ5JH7nLWso+uygjgHAeejkZGR7b2iYHiUIclXzO5GqLiUWZ1o
ca+d99zc5NgUhLCm23aFHf7j7MOOOVxX+a0y+r4gr8e0SEDkDM8jKA0znXWfIrSEjkWZRR42Ddj8
tLgQVW1mGygv5pbPl9Js2zYflgJsrcw2F4OhYpc9g8xUjqDjBd81UltfqAnhRFPD/xSVn+dCoy2a
Xg9cIzX1MOAazi3YjnBsi6EMgj/ZrEQBaDpZO2uSUSCaykjpZs9NX/UMBn650Yi7z7yx48xYAYms
p2tWIK0czk1WaSsunSmw3EUm3VkDmr0AtDwN2D/g2ATqPYHmGRz3bPm+D3uBgwDyz30S6bVJ3BTf
DXqP0C/YkW0P2sZBkWKcpQN2GkE8rXkaD+FUYHqZSICfWUJA0vifzN2AbGq0g8vpls4fMPiwGeJp
3wQ2Ev6Q5NB2gljgNoJcGyv++2W+rPuFtsnHVgg33UOu97HDzwvPDt3ODE56+FHqwrYeP7Axthy2
smBvSdN1X6koj61F3W/61hQLNm67RcWGir6c6LPhKjSqhbwWqdbt6iNi55wh6k4S2QZBzAmLllrv
QmnJ3iHoUJOD2S2e2bJgWYgfzprzB8hDdx3I7R2+jzE5iXfwQ+LEE5x2yIMu9WNuKETJcntv3l6f
LxglXfgvrOAwlsNhjBDRHR5ajtizlBv2GgufdowVwrkDEomVlZyIKhJwgk6j0XEmI1tBMJOZwoRe
hOdhhNtqZIO+C25rvQ1JUwkDroRDbH8McbKDSp9NYGK8a0LocHBAMauEywV5wzVixqOYvdBgAvKS
oYeV31iSDr3taRjzAB2FsH/CbMDTe75RBrfF4/huJ32TG51mssrd/K9s11YzgewjNjw3QGrGR8vv
7q28BGhkeDc4ukUHFDPauZu8Kxfm3BkIgy0QMSYiuqzBhIVmaLCaKxwn85nEd8XvoOZie5fg8Vrg
GazY2KsEW4qafobyREwv7+usaLNYXKW0TCpwVQ8jNAlNJaFzWInnd40n1EZVHyUeh0xsKG4PrOjU
WF8a+beMgQqtjXHJHxjf1gschEIqD60/dGxxiDvf8SiplLPLmoFb5ihGzU7rdrgeehXMSHhV5lVF
BK7Y8sfCVHBDg+7q2mRk+G4PdzXrg8e82+x3zxM6p8OZvBLWvHY/RT3BPQW2WrDjr8JWyKJKLTb7
jIVpC7GfU0h6oDxk2lwIeuRGIPiMHDODTK3xhsZCxzY74B3agpnWrrYofs9eFdDqmH7P+CPlDtNm
WFyA5Qh3WYKIFI0GgiChBkgwngUJOL5ZYq/vzDl9YXIRXingN/XMQE2FtT5inNf28U1uQ7f28D6o
C2mqSQdarIskj2XrBvhV/MKQHDjXg9AGEX+5zDcZNvkUIAr0qxpG8dRip1k7TQyDr3HGVysoPvaC
oLl6wQ4R/7Lgdrc0hh9Ep3bxg/oyrkwm3t4NPmFmF8YAZe7Z0tz2fwSVhXNpdIZXjHTnJVJZYLHq
M/wWFS9cgBPbiEFfEkOfLEDZUJ5yrPLODltgKzQShKUzw+wbCqeRqKDrVNqUuTrtWaRoKDNdk1Fb
usE3eTs0kyZQdIxxzh84Vl0zwK4F8FsmFjU3NAU+j8flBfsFHz0oNX06P/+KGE0urJsR946WhKgP
DebkVl+H05Fs15UvnXCplinqG1DsDNqJBBi1hd5hnagSA/TE8PYcI3hGo4baguEV+uKoP93xb0JX
3uJBixwFphecZ1Bt3L/cQFdxx5D2V70FxUa/V4S42A7Ub2mixdT8dYln/pDld/PnJuaTxSCE/mXd
rMcL1TziZQswf21Wj6oybQZxkuKX34h6bL6gi3XRzK6i9jFrwWuIWPP1Kaz/qJrvJ/AVeRaY695m
MbSBm0K3wmiOvEWu6FfLC+IAv78oQujf2s0bEJ7+wsU+scMBcopaYB6+QJqMDkdTePzuNZ6Pw/nx
cTAPgnA6iqZzHk95OJ3FUTQLjoLD4Oj4KBaH8MO+A0rLNaqo+cqqkCp5aA1gz+d2Af39yzsR28Ml
QImeiOPjIArnh8EoEDw+jmc8EvN4NI+PZ8diHs2mURwdT+ZET60z2epQURiprqSJMQQs1vJW5FBc
ygbyQfBbSANGUfQl1YbTi5T6w77fk8KMJoPD3qdP/wLO1BTS
===END CRASH DUMP===

**Comment by 64FF00** [comment]
@GreenNature-MC-Server **UPDATE YOUR PP TO THE LATEST VERSION**

**Comment by GreenNature-MC-Server** [comment]
It's the latest version...

**Comment by GreenNature-MC-Server** [comment]
Read the title...
"Installing the newest version not worked"

**Comment by 64FF00** [comment]
@GreenNature-MC-Server Please try downloading the file again if it does not work

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/releases

**Comment by GreenNature-MC-Server** [comment]
I find a liitle mistake!
In the crash log is "File: /PurePerms_v1.2.2-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms" at the 4th line but in the plugin list is "PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0"
I have the newest version but the crash log don't say that in the 1st lines but in the plugin list!

**Comment by GreenNature-MC-Server** [comment]
Please read my latest comment @64FF00 
That's the newest version!

**Comment by 64FF00** [comment]
@GreenNature-MC-Server Please re-open this issue if the problem still persists in the latest version

**Comment by 64FF00** [comment]
@GreenNature-MC-Server https://github.com/PurePlugins/PurePerms/archive/master.zip
