### ISSUE TITLE
 INFO Fatal error: Call to a member function toString() on null in 

### ISSUE THREAD

**Issue by RocoWayne** [PurePlugins/PurePerms#168]
25.01 09:57:21 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
25.01 09:57:21 [Server] INFO Fatal error: Call to a member function toString() on null in phar:///plugins/PurePerms_v1.1.12-PMv1.6dev.phar/src/_64FF00/PurePerms/PurePerms.php on line 661

**Comment by 64FF00** [comment]
@RocoWayne Please update PurePerms to the latest version

**Comment by RocoWayne** [comment]
i just install the last version,  i let you know!

**Comment by RocoWayne** [comment]
Still crash the server!
