### ISSUE TITLE
Not Updated For Me plz read!

### ISSUE THREAD

**Issue by blah123454321** [PurePlugins/PurePerms#169]
For some reason when I install this plugin on my pc it says that this plugins is outdated and can not be installed to your server. I have a Windows 8 computer with pocketmine version 1.4.1. If someone can tell me how to fix it that would be great because it says the same thing for plugins like PurePerms, PureChat and some others to.

**Comment by blah123454321** [comment]
Sexy for the no description but For some reason when I install this plugin on my pc it says that this plugins is outdated and can not be installed to your server. I have a Windows 8 computer with pocketmine version 1.4.1. If someone can tell me how to fix it that would be great because it says the same thing for plugins like PurePerms, PureChat and some others to.

**Comment by 64FF00** [comment]
Please update your PocketMine-MP to the latest version

**Comment by blah123454321** [comment]
How do I update to the latest version if the Verizon on pocketmine.net is the version that I have?
