### ISSUE TITLE
How do I get the latest version?

### ISSUE THREAD

**Issue by blah123454321** [PurePlugins/PurePerms#170]
How do I get the latest version if I have the version 1.4.1 right off of pocketmine.net?

**Comment by 64FF00** [comment]
@blah123454321 Woops sorry, I mean the latest **development** version. You can download it at http://cdn.pocketmine.net/api/update-development.phar

**Comment by blah123454321** [comment]
Ok and this version will let me download all plugins?

**Comment by blah123454321** [comment]
And thx a for the info

**Comment by 64FF00** [comment]
@blah123454321 I think so.

**Comment by 64FF00** [comment]
@blah123454321 Don't forget to change the name of the phar to PocketMine-MP.phar

**Comment by blah123454321** [comment]
Ok so I replace the original pocketmine mp file with the new one?

**Comment by 64FF00** [comment]
@blah123454321 Yup.

**Comment by blah123454321** [comment]
Ok and what's the file that I'm replacing

**Comment by blah123454321** [comment]
The exact name?

**Comment by 64FF00** [comment]
@blah123454321 update-development.phar -> PocketMine-MP.phar

**Comment by blah123454321** [comment]
Ok and it's a file that I just delete and replace correct

**Comment by 64FF00** [comment]
@blah123454321 :+1:

**Comment by blah123454321** [comment]
Ok thx

**Comment by blah123454321** [comment]
Do I have to rename it

**Comment by 64FF00** [comment]
@blah123454321 Yes

**Comment by blah123454321** [comment]
Ok thx closing now

**Comment by blah123454321** [comment]
When I go to the website on my pic it says the link seems to be broken what do I do now?

**Comment by blah123454321** [comment]
Pic= computer stupid autocorrect

**Comment by blah123454321** [comment]
Hello?

**Comment by 64FF00** [comment]
@blah123454321 It's not broken... Are you using Linux or Windows?

**Comment by blah123454321** [comment]
Windows

**Comment by blah123454321** [comment]
Windows 9 acctually

**Comment by 64FF00** [comment]
@blah123454321 What does it say if you go to the link that I gave you?

**Comment by blah123454321** [comment]
It says this link is invalid! did u mean pocketmine.net?
Thas what it says

**Comment by blah123454321** [comment]
What do u have to say now?

**Comment by PEMapModder** [comment]
I thought this repo is PurePerms not PocketMine?
