### ISSUE TITLE
Please make timer for groups

### ISSUE THREAD

**Issue by XiangZhao969** [PurePlugins/PurePerms#173]
Time still be counted while players are offline, not like timeranks

**Comment by isoz** [comment]
count time while they are offline? whats the point? So if a player would be offline for 1 month you would still give them everything?

**Comment by RocoWayne** [comment]
I dont understand the issue

**Comment by XiangZhao969** [comment]
Example: players can be in group VIP in 7 days, after 7 days, they will be set back to Member group

**Comment by RocoWayne** [comment]
Ohhh, nos understand. Great idea, like permissionsex

**Comment by 64FF00** [comment]
@XiangZhao969 I'm really sorry but... I don't think I won't be able to do that. I don't actually have that much time to work on it.

**Comment by RocoWayne** [comment]
:(
