### ISSUE TITLE
Multi World Level Update

### ISSUE THREAD

**Issue by MichaelM04** [PurePlugins/PurePerms#176]
I've experimented for hours and finally figured it out when you set a multi world permission it won't take effect in the other world until you quit and rejoin in that world then it works! I think this may be caused by level change event not updating when you change worlds so the permissions aren't updating for that world as well.

I might be the only one with this issue is there a fix?

**Comment by kdani1** [comment]
I now tryed pp 1.3.6 and its happened...
I tp to another world and then where i came from world s permissions applied.
