### ISSUE TITLE
Php7Support?

### ISSUE THREAD

**Issue by MilkoIvanov** [PurePlugins/PurePerms#179]
Guys is the plugin getting Php7 support soon

**Comment by PEMapModder** [comment]
The plugin doesn't seem to use any backwards-incompatible features in PocketMine PHP 7 support.

**Comment by MilkoIvanov** [comment]
My fault,sorry guys.

**Comment by 64FF00** [comment]
yey thanks @PEMapModder

**Comment by MilkoIvanov** [comment]
@64FF00 Actually sometimes PurePerms seems loaded but the players still don't have permissions.And I don't see any Error.Sorry for that closing and opening...But there is some problem

**Comment by MilkoIvanov** [comment]
And I think the problem somehow is my groups settings 
[groups.txt](https://github.com/PurePlugins/PurePerms/files/114106/groups.txt)

**Comment by 64FF00** [comment]
@MilkoIvanov Are you using the 'multiworld-perms' mode?

**Comment by MilkoIvanov** [comment]
Mm no should I enable it?

**Comment by Lucario2** [comment]
Hey! Only I say "yey"

**Comment by 64FF00** [comment]
@MilkoIvanov Could you try changing the file name to groups.yml? (groups.txt -> groups.yml) I'm pretty sure it would work well.
