### ISSUE TITLE
PurePlugins Webpage [En/Ru]

### ISSUE THREAD

**Issue by 0-Eclipse-0** [PurePlugins/PurePerms#183]
EN
Here is a PurePlugins website I created as I saw that you tried to make one a while ago.

RU:
Вот сайт PurePlugins я создал, как я увидел, что вы пытались сделать один некоторое время назад .

Link/Ссылка:
https://github.com/0-Eclipse-0/PPlugins-Website [En/Ru]

**Comment by 64FF00** [comment]
@0-Eclipse-0 :+1:

**Comment by 64FF00** [comment]
@0-Eclipse-0 Is it still WIP?

**Comment by 0-Eclipse-0** [comment]
Yes.

**Comment by 64FF00** [comment]
@0-Eclipse-0 That's great - don't forget to tell me if it's finished :D

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/pureplugins.github.io

**Comment by 64FF00** [comment]
@0-Eclipse-0 I sent you an invitation to our team. Don't forget to accept it xD

**Comment by 0-Eclipse-0** [comment]
Joined

**Comment by Bamuel** [comment]
http://pureplugins.github.io/
