### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MrDoni98** [PurePlugins/PurePerms#188]
I introduced the command - /grpinfo
Object of class _64FF00\PurePerms\PPGroup could not be converted to string in phar:///root/cs/plugins/PurePerms_v1.3.0.phar/src/_64FF00/PurePerms/cmd/GrpInfo.php on line 100

[100]             $parents = TextFormat::DARK_GREEN . implode(",", $group->getParentGroups());

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/releases/download/v1.3.0/PurePerms_v1.3.0_01.phar
