### ISSUE TITLE
Can't set group, after setting get this error

### ISSUE THREAD

**Issue by Ecka149** [PurePlugins/PurePerms#19]
http://crash.pocketmine.net/view/302210

**Comment by Ecka149** [comment]
I can't find new release, (sorry new in github)

**Comment by Ecka149** [comment]
The problem was. I named Guest group as Newbie, but left the Guest in Admins, Mods, as an example of commands. My fault.

**Comment by 64FF00** [comment]
@Ecka149 :O

**Comment by Ecka149** [comment]
What? :D
