### ISSUE TITLE
Multi-World Perms Don't Work

### ISSUE THREAD

**Issue by Skyladd** [PurePlugins/PurePerms#195]
When I enable world perms and add any permission or edit the individual worlds i get this error

[Server thread/CRITICAL]: RuntimeException: "INVALID GROUPS.YML SETTINGS: Please check if you have an invalid or corrupted groups.yml." (EXCEPTION) in "/Pureperms.phar/src/_64FF00/PurePerms/provider/DefaultProvider" at line 41

I'm running linux 32 bit and no matter how i edit the multi world perms it breaks. I have a lot of experience with perms config files as well from bukkit.

**Comment by 64FF00** [comment]
@Skyladd Are you sure you don't have any tabs in your config file?

**Comment by Skyladd** [comment]
I dont have any at all i never use tabs in my config files. It could be linux specific? But i know i write it fine, the multi world doesnt give errors until you edit the worlds.

**Comment by 64FF00** [comment]
@Skyladd Could you try using http://www.yamllint.com and check if you can get any errors

**Comment by Skyladd** [comment]
---
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - -blocksniffer
  - -essentials.getpos.other
  - -essentials.kill
  - -pocketmine.command.kill
  - -pocketmine.command.plugins
  - -pocketmine.command.tell
  - -pocketmine.command.time.*
  - -pocketmine.command.version
  - -wp.cmd.info
  - essentials.afk
  - essentials.back
  - essentials.back.ondeath
  - essentials.delhome
  - essentials.getpos
  - essentials.home
  - essentials.seen
  - essentials.sethome
  - essentials.sign
  - essentials.sign.color
  - essentials.sign.use.warp
  - essentials.spawn
  - essentials.suicide
  - essentials.tpa
  - essentials.tpaccept
  - essentials.tpahere
  - essentials.tpdeny
  - essentials.warps.*
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketguard.command.pg
  - pocketmine.command.list
  - pocketmine.command.me
  worlds:
    spawn:
      permissions: []
    survival:
      permissions: []
    creative:
      permissions: []
    nether:
      isDefault: false
      permissions: []
Admin:
  inheritance:     **Error Here, but i dont edit this part of the config**
  - Guest
  permissions:
  - blocksniffer
  - essentials.gamemode
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.time
  - wp.cmd.gm.exempt
  - wp.cmd.info
  worlds:
    spawn:
      permissions:
  - wp.cmd.info
    survival:
      permissions: []
    creative:
      permissions: []
    nether:
      isDefault: false
      permissions: []
Owner:
  inheritance:
  - Guest
  - Admin
  permissions:
  - essentials
  - pocketmine.command
  - pperms.command
  worlds:
    spawn:
      permissions: []
    survival:
      permissions: []
    creative:
      permissions: []
    nether:
      isDefault: false
      permissions: []
OP:
  inheritance: []
  permissions:
  - '*'
  worlds:
    spawn:
      permissions: []
    survival:
      permissions: []
    creative:
      permissions: []
    nether:
      isDefault: false
      permissions: []
...

**Comment by Skyladd** [comment]
![screenshot-yamllint - the yaml validator - google chrome](https://cloud.githubusercontent.com/assets/16869214/13260723/002245ee-da1a-11e5-9d53-75d541b1ae2f.png)

**Comment by 64FF00** [comment]
@Skyladd 
```yaml
---
Admin:
  inheritance:
  - Guest
  permissions:
  - blocksniffer
  - essentials.gamemode
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.time
  - wp.cmd.gm.exempt
  - wp.cmd.info
  worlds:
    spawn:
      permissions:
      - wp.cmd.info # Your problem here
    survival:
      permissions: []
    creative:
      permissions: []
    nether:
      isDefault: false
      permissions: []
...
