### ISSUE TITLE
Bug in v1.3.0_01(multiworld support)

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#196]
[Server] [24:45:56] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PurePerms v1.3.0': Undefined index: IsDefault on _64FF00\PurePerms\PPListener
[Server] [26:47:58] [Server thread/NOTICE]: "ArrayOutOfBoundsException: "Undefined index: IsDefault" (E_NOTICE) in "/PurePerms v1.3.0_01.phar/src/_64FF00/PurePerms/PPGroup" at line 220

**Comment by 64FF00** [comment]
If you are using YAML Provider change '*I*sDefault' nodes to '*i*sDefault'

**Comment by SoyPro** [comment]
I dont know where i can found IsDefault pls help me

**Comment by 64FF00** [comment]
Could you post your groups.yml here

**Comment by SoyPro** [comment]
---
Guest:
  alias: gst
  isDefault: true
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -pocketmine.command.me
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinfo
  worlds:
    world:
      isDefault: true
      permissions: []
    +:
      permissions: []
      isDefault: true
    p:
      isDefault: false
      permissions: []
Admin:
  alias: adm
  inheritance:
  - Guest
  permissions:
  - essentials.gamemode
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.time
  worlds:
    world:
      isDefault: false
      permissions:
      - essentials.mute.use
      - essentials.tempban
      - gieffects.effect
      - pocketmine.command.ban
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.time
      - pocketmine.command.weather
    +:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.effect
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
    p:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.effect
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
Owner:
  alias: owr
  inheritance:
  - Admin
  permissions:
  - essentials
  - pocketmine.command
  - pperms.command
  worlds:
    world:
      isDefault: false
      permissions: []
    +:
      isDefault: false
      permissions: []
    p:
      isDefault: false
      permissions: []
OP:
  alias: op
  inheritance: []
  permissions:
  - '*'
  worlds:
    world:
      isDefault: false
      permissions: []
    +:
      isDefault: false
      permissions: []
    p:
      isDefault: false
      permissions: []
Dueño:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - essentials
      - gieffects.effect
      - pocketmine.command
      - pperms.command
    +:
      isDefault: false
      permissions:
      - essentials
      - pocketmine.command
      - pperms.command
    p:
      isDefault: false
      permissions:
      - essentials
      - pocketmine.command
      - pperms.command
SubDueño:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - essentials.mute.use
      - essentials.tempban
      - gieffects.effect
      - pocketmine.command.ban
      - pocketmine.command.banip
      - pocketmine.command.list
      - pocketmine.command.pardon
      - pocketmine.command.pardonip
      - pocketmine.command.say
      - pocketmine.command.time
      - pocketmine.command.weather
    +:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.antioch
      - essentials.back
      - essentials.break
      - essentials.broadcast
      - essentials.burn
      - essentials.clearinventory
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.jump
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tpall
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.banip
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.pardon
      - pocketmine.command.pardonip
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
    p:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.antioch
      - essentials.back
      - essentials.break
      - essentials.broadcast
      - essentials.burn
      - essentials.clearinventory
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.jump
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tpall
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.banip
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.pardon
      - pocketmine.command.pardonip
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
JefeAdmin:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - essentials.mute.use
      - essentials.tempban
      - gieffects.effect
      - pocketmine.command.ban
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.time
      - pocketmine.command.weather
    +:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials burn
      - essentials.antioch
      - essentials.back
      - essentials.break
      - essentials.broadcast
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.jump
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tpall
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
    p:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials burn
      - essentials.antioch
      - essentials.back
      - essentials.break
      - essentials.broadcast
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.jump
      - essentials.kill.use
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tpall
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.ban
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.pardon
      - pocketmine.command.say
      - pocketmine.command.status
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
Moderador:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - essentials.mute.use
      - essentials.tempban
      - gieffects.effect
      - pocketmine.command.list
      - pocketmine.command.time
      - pocketmine.command.weather
    +:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
    p:
      isDefault: false
      permissions:
      - economyapi.command.*
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.extingush
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning.use
      - essentials.more
      - essentials.mute.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.sudo
      - essentials.tempban
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - jail.command.jail
      - jail.command.unjail
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.effect
      - pocketmine.command.enchant
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.list
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
Constructor:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
      - pocketmine.command.kick
      - pocketmine.command.time
      - pocketmine.command.weather
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.essentials
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
      - pocketmine.command.weather
Ayudante:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
      - pocketmine.command.kick
      - pocketmine.command.time
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - essentials.world
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.give
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
Policia:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
      - pocketmine.command.kick
      - pocketmine.command.time
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.lightning
      - essentials.lightning.use
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.tphere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
      - pocketmine.command.kick
      - pocketmine.command.teleport
      - pocketmine.command.time
Vip:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
SuperVip:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
UltraVip:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
VipDios:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
VipGeneral:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
Publicista:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.gamemode
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
Dev:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - '*'
    +:
      isDefault: false
      permissions:
      - '*'
    p:
      isDefault: false
      permissions:
      - '*'
Usuario:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: true
      permissions:
      - gieffects.effect
    +:
      permissions:
      - advancedkits.kitname
      - essentials.sign.use
      - essentials.warps.*
      - essentials.tpa
      - essentials.tpaccept
      - essentials.tpahere
      - essentials.home
      - essentials.sethome
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: true
      permissions:
      - advancedkits.kitname
      - essentials.sign.use
      - essentials.warps.*
      - essentials.tpa
      - essentials.tpaccept
      - essentials.tpahere
      - essentials.home
      - essentials.sethome
      - pchat.colored.format
      - pchat.colored.nametag
Youtuber:
  alias: ""
  isDefault: false
  inheritance: []
  permissions: []
  worlds:
    world:
      isDefault: false
      permissions:
      - gieffects.effect
    +:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.lightning.use
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
    p:
      isDefault: false
      permissions:
      - essentials.back
      - essentials.break
      - essentials.condense
      - essentials.depth
      - essentials.fly
      - essentials.lightning.use
      - essentials.getpos
      - essentials.god
      - essentials.home
      - essentials.itemdb
      - essentials.near
      - essentials.realname
      - essentials.repair
      - essentials.seen
      - essentials.sethome
      - essentials.sign.use
      - essentials.tpa
      - essentials.tpahere
      - essentials.vanish
      - essentials.warps.*
      - pchat.colored.format
      - pchat.colored.nametag
...

**Comment by SoyPro** [comment]
_64FF00 but now the same happened but in line 200

**Comment by SoyPro** [comment]
Here the same happen:
[Server] [23:34:05] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PurePerms v1.3.2': Undefined index: IsDefault on _64FF00/PurePerms/PPListener
[Server] [24:06:10] [Server thread/NOTICE]: ArrayOutOfBoundsException "Undefined index: isDefault" (E_NOTICE) in "/PurePerms v1.3.2.phar/src/_64FF00/PurePerms/PPGroup" at line 213

**Comment by SoyPro** [comment]
[Server] [03:16:25] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\entity\EntityLevelChangeEvent' to 'PurePerms v1.3.2': Undefined index: IsDefault on _64FF00/PurePerms/PPListener
[Server] [24:06:10] [Server thread/NOTICE]: ArrayOutOfBoundsException "Undefined index: isDefault" (E_NOTICE) in "/PurePerms v1.3.2.phar/src/_64FF00/PurePerms/PPGroup" at line 213

**Comment by SoyPro** [comment]
Sorry line 213
