### ISSUE TITLE
Just a question but since your updating everything to php7 you know what I should change from php5 right? What should I change to fix non working plugins from php5 to php7?

### ISSUE THREAD

**Issue by Lucario2** [PurePlugins/PurePerms#197]

**Comment by Skyladd** [comment]
Nothing you can do. the plugin makers have to update their plugins to php7

**Comment by 64FF00** [comment]
Already supports php7

**Comment by Lucario2** [comment]
I was talking about other plugins like essentials PE and worldedit art but i already fixed that to support php7 servers

**Comment by Lucario2** [comment]
Lel

**Comment by Lucario2** [comment]
@64FF00 why did you leave kik?

**Comment by Lucario2** [comment]
I fixed all the non working plugins that don't support php7. I'm so proud of myself

**Comment by 64FF00** [comment]
@Lucario2 :+1:
