### ISSUE TITLE
I will wait :)

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#201]
THE PLUGIN CANT PASS PLAYERJOINEVENT WHEN A PLAYER JOIN THE SERVER AND I CANT PUT /setgroup SoyPro Owner world,IN THE CONSOLE THROW ME,AN ERROR OCURRED WHILE ATTEMPED TO PERFORM THIS COMMAND,CAN YOU FIX THIS??

**Comment by 64FF00** [comment]
@SoyPro OMG COULD YOU PLEASE TELL ME WHAT HAPPEEND ON CONSOLEEE? LIKE YOU WILL SEE RED ERRORS WHEN USING /SETGROUP

**Comment by SoyPro** [comment]
I eliminated the Server :( :( :(

**Comment by SoyPro** [comment]
Dont close this i will not enable multiworld-support because it has a lot of errors

**Comment by SoyPro** [comment]
PureChat you fix it but this ?

**Comment by SoyPro** [comment]
But you make a awesome plugin man

**Comment by SoyPro** [comment]
I will create a new server, if i found errors,I dont known man

**Comment by SoyPro** [comment]
Noooo _64FF00 dont abandon this plugin you are a great noo if you do i will cry :{

**Comment by 64FF00** [comment]
@SoyPro :'( Please reopen this issue with the error you get on console
