### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by YaBoiLewis** [PurePlugins/PurePerms#208]
Permissions aren't parsed correctly. Did "/setgperm Guest kits.kit.Warrior" and the permission doesn't work.

**Comment by 64FF00** [comment]
@YaBoiLewis More details? Like what provider are you using now, and how does your groups.yml look like, and so on... Just a plain short description of the issue won't help me at all.

**Comment by YaBoiLewis** [comment]
Provider : MinersPlanet
groups.yml looks fine.
I can send you the source code of plugin so you can check for issues but overall, everything seems fine to me in my plugin.

**Comment by 64FF00** [comment]
Please reopen this issue with your PurePerms groups.yml, config.yml, and the link to your Kits plugin source

**Comment by YaBoiLewis** [comment]
Config : https://www.dropbox.com/s/yyzzpn0yz1bec2l/config.yml?dl=0
Groups : https://www.dropbox.com/s/w7ocgj4b4xus64o/groups.yml?dl=0
Kits - Plugin : https://www.dropbox.com/s/7lu6nts0s4877vi/phar_Kits_4zREBu4mQdeZ4K7.phar?dl=0

**Comment by 64FF00** [comment]
@YaBoiLewis Thanks.

**Comment by YaBoiLewis** [comment]
Hi,

Have you figured it out?
