### ISSUE TITLE
CRITICAL Unhandled exception executing command

### ISSUE THREAD

**Issue by mightysun99** [PurePlugins/PurePerms#21]
WARNING RuntimeException: "array_merge(): Argument 1 is not an array" (E_WARNING) in "/PurePerms_v1.0.3.phar/src/_64FF00/PurePerms/ppdata/PPUser" at line 62
23.01 21:04:06 [Server] CRITICAL Unhandled exception executing command 'setgroup mightysun99

**Comment by 64FF00** [comment]
@64FF00 *closes
