### ISSUE TITLE
Request: set permissions on PreLoginEvent

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PurePerms#210]
A lot of plugins which I made but also other plugins check permissions on PreLoginEvent and don't work properly. Can you set permissions on PreLoginEvent, please?

**Comment by 64FF00** [comment]
@AryToNeX I recommend you to check permissions on PlayerLoginEvent instead of PlayerPreLoginEvent, since most of the player information does not get initialized on pre-login process. I'll move it to PlayerLoginEvent instead.
