### ISSUE TITLE
Give set group permission to CoOwner but block Owner Rank

### ISSUE THREAD

**Issue by kabluinc** [PurePlugins/PurePerms#211]
Is there a permission code/node which I can set to a CoOwner so that they can only set ranks up to CoOwner and not Owner.
I don't want them giving players Owner or giving it to themselves!

Thanks

**Comment by jazzwhistle** [comment]
Add Owner to the superadmin rank in the new config

**Comment by kabluinc** [comment]
so in the config file it says this
# Special thanks to @jazzwhistle for helping me with this cool feature! #JAZZWHISTLE-FTW
# Ranks that can only be set on console
# Also, users with a superadmin-rank can only have their rank changed on console
# - array
superadmin-ranks: ["OP"]
...

where do I write Owner

**Comment by kabluinc** [comment]
so where it says "superadmin-ranks: ["OP"]" do I write Owner next to it e.g. "superadmin-ranks: ["OP"] Owner" ?

**Comment by jazzwhistle** [comment]
You want:

superadmin-ranks: ["Owner"]

If you added more it would be

superadmin-ranks: ["Owner","MainOwner","SuperDuperOwner"]

and so on...

**Comment by kabluinc** [comment]
Ok thank you very much
