### ISSUE TITLE
Purge Command

### ISSUE THREAD

**Issue by BobbyTowers** [PurePlugins/PurePerms#213]
Is there anyway you could a some type of old player purge command to delete players that haven't logged in some time. Or maybe add something in the config to delete old players after a certain time?

**Comment by YaBoiLewis** [comment]
Hi,

You can delete them. Just go into folder and find their name, and delete. Then restart server and volah!

**Comment by BobbyTowers** [comment]
@YaBoiLewis No dude, I have way to many players to do it manually. I would like something to delete old players that haven't been on in a few months.

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/issues/177
