### ISSUE TITLE
1.3.7 mysql bugging when adding worlds

### ISSUE THREAD

**Issue by predawnia** [PurePlugins/PurePerms#216]
Using 1.3.7 and mysql, when issuing the command /setgperm Guest permission.node world2

the permission is set correctly in mysql table groups_mw

when issue same command for another world 
/setgperm Guest permission.node world3

It replaced world2 in table groups_mw and all data for world2 is lost, replaced by world3

It seems you can only have 1 world specified in groups_mw table

and sometimes just a blank table and all perms data are lost as well.

**Comment by predawnia** [comment]
One more thing I forgot to mentioned... 
enable-multiworld-perms: true

**Comment by kenygamer** [comment]
@predawnia Was the problem fixed with the new PurePerms updates ?
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by jasonwynn10** [comment]
Closing due to lack of response
