### ISSUE TITLE
Multiworld error

### ISSUE THREAD

**Issue by RaGeXMe** [PurePlugins/PurePerms#223]
When i try adding permissions to different wordls, it will give me this error when i open the server: "RuntimeException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 37, column 3), context while parsing a block mapping (line 3, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 124" and it will disable the plugin.

Here is my groups.yml:

[groups.txt](https://github.com/PurePlugins/PurePerms/files/216128/groups.txt)

**Comment by 64FF00** [comment]
yaml_parse() errors = 100% bad config -> pls check if you have any tabs or invalid characters there using http://www.yamllint.com
