### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by ClockProgramming** [PurePlugins/PurePerms#225]
```
Notice: Uninitialized string offset: 0 in phar://C:/Users/glitc/Documents/Genisys/plugins/PurePerms_v1.3.7.phar/src/_64FF00/PurePerms/PPListener.php on line 69
Notice: Uninitialized string offset: 0 in phar://C:/Users/glitc/Documents/Genisys/plugins/PurePerms_v1.3.7.phar/src/_64FF00/PurePerms/PPListener.php on line 69
```

**Comment by GlitchPlayer** [comment]
That happens when players join the server.

**Comment by CortexPE** [comment]
@64FF00 use substr($message, 0, 1) instead of $message[0]
(It worked for me. but according to StackOverflow you'll waste a few milliseconds)

**Comment by CortexPE** [comment]
Ik $message[0] should work... but idk why it wouldn't.
> Ugh. Code sometimes just doesn't work for no reason.

**Comment by jasonwynn10** [comment]
Is this fixed in the latest commit?
