### ISSUE TITLE
Disable-Op Config

### ISSUE THREAD

**Issue by Mike4l6** [PurePlugins/PurePerms#226]
In default in the config file, Disable-OP is set to true, I put it to false and after I reload the server, I realized the Disable-OP is set back to true !!! Please Fix

**Comment by dktapps** [comment]
Pull request #224 has a fix for this issue, please merge it @64FF00

**Comment by 64FF00** [comment]
Already fixed in https://github.com/PurePlugins/PurePerms/commit/c12747dd881984c574bf639d3a466ad71f14d0f6

**Comment by HittmanA** [comment]
Wow

**Comment by HittmanA** [comment]
Im watching you self assign live xD
