### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XShockinFireX** [PurePlugins/PurePerms#227]
how do i set a players group for all worlds with /setgroup?

**Comment by XShockinFireX** [comment]
anyone?

**Comment by SalmonGER** [comment]
@XShockinFireX Do you want to set a default group for all worlds?

**Comment by XShockinFireX** [comment]
no, i want to set a players group, but for all worlds with /setgroup

**Comment by XShockinFireX** [comment]
cause i have multiworld groups
