### ISSUE TITLE
Wheres the .phar download? dragging this to my PM directory doesnt do anything!

### ISSUE THREAD

**Issue by MhikeiMPC** [PurePlugins/PurePerms#232]
I need a phar what am i supposed to do with the files in the master zip?

**Comment by SalmonGER** [comment]
You could make your own phar with the files in the zip or download a phar from here:
https://github.com/PurePlugins/PurePerms/releases

**Comment by MhikeiMPC** [comment]
Sorry for being such a noob :P im new to GitHub.

**Comment by SalmonGER** [comment]
@MhikeiMPC It's fine :D

**Comment by robske110** [comment]
Close this issue please :)
