### ISSUE TITLE
How i can add levels to ranks?

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#233]
Example [Guest] [Lvl 1] [Steve].

**Comment by SalmonGER** [comment]
In the chat?

**Comment by SoyPro** [comment]
When you talk i want [Guest] lvl1 Steve

**Comment by robske110** [comment]
Close this issue, there is no way to do it

**Comment by SoyPro** [comment]
Yes there ,is

**Comment by SalmonGER** [comment]
If you mean the PureChat format use {world}

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PureChat/issues/46

This is definitely related to PureChat, not PurePerms. You silly :P @SoyPro
