### ISSUE TITLE
Diffrent group display in diffrent worlds

### ISSUE THREAD

**Issue by kabluinc** [PurePlugins/PurePerms#236]
I tried doing /setgroup (player) Admin world and /setgroup (player) CoOwner world2 but when the player moves worlds his rank stays the same

is it possible to have different rank diplay in different worlds. e.g. your an admin in world and CoOwner in world2

I have multi word perms set to true in config

**Comment by kenygamer** [comment]
@kabluinc Use PureChat for this. /setnametag will help you. You will also have to enable multi-world support in that plugin, so that both plugins complement each other correctly.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by jasonwynn10** [comment]
Is this error still occurring with the latest commit?
