### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by Smasher535** [PurePlugins/PurePerms#237]
Ok, let's say I create a group named BuilderPlus, I know when a BuilderPlus player say something in chat, it'll say:
 [BuilderPlus] Steve > test
I wanna set a prefix for the BuilderPlus group so it'll be like:
 [Builder+] Steve > test
If it's possible, then I'll be able to do colors, like:
/setgprefix BuilderPlus §e[§9Builder+§e]§r
So it will be yellow, light blue

**Comment by SalmonGER** [comment]
Do it with PureChat

**Comment by BlockCraftMCPE** [comment]
@Smasher535 Download Pure Chat.
Then Make /setformat BuilderPlus global [{HereGoesYourBuilderTag}] : {display_name} > {msg}

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SuperOP535** [comment]
Are you stupid? This was sent more than 1 year ago, I made a server and I quitted mcpe... It's a bad time to answer... I will now delete this shit from my other account
