### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mightysun99** [PurePlugins/PurePerms#24]
30.03 23:09:28 [Server] WARNING RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/PurePerms_v1.0.8.phar/src/_64FF00/PurePerms/ppdata/PPGroup" at line 24
30.03 23:09:28 [Server] CRITICAL Could not pass event pocketmine\event\player\PlayerJoinEvent to PurePerms v1.0.8: Invalid argument supplied for foreach() on _64FF00\PurePerms\PPListener

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/commit/906d8e677dace8f406a73bc523233d2d1d6ff85f
