### ISSUE TITLE
/rmgroup not working

### ISSUE THREAD

**Issue by ZePigThouv** [PurePlugins/PurePerms#241]
Hello,
I've just setup the latest PurePerms version from GitHub (1.4.0-INDEV) on my PocketMine server running PocketMine 1.6.2dev for MC 1.0.
I've set the data provider to MySQL and everything seems to be working fine, if I add a group it gets added to the group table in the database, if I set a perm it gets added to the permissions column of the database.
The only problem is with /rmgroup.
Whenever I try removing a group, either in-game or through the console, it says it was successfully deleted. But, when I check with /groups, the group is still there. I also checked in the database, and the group was there as well.

**Comment by Borduni** [comment]
Does it work now? :D

**Comment by Borduni** [comment]
//closed
