### ISSUE TITLE
[1.0.0.0] API Problem 

### ISSUE THREAD

**Issue by HasanBrandsXD** [PurePlugins/PurePerms#243]
It says that all plugins are are incompaitable by the API including PurePerms! I NEED HELP!

PurePerms were the best plugins ;(

**Comment by AnkitM252** [comment]
download the latest zip and change the api of plugin.yml to [2.0.0,3.0.0]

**Comment by HasanBrandsXD** [comment]
Its not working.

**Comment by AnkitM252** [comment]
Do like i said! Download source and extract it and download devtools and install it too and open the pureperms folder,open plugin.yml and change the api to [2.0.0,3.0.0]

**Comment by Mgl642001** [comment]
Doesn't work. I did it but when I do it it works, but no rank is shown. Like if I didn't have it.

**Comment by Borduni** [comment]
It should be fixed now

**Comment by kenygamer** [comment]
It is a call to all developers to update their plugins..
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Borduni** [comment]
Can i close this issue?

**Comment by Borduni** [comment]
//closed
