### ISSUE TITLE
Rank expiry time not working

### ISSUE THREAD

**Issue by ealgueiroqb9** [PurePlugins/PurePerms#246]
Hello, I'm creating ranks with an expiry date but they never expire and fall back to the default rank.
Is this feature working? I'm using the MySQL provider and the plugin doesn't store the expiry date anywhere.
Thanks.

**Comment by jasonwynn10** [comment]
Is this issue still occurring?

**Comment by MrDoni98** [comment]
I fixed the exp time for my server. With pleasure I will share with you.

**Comment by NanoRayYT** [comment]
You fixed it for Yaml, but mysql does not support exp time..
