### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by mightysun99** [PurePlugins/PurePerms#25]
30.03 23:01:21 [Server] EMERGENCY The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/1599325 or use the ID #1599325.
30.03 23:01:21 [Server] EMERGENCY Please submit the "/CrashDump_Tue_Mar_31-01.01.21-EASST_2015.log" file to the Bug Reporting page. Give as much info as you can.
30.03 23:01:21 [Server] EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
30.03 23:01:21 [Server] INFO Fatal error: Call to undefined method _64FF00\PurePerms\ppdata\PPGroup::getLogger() in phar:///plugins/PurePerms_v1.0.8.phar/src/_64FF00/PurePerms/ppdata/PPGroup.php on line 55

**Comment by 64FF00** [comment]
Will be fixed in v1.0.9

**Comment by 64FF00** [comment]
@mightysun99 Fixed :3
