### ISSUE TITLE
1.0.7

### ISSUE THREAD

**Issue by Megalunchbox** [PurePlugins/PurePerms#250]
Currently I am unable to use pureperms on 1.0.7, it launches fine.. but I cannot join the server. This problem is only caused by this plugin and I haven't tested an older version, only the latest.

**Comment by Borduni** [comment]
#644FF0 pls fix that. i cannot run my server, when i haven't any ranks

**Comment by ifvictr** [comment]
@Megalunchbox @Borduni This plugin is no longer maintained. Please go to here instead: https://github.com/poggit-orphanage/PurePerms
