### ISSUE TITLE
[IMPORTANT] READ THIS FIRST BEFORE SUBMITTING AN ISSUE

### ISSUE THREAD

**Issue by 64FF00** [PurePlugins/PurePerms#252]
this plugin is stale af 
pls go make your own plugin if you are gonna keep bragging about how good you are as a plugin developer
and yes pureperms really sucks don't expect too much

**Comment by 64FF00** [comment]
since y'all are saying like 'i'm a real pro dev' or 'i make plugins better than that sixtyfour scrub' why don't you just... well

**Comment by Borduni** [comment]
Pls don't give up this work

**Comment by ProjectInfinity** [comment]
@64FF00 LOL. You've still not changed huh :P

**Comment by 64FF00** [comment]
@projectinfinity <3

**Comment by 64FF00** [comment]
well everything there is quite true though
also i realised that being a php developer is not something to brag about... (lmao i'm not even sure if i can call myself developer i suck too mooch)
minecraft is considered a super cancer game only for kids here so maybe those should be why i find it less fun to work on those stale pmmp plugins

**Comment by ProjectInfinity** [comment]
@64FF00 Do what I did. I moved on to making services like PocketVote and I used the opportunity to play with NodeJS.

**Comment by HimbeersaftLP** [comment]
> minecraft is considered a super cancer game only for kids here so maybe those should be why i find it less fun to work on those stale pmmp plugins

Totally agreed

**Comment by 64FF00** [comment]
@projectinfinity ilysm

**Comment by 64FF00** [comment]
@himbeersaftlp yes

**Comment by 64FF00** [comment]
@jasonwynn10 👍

**Comment by 64FF00** [comment]
@ProjectInfinity ye me lernin nodejs c# python and docker

**Comment by Borduni** [comment]
So many labels... that looks weird xD

**Comment by Borduni** [comment]
I will make PurePerms great again!

**Comment by Epsimatt** [comment]
@Borduni @jasonwynn10 <3

**Comment by 64FF00** [comment]
you will

**Comment by Borduni** [comment]
Okay, I realized, that this is very hard to do that alone. Need some good devs and a active commiunity :(

**Comment by Borduni** [comment]
Why this?

**Comment by jasonwynn10** [comment]
Just cause
