### ISSUE TITLE
Player Disconnect

### ISSUE THREAD

**Issue by jrodr10** [PurePlugins/PurePerms#254]
For some reason when using Tesseract.. since it's the last api 2.0.0 build out. Players aren't able to connect to the server. If you remove pureperms players can join without disconnect.

**Comment by HimbeersaftLP** [comment]
Tesseract issue, it works fine with PMMP...

**Comment by jrodr10** [comment]
Well it has to be a plugin issue if the plugin is the cause of players not being able to join..... @HimbeersaftLP

**Comment by HimbeersaftLP** [comment]
This plugin has never meant to be compatible with Tesseract, and since it works with PocketMine, this isn't a plugin issue

**Comment by XxParkerGamesxX** [comment]
it was working well before

**Comment by jrodr10** [comment]
My point exactly and the new pocketmine isn't the only software in PHP for MCPE. Nor should it be. I don't care for your opinion toward Tesseract. But this is a bug that start on your 1.4.0 releases

**Comment by jrodr10** [comment]
@himbeersaftLP

**Comment by HimbeersaftLP** [comment]
> new pocketmine isn't the only software in PHP for MCPE

It is, the others are all variants aka spoons of PocketMine. It isn't the plugin's fault when it doesn't work on a software that it isn't supposed to be used on

**Comment by jrodr10** [comment]
PMMP is a spoon of pocketmine

**Comment by jrodr10** [comment]
There hasnt been an original since 1.4 @HimbeersaftLP

**Comment by HimbeersaftLP** [comment]
PMMP is an abbreviation of PocketMine-MP...
And the org pmmp is the official new home of PocketMine

**Comment by jrodr10** [comment]
"new home" no the official home is the official home not just some copiers who claim they are original lmao. the devs should fix this issue even if the spoon named pmmp can run it.

**Comment by HimbeersaftLP** [comment]
No, it's official see [here](https://github.com/PocketMine/PocketMine-MP/commit/3f279888bd5ac195da55c474bc8be156afae08a4) and [here](http://forums.pocketmine.net/threads/moving-day.18639/)

**Comment by kenygamer** [comment]
Hey there,

This problem has been reported by multiple PurePerms users and the solution is to download the newest version at poggit.pmmp.io. Until RakLib is not updated.

USING SPOONS IS NOT SUGGESTED!
Spoons doesn't guarantee complete support, although they have more features than PocketMine-MP.

> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by ProjectInfinity** [comment]
@kenygamer Please stop calling it "spoon". The correct terminology is [fork](https://en.wikipedia.org/wiki/Fork_(software_development)).

**Comment by jasonwynn10** [comment]
@ProjectInfinity the pmmp community call's it a spoon because they usually aren't good enough to be called a fork. It's just a play on words 😋

**Comment by kenygamer** [comment]
@ProjectInfinity Updated my comment.
