### ISSUE TITLE
Groups not 'loaded' + more

### ISSUE THREAD

**Issue by BudderSticks** [PurePlugins/PurePerms#256]
This problem came out of no where, I joined my server one day and the ranks did not work. I went to check on the console to see what was happening and it said PurePerms groups not loaded. I did not change my server jar, new plugins or anything, I didnt do anything. They just like unloaded themselves.

I also tried to reinstall the pureperms plugins and matched all the stuff in the PurePerms groups file to the PureChat config file.

Plus where is the download link for PurePerms here at the github page. I know about the zip download and I do not know how to convert zip to phar. So I need the phar download please for latest version.

**Comment by jasonwynn10** [comment]
https://poggit.pmmp.io/ci/poggit-orphanage/PurePerms/~
