### ISSUE TITLE
Low Tps When Using Mysql Provider

### ISSUE THREAD

**Issue by ChaostixZix** [PurePlugins/PurePerms#258]
I'm using PMMP/PocketMine-MP Unleashed API 3.0.0-ALPHA5 on Ubuntu 14.10 x86_64

When I use the YamlV1 provider, My TPS rate is above 15, but When I use MySQL, it's under 15. This only happens when a player joins. How can I fix this?

**Comment by Borduni** [comment]
So both dropped under 15ms?

**Comment by ChaostixZix** [comment]
Im Sorry, When Using YAML ,The Tps Is More Than 15, But When Using Mysql ,The Tps Lower Than 15

**Comment by ChaostixZix** [comment]
Is Slapper Run Query EveryTime Player Chat?

**Comment by spoopystarman** [comment]
How do I get groups?

**Comment by Borduni** [comment]
Do you mean /setgroup <player> <group>?
Or: /addgroup <group>

**Comment by ProjectInfinity** [comment]
Is the tps consistently low when using MySQL or only when a player joins?

**Comment by jasonwynn10** [comment]
This is outdated
