### ISSUE TITLE
PurePerms API

### ISSUE THREAD

**Issue by kenygamer** [PurePlugins/PurePerms#259]
How do i get all players that have a specific permission node in my plugin?
(Individually).

Thank you.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Borduni** [comment]
Do you mean /setuperm <permission>?

**Comment by kenygamer** [comment]
@Borduni Yes.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Borduni** [comment]
Can I close this issue?

**Comment by BlockCraftMCPE** [comment]
@kenygamer You mean The Plugin Should check who on the server have this perm?

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jasonwynn10** [comment]
`How do i get all players that have a specific permission node in my plugin?`
This is PocketMine API. Look it up.
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L565L570
