### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by alexbgameson** [PurePlugins/PurePerms#262]
With the latest release of mcpe server software this plugin causes the clients game to crash when they attempt to join.

**Comment by kenygamer** [comment]
@alexbgameson What mcpe software are you using? Please download the newest version at poggit.pmmp.io if you use spoons (Tesseract is an example).
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by zKoz210** [comment]
Revert this. Fixed https://github.com/GenisysPro/GenisysPro/pull/263
