### ISSUE TITLE
Permission Nodes being ignored

### ISSUE THREAD

**Issue by FienixEC** [PurePlugins/PurePerms#264]
With this latest MCPE update, all permission nodes a group has are being ignored, Anyone have similar issue?

name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: "1.4.0-INDEV"

This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)

**Comment by AydarTop** [comment]
@FienixEC I have similar problem

**Comment by kenygamer** [comment]
Please add more information to the issue.

> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by jasonwynn10** [comment]
Is the issue still occurring?

**Comment by EpicPinkCreeper** [comment]
Do you have simpleauth? I had this problem and then got rid of it and the problem was fixed, but I guess it could be a different thing doing it.

**Comment by jasonwynn10** [comment]
Simpleauth unsets all permissions when players join but doesnt re-set them. try a different auth plugin
