### ISSUE TITLE
Timeout Error when using PurePerms on Genisys-pro or Tesseract

### ISSUE THREAD

**Issue by djdisodo** [PurePlugins/PurePerms#268]
한국분이신것 같아 그냥 한국어로 적겠습니다.
pureperms는 pocketmine와 호환되는 플러그인으로 알고있는데, 요즘 한국에서는 다들 genisys-pro나 tesseract등을 이용하고 있습니다.
genisys-pro랑 tesseract에서 pureperms를 사용하면 무조건 사용자가 접속할때 timeout이 뜨는 호환성 오류가 있는데 고쳐주실수 있나요?
대부분의 분들이 다른 구동기 말고 pocketmine을 사용해보라고 하지만
실제로 운영중인 서버에서 구동기를 pocketmine으로 바꾸기엔 pocketmine과 파생 구동기들의 개발상황이 많이 달라서 기존 플러그인들과의 호환성 문제가 발생할수 있습니다

Google translation:

I think I'm from Korea.
Pureperms is a plug-in compatible with pocketmine. Nowadays in Korea, everyone uses genisys-pro or tesseract.
If you use pureperms on genisys-pro and tesseract, can you fix a compatibility error that timeout occurs when a user connects?
Most people would try to use pocketmine instead of other actuators
Pocketmine and its derivative drivers are very different from the actual operating server to replace the driver with pocketmine, which may cause compatibility problems with existing plugins

**Comment by 64FF00** [comment]
감사합니다 제가 다른 개발자분들한테도 말씀드리겠습니다

**Comment by 64FF00** [comment]
@jasonwynn10 Mr. Wynn could you take a look at this issue please? Tbh I've never used Genisys forks and Tesseract b4...

**Comment by jasonwynn10** [comment]
@64FF00 I haven't either, so this should be fun...

**Comment by kenygamer** [comment]
@64FF00 @jasonwynn10  I've had the same issue before.
Solution:
Install an older version of **PurePerms**.
*v1.3.7* works on **Tesseract**.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Johnmacrocraft** [comment]
@64FF00
한국에서는 사용을 안 한다니요... 대부분 다른 랭크 플러그인을 사용해서 그렇지 사용하는 사람도 있을 겁니다 (아마도). 참고로 (당연히) 저는 이 댓글을 작성했으니 이 플러그인을 매우 유용하게 사용하고 있습니다.
(사실 LE**라는 작은 서버 호스팅 해주는 외국 호스팅을 사용해서 알게 되었습니다.)

**Comment by Johnmacrocraft** [comment]
(ignore that reference, it's not something to say stop using spoon/fork)

**Comment by kenygamer** [comment]
@Johnmacrocraft 
> Please stop calling it SPOON, the correct terminology is [fork](https://en.m.wikipedia.org/wiki/Fork_(software_development).
// ProjectInfinity

**Comment by Johnmacrocraft** [comment]
@kenygamer Whatever, I just wanted it to call it was spoon lol

**Comment by kenygamer** [comment]
Just a cite.

**Comment by Johnmacrocraft** [comment]
@kenygamer oh, k

**Comment by jasonwynn10** [comment]
If this plugin still doesn't work on GenesisPro, then the software needs to be more compatible with PMMP API
