### ISSUE TITLE
Perm Bug - EssentialsPE

### ISSUE THREAD

**Issue by ekkogaming** [PurePlugins/PurePerms#269]
why bug /setgperm A essentials.warps.a 
You Are No Permission! 
Why ! Im SetWarp and OpenWarp !
Bug Permission For Mutilworld !
Fixed Please ! Im Make Server Prison Bug Warp Im Unhappy m

**Comment by Borduni** [comment]
Do you have OP rights?

**Comment by ekkogaming** [comment]
No OP Im Setgperm !

Vào 24-06-2017 14:10, "Borduni" <notifications@github.com> đã viết:

**Comment by kenygamer** [comment]
@ekkogaming Please use [**Google Translator**](https://translate.google.com) - **English** so that we can understand what do you want to say.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by ekkogaming** [comment]
This means that only the op can use the command even though I have already
setgpermn for the group! I think it's a bug here!

Vào 26-06-2017 4:45, "Kevin Andrews" <notifications@github.com> đã viết:

**Comment by kenygamer** [comment]
@ekkogaming Please provide more information.
Such as your *config.yml*, *permissions.yml*, PurePerms version.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by ekkogaming** [comment]
1.4.0

Vào 26-06-2017 22:57, "Kevin Andrews" <notifications@github.com> đã viết:

**Comment by kenygamer** [comment]
@ekkogaming *config.yml*, *permissions.yml*...
---
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by ekkogaming** [comment]
Yes i edit file and Setgperm ! You Are No Permission

Vào 27-06-2017 6:14, "Kevin Andrews" <notifications@github.com> đã viết:

**Comment by kenygamer** [comment]
@ekkogaming include your **FULL** config.yml, permissions.yml files.
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Borduni** [comment]
How you can be a permission?

**Comment by Sandertv** [comment]
You can close this. As the current EssentialsPE maintainer I can tell you that this is simply due to the fact that the wrong permissions have been given.

To allow players to use a warp, give them:
`essentials.warps.<warpname>`,
`essentials.warp.use`

If you want players to be able to use any warp, give them:
`essentials.warps.*`

**Comment by ekkogaming** [comment]
It does not work!

Vào 10-07-2017 5:07, "Sandertv" <notifications@github.com> đã viết:

**Comment by Sandertv** [comment]
Have you made sure you're not using SimpleWarp like I said?

**Comment by ekkogaming** [comment]
Simplewarp does not support each warp perm!

Vào 10-07-2017 12:56, "Sandertv" <notifications@github.com> đã viết:

**Comment by kenygamer** [comment]
@ekkogaming Exactly so, @Sandertv is asking if you are **NOT** using *SimpleWarp*.
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ
