### ISSUE TITLE
PureChat 오류 리포트

### ISSUE THREAD

**Issue by ruddn0101** [PurePlugins/PurePerms#27]
[Server] 13:14:09 [CRITICAL] Could not pass event pocketmine\event\player\PlayerChatEvent to PureChat v1.2.3: yaml_parse(): parsing error encountered during parsing: did not find expected key (line 19, column 4), context while parsing a block mapping (line 8, column 3) on _64FF00\PureChat\ChatListener
[Server] 13:14:09 [WARNING] RuntimeException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 19, column 4), context while parsing a block mapping (line 8, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 137

콘피그부분에서 우류납니다

**Comment by 64FF00** [comment]
설정 파일에 오타나 잘못된 문자 등이 들어갔을 경우에 생기는 오류입니다. http://www.yamllint.com에 들어가서 설정 파일 내용 전체를 복붙하신 뒤에 잘못된 곳만 수정해주세요.
