### ISSUE TITLE
When in MySQL mode gets Segment Fault 

### ISSUE THREAD

**Issue by linuzo** [PurePlugins/PurePerms#273]
Causes segmentation fault when enabled on MySQL mode only. If I revert to yaml it works fine. 

Anyone know why this suddenly started happening??  

Was working fine up to about a month ago..

**Comment by jasonwynn10** [comment]
Any errors or crashdumps?

**Comment by linuzo** [comment]
Well it doesn't create a crashdump just gives segment fault and crashes. I think it is a php7 error..

**Comment by jasonwynn10** [comment]
does your server have the MySQL extension on it?

**Comment by linuzo** [comment]
Yes we use many MySQL plugins this is the only one causing segment faults though. Simpleauth, netherchest, etc also use MySQL they work fine. This plugin use to work before PHP updated to a newer version I believe

**Comment by jasonwynn10** [comment]
I'll look into it

**Comment by linuzo** [comment]
@jasonwynn10 I enabled Debugging Level 4 in pocketmine and for some reason only on my 19132 server this happens. I can't reproduce it on my other servers that are connected to MySQL..  

[PurePerms] Registering player **...
./start.sh: line 65: 10611 Segmentation fault      "$PHP_BINARY" "$POCKETMINE_FILE" $@

That's what it says during connect right before it crashes..  Still no crash dump..  Not sure if this helps or not but I miss using PurePerms for MySQL because of multiple servers depending on this.

**Comment by jasonwynn10** [comment]
Probably an incorrect installment
