### ISSUE TITLE
API PocketMine-MP

### ISSUE THREAD

**Issue by Bruno99** [PurePlugins/PurePerms#274]
Pls. Update plugin api to 3.0.0-ALPHA7

**Comment by teracube** [comment]
Hi,
I try 
PurePerms: Dev build #8 16/07/2017 à 01:41:44 Updated for API version 3.0.0-ALPHA7. Breaks BC
+
PocketMine-MP_1.6.2dev-305_1a7f567a_API-3.0.0-ALPHA7.phar

The server refused to start and show error Imcompatible API version 

Is PurePerms: Dev build #8 compatible PI-3.0.0-ALPHA7 or a bug ?

Thanks

**Comment by Borduni** [comment]
#280

**Comment by Borduni** [comment]
Update to the latest version. Bumped API's already :)
