### ISSUE TITLE
How Can i transfer YAML to MySql?

### ISSUE THREAD

**Issue by exepx** [PurePlugins/PurePerms#277]
How can i transfer Yaml to MySql Data?

**Comment by ealgueiroqb9** [comment]
You'll have to write a process for that. It's like using 2 providers at the
same time. You can run it in your onEnable function.

**Comment by exepx** [comment]
haha, i dont even know how to do that. is there any plugin that can transfer it?

**Comment by ealgueiroqb9** [comment]
Mmmh nah I don't think so. I wrote that for my daytime job though. I can
tell it works.
