### ISSUE TITLE
Plugin doesnt work anymore

### ISSUE THREAD

**Issue by PhoenixGamer** [PurePlugins/PurePerms#278]
even if i set the permissions for simplewarp or vanish i can only use the commands if i am op

**Comment by jasonwynn10** [comment]
That's a simplewarp problem

**Comment by Falkirks** [comment]
`simplewarp && vanish !== simplewarp`

If it was just simplewarp, I would suggest verifying you have run `/openwarp [name]` on the warps you want to give players permission to use.

**Comment by PhoenixGamer** [comment]
No. I used /addwarp

**Comment by PhoenixGamer** [comment]
After i added a new Group and deletetd the other Vanish works now to.

**Comment by 64FF00** [comment]
waw
