### ISSUE TITLE
getUserData() on null

### ISSUE THREAD

**Issue by llj070** [PurePlugins/PurePerms#28]
Error: Call to a member function getUserData() on null
File: /PurePerms_v1.0.8.phar/src/_64FF00/PurePerms/ppdata/PPUser
Line: 20
Type: E_ERROR

[18]     public function getData()
[19]     {
[20]         return $this->plugin->getProvider()->getUserData($this, true);
[21]     }

**Comment by llj070** [comment]
phpstorm show namespace _64FF00\PurePerms\providers;


public function getGroupsData()
Declaration must be compatible with ProviderInterface->getGroupsData([isArray : bool = false])

public function getUserData(PPUser $user)
Declaration must be compatible with ProviderInterface->getUserData(user : \_64FF00\PurePerms\ppdata\PPUser, [isArray : bool = false])

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/commit/906d8e677dace8f406a73bc523233d2d1d6ff85f
