### ISSUE TITLE
Default permissions ignored

### ISSUE THREAD

**Issue by EpicPinkCreeper** [PurePlugins/PurePerms#282]
The default permissions in plugins are ignored by this plugin so I have to set them all in the groups.yml manually.

**Comment by jasonwynn10** [comment]
The default permissions are not ignored by this plugin. Have you checked with your Auth plugin? Many will deny permissions until a player is logged in

**Comment by EpicPinkCreeper** [comment]
Yes, I think the problem was the auth plugin. Since I got a different auth
plugin It has been working again.
