### ISSUE TITLE
Have to reload

### ISSUE THREAD

**Issue by EpicPinkCreeper** [PurePlugins/PurePerms#283]
I have to /reload the server after I start it up because the group permissions are not working the first time.  I also have to /reload it every once in a while because it seems to revert after a while.  This is a problem since I have to use /reload from my phone if I am away but it says I do not have permissions to use it.

**Comment by jasonwynn10** [comment]
Is there a crashdump or any log error?

**Comment by EpicPinkCreeper** [comment]
It hasn't happened today so I am guessing the problem was either something I had in one of the groups or something weird with one of my plugins that I got rid of recently.   I did not get any crashdump and no log errors showed up, and the only way to tell had been in game and actually testing it out, so it probably was another plugin messing this up.
