### ISSUE TITLE
HELP! How to unset every permission???

### ISSUE THREAD

**Issue by nikoskon2003** [PurePlugins/PurePerms#292]
HELLO!
I know to unset a permission you do /setg(u)perm <group> -(permission) 
but i wanna do /setgperm Guest -*
this doesnt work :(
how to unset every permission???
if i do /setgperm Guest -pokcetmine
it disables only pocketmine commands not plugin ones!
plz respond asap!!

TY,
nikoskon

**Comment by jasonwynn10** [comment]
Plugins have their own permissions. If you only remove the PocketMine permissions, then no plugins will be affected because none of them use PocketMine in their permissions
