### ISSUE TITLE
Please fix config

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [PurePlugins/PurePerms#32]
Each time you run the server confg.yml is reset to standard

I'm sorry, I translated in Google

**Comment by 64FF00** [comment]
Are you sure about this? Seems like it's not happening for me.

**Comment by qwefqwfqwefqwef** [comment]
Yes

**Comment by qwefqwfqwefqwef** [comment]
Eeeem "messages-version: "1.1.3" ? May be messages-version: "1.1.4"

**Comment by 64FF00** [comment]
@qwrfqwfqwefqwef I see thanks. Looks like it's a problem related to message version checks.
