### ISSUE TITLE
Server crashes with 1.1.4

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PurePerms#33]
"Fatal error: Call to undefined method _64FF00\PurePerms\ppdata\PPGroup::getPermissions() in phar:///home/anthony/server/plugins/PurePerms.phar/src/_64FF00/PurePerms/ppdata/PPGroup.php on line 100"

**Comment by 64FF00** [comment]
@AryToNeX

**Comment by NML32** [comment]
I get that error on all three of my servers with the latest build 1.1.4.

**Comment by 64FF00** [comment]
@AryToNeX @NML32 Fixed in v1.1.5 :D
