### ISSUE TITLE
Crashes my server!

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#34]
Please fix this.the update was horrible.error: Call to undefined method_64FF00\PurePerms\ppdata\PPGroup::getPermissions()
File: /plugin-862.phar/src/_64FF00/PurePerms/ppdata/PPGroup
Line:100
Type: E_ERROR 
Please fix that!thanks and this problem ocurred un version 1.1.4

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/issues/33
