### ISSUE TITLE
getPlayerGroup($player)

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PurePlugins/PurePerms#38]
You should add a public function that gets the players group and returns it as a string.

**Comment by 64FF00** [comment]
Use PurePerms::getUser() to get the player's group and PPUser::getGroup($levelName) for getting user group

**Comment by AndreyNazarchuk** [comment]
How would I do that?
Like $this->getPlayer()->PurePerms::getUser()

**Comment by 64FF00** [comment]
@AndreyNazarchuk Just do it like this
``` PHP
$plugin = $this->getServer()->getPluginManager()->getPlugin("PurePerms");
$user = $this->plugin->getUser(/* Player $player */);
$userGroup = $user->getGroup(/* $levelName */);
```

**Comment by AndreyNazarchuk** [comment]
Thanks man.

**Comment by AndreyNazarchuk** [comment]
Wait can I remove the /* */ ?

**Comment by AndreyNazarchuk** [comment]
Ok its not working, can you please make your api like everyone else so I can do getPlayerGroup($player)
