### ISSUE TITLE
/setgperm <group> <permission> 하고 /ppreload 해야 적용이 됨

### ISSUE THREAD

**Issue by onebone** [PurePlugins/PurePerms#44]
버그인가요 아니면 그냥 기능인가요

**Comment by 64FF00** [comment]
@onebone 버그같은 기능인데요

**Comment by 64FF00** [comment]
@onebone 그냥 퍼미션 설정할때마다 자동으로 로드되게 만들까요

**Comment by onebone** [comment]
그래주시면 감사하겠습니다!

**Comment by 64FF00** [comment]
@onebone 근데 그러면 살짝 렉생길것 같은데

**Comment by onebone** [comment]
소스 보니 개별적으로 권한을 추가시키는건 어렵나 보네요
그냥 이슈 닫겠습니다!

**Comment by 64FF00** [comment]
@onebone 이런 이슈는 다시 열어주는게 제맛

**Comment by 64FF00** [comment]
@onebone 어려우면 추가하면 되는거 아입니까

**Comment by 64FF00** [comment]
@onebone https://github.com/PurePlugins/PurePerms/commit/73648a2796263947e10c85b0d5d1e68c1a6e4692 :+1:

**Comment by onebone** [comment]
:+1:
