### ISSUE TITLE
Add Hindi translation!

### ISSUE THREAD

**Issue by JoahDave** [PurePlugins/PurePerms#53]
Maybe viewing desktop GitHub on a mobile device was not the way to go when making a pull request. I'm still confused.

<b>Using <sarcasm>my extensive knowledge of the Hindi language, </sarcasm>and a little bit of Google Translate, I present another translation! I'm curious if anyone is going to use this. </b>

---
messages-version: "1.1.7"
language: "hi"
cmds:
  addgroup:
    desc: "Samūha sūcī kē li'ē ēka nayā samūha kahatē haiṁ."
    usage: "Upayōga: / addgroup <samūha>"
    messages:
      group_added_successfully: "Saphalatāpūrvaka samūha sūcī kō% var0% jōṛā."
      group_already_exists: "Samūha% var0% pahalē sē hī maujūda hai."
  fperms:
    desc: "Ēka viśiṣṭa plaga'ina kē li'ē sabhī anumatiyōṁ kī ēka sūcī dikhātā hai."
    usage: "Upayōga: / fperms <plaga'ina>"
    messages:
      no_plugin_perms: "Plaga'ina% var0% kisī bhī anumati nahīṁ hai."
      plugin_not_exist: "Plaga'ina% var0% maujūda nahīṁ hai."
      plugin_perms_list: "% Var0% sē sabhī plaga'ina anumatiyām̐ (% var1% /% var2%) kī sūcī:"
  groups:
    desc: "Sabhī samūhōṁ kī ēka sūcī dikhātā hai."
    messages:
      all_registered_groups: "Sabhī pan̄jīkr̥ta samūhōṁ:% Var0%"
  listgperms:
    desc: "Ēka samūha sē sabhī anumatiyōṁ kī ēka sūcī dikhātā hai."
    usage: "Upayōga: / listgperms <samūha> <pēja> [duniyā]" 
    messages:
      group_not_exist: "Samūha% var0% maujūda nahīṁ hai."
      group_perms_list: "% Var0% sē sabhī samūha anumatiyōṁ kī sūcī (% var1% /% var2%):"
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      no_group_perms: "Samūha% var0% kisī bhī samūha anumati nahīṁ hai."
  listuperms:
    desc: "Ēka upayōgakartā sē sabhī anumatiyōṁ kī ēka sūcī dikhātā hai."
    usage: "Upayōga: / listuperms <khilāṛī> <pēja> [duniyā]"
    messages:
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      no_user_perms: ". Plēyara% var0% kisī bhī upayōgakartā anumatiyām̐ nahīṁ hai"
      user_perms_list: "% Var0% sē sabhī upayōgakartā anumatiyōṁ kī sūcī (% var1% /% var2%):"
  ppinfo:
    desc: "Lēkhaka, sanskaraṇa, aura ādi# 64FF00 sahita vartamāna PurePerms jānakārī prāpta karēṁ"
    messages:
      ppinfo_console: "Āpa vartamāna mēṁ% var1% sē PurePerms V% var0% kā upayōga kara rahē haiṁ."
      ppinfo_player: "Yaha sarvara% var1% sē PurePerms V% var0% kā upayōga kara rahā hai."
  ppreload:
    desc: "Sabhī PurePerms vin'yāsa kō puna: Lōḍa."
    messages:
      successfully_reloaded: "Sabhī plaga'ina vin'yāsa saphalatāpūrvaka punaḥ lōḍa kara diyā gayā hai."
  rmgroup:
    desc: "Samūha sūcī sē ēka samūha kō nikālatā hai."
    usage: "Upayōga: / rmgroup <samūha>"
    messages:
      group_removed_successfully: "Saphalatāpūrvaka samūha sūcī sē% var0% haṭā diyā."
      group_not_exist: "Samūha% var0% maujūda nahīṁ hai."
  setgperm:
    desc: "Samūha kē li'ē kō'ī anumati kahatē haiṁ."
    usage: "Upayōga: / setgperm <samūha> <anumati> [duniyā]"
    messages:
      gperm_added_successfully: "Saphalatāpūrvaka samūha kī anumati% var0% jōṛā."
      group_not_exist: "Samūha% var0% maujūda nahīṁ hai."
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
  setgroup:
    desc: "Upayōgakartā kē li'ē samūha sēṭa karatā hai."
    usage: "Upayōga: / setgroup <khilāṛī> <samūha> [duniyā]"
    messages:
      group_not_exist: "Samūha% var0% maujūda nahīṁ hai."
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      setgroup_successfully: "Saphalatāpūrvaka samūha kē li'ē% var0% jōṛā."
  setuperm:
    desc: "Upayōgakartā kē li'ē kō'ī anumati kahatē haiṁ."
    usage: "Upayōga: / setuperm <khilāṛī> <anumati> [duniyā]"
    messages:
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      uperm_added_successfully: "% Var0% karanē kē li'ē% var1% saphalatāpūrvaka anumati jōṛā."
  unsetgperm:
    desc: "Samūha sē kō'ī anumati nikālatā hai."
    usage: "Upayōga: / unsetgperm <samūha> <anumati> [duniyā]"
    messages:
      gperm_removed_successfully: "Saphalatāpūrvaka samūha sē anumati% var0% haṭā diyā."
      group_not_exist: "Samūha% var0% maujūda nahīṁ hai."
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
  unsetuperm:
    desc: "Upayōgakartā sē kō'ī anumati nikālatā hai."
    usage: "Upayōga: / unsetuperm <khilāṛī> <anumati> [duniyā]"
    messages:
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      uperm_removed_successfully: "Saphalatāpūrvaka% var1% sē anumati% var0% haṭā diyā."
  usrinfo:
    desc: "Ēka upayōgakartā kē bārē mēṁ jānakārī dikhātā hai."
    usage: "Upayōga: / usrinfo <khilāṛī> [duniyā]"
    messages:
      level_not_exist: "Viśva% var0% maujūda nahīṁ hai."
      status_online: "Ŏnalā'ina!"
      status_offline: "Ŏfalā'ina..."
      usrinfo_header: "-% Var0% kē li'ē upayōgakartā jānakārī -"
      usrinfo_username: "Upayōgakartā nāma:% Var0%"
      usrinfo_status: "Sthiti:% Var0%"
      usrinfo_group: "Samūha:% Var0%"
logger_messages:
  getConfigValue_01: "Kun̄jī% var0% config.yml mēṁ nahīṁ milā."
  getDefaultGroup_01: "Ēka sē adhika ḍifŏlṭa samūha samūhōṁ fā'ila mēṁ ghōṣita kiyā gayā thā."
  getDefaultGroup_02: "Kō'ī ḍiphŏlṭa samūha samūhōṁ fā'ila mēṁ pāyā gayā thā."
  getDefaultGroup_03: "Svacālita rūpa sē ḍifŏlṭa samūha kī sthāpanā."
  getGroup_01: "Samūha% var0% nahīṁ milā"
  getGroup_02: "Samūha% var0% avaidha yā bhraṣṭa ḍēṭā hai"
  onEnable_01: "Ka'ī duniyā'ōṁ samarthana vartamāna mēṁ akṣama hai."
  onEnable_02: "enable-multiworld-perms saca karanē kē li'ē config.yml mēṁ vikalpa āpakō prati-duniyā anumatiyōṁ kā upayōga karanā cāhatē haiṁ sthāpita karanē kē li'ē mata bhūlanā!"
  onEnable_03: "Ka'ī duniyā'ōṁ samarthana sakṣama hōnā cāhi'ē."
  setProvider_SQLite3: "SQLite3 karanē kē li'ē sēṭa ḍēṭā pradātā."
  setProvider_YAML: "YAML sēṭa karanē kē li'ē ḍēṭā pradātā."
  setProvider_NotFound: "Pradātā% var0% ḍifŏlṭa karanē kē li'ē ḍēṭā pradātā sthāpanā maujūda nahīṁ hai.."
...

**Comment by 64FF00** [comment]
Tysm again <3

**Comment by 64FF00** [comment]
@JoahDave Could you please keep the indentions next time you make a PR? Thank you btw.

**Comment by JoahDave** [comment]
@64FF00 Next time, I'll give you a pastebin link! less than 3
