### ISSUE TITLE
Invalid 'permissions' nodes given to _64FF00\PurePerms\ppdata\PPUser::getUserPermissions

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#62]
You dont fix this. i dont agree you fix the bugs. purechat have bug and this have!

**Comment by SoyPro** [comment]
[Server][03:13:04][Server thread/CRITICAL]: [PurePerms] Invalid 'permissions' nodes given to _64FF00\PurePerms\ppdata\PPUser::getUserPermissions

**Comment by 64FF00** [comment]
@SoyPro What version are you using now?

**Comment by SoyPro** [comment]
PurePerms v1.1.8 and purephat 1.2.9

**Comment by SoyPro** [comment]
Now PurePerms v1.1.9 and PureChat v1.3.0

**Comment by 64FF00** [comment]
@SoyPro Do you still have your original groups.yml?

**Comment by SoyPro** [comment]
But now not you fixed it.thanks!
