### ISSUE TITLE
Feature: Sudo mode

### ISSUE THREAD

**Issue by PEMapModder** [PurePlugins/PurePerms#64]
A user always joins with the default rank if sudo is enabled in config.
The user has to enter sudo mode by executing the command `/sudo <password>` to change his rank for the session into another rank.

**Comment by 64FF00** [comment]
@PEMapModder Sounds awesome! What do you think about making a separate plugin using SimpleAuth API?

**Comment by PEMapModder** [comment]
@64FF00 users might want to use a password other than their own passwords, like a "root" password.

**Comment by 64FF00** [comment]
@PEMapModder :+1:

**Comment by 64FF00** [comment]
@PEMapModder https://github.com/PurePlugins/PurePerms/issues/30

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/commit/b0f916cd6e974067e3258f48e92245aa85bf52bd

**Comment by s3r1alpari4h** [comment]
Is this turning into UNIX? XD

**Comment by PEMapModder** [comment]
@s3r1alpari4h in Unix, you type your own password for sudo. I am proposing this with a same "root password" (although it doesn't really give you ultimate/root access).

**Comment by 64FF00** [comment]
@s3r1alpari4h @PEMapModder Conclusion: Sweg

**Comment by s3r1alpari4h** [comment]
XD

**Comment by 64FF00** [comment]
@PEMapModder https://github.com/PurePlugins/PurePerms/commit/7f320a47a946673baa56f06be3bd2aed6d924dcd
Suggestions related to Noeul (e.g. password encryption methods) are always welcome :+1:
