### ISSUE TITLE
Call to a member function getGroupPermissions()

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#66]
Fatal error: Call to a member function getGroupPermissions() on null in phar://C:/PocketMine-MP/plugins/PurePerms_v1.1.9.phar/src/_64FF00/PurePerms/PurePerms.php on line 390

**Comment by 64FF00** [comment]
@Pub4Game Do you still have your groups.yml file?

**Comment by Pub4Game** [comment]
I used the standard file groups

**Comment by 64FF00** [comment]
@Pub4Game Please update this issue if you are still able to reproduce this
