### ISSUE TITLE
Everytime I Do /reload (pocketmine.command.reload)

### ISSUE THREAD

**Issue by Jefferson629** [PurePlugins/PurePerms#68]
[Server] [03:56:58] [Server thread/INFO]: Enabling PurePerms v1.1.9
[Server] [03:56:58] [Server thread/INFO]: [PurePerms] Set data provider to YAML.
[Server] 
[Server] Fatal error: Call to a member function setPermissions() on null in phar:///storage/emulated/0/PocketMine/plugins/PurePerms_v1.1.9.phar/src/_64FF00/PurePerms/PurePerms.php on line 601

**Comment by SoyPro** [comment]
Can you fix the problem muy server crashes.please fix the crashes

**Comment by Jefferson629** [comment]
@SoyPro Maybe You Didn't Setup The PurePerms Correctly... That Why Your Server Crashes.

**Comment by SoyPro** [comment]
No.i setup property i have the bug you have

**Comment by Jefferson629** [comment]
@SoyPro Oh Okay...Dont Worry @64FF00 Will Fix It Soon.

**Comment by 64FF00** [comment]
Fixed in v1.1.10
