### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#74]
I have a server with an average 60-70 people online and all the console messages in "Registering player Name..." and "Unregistering player Name..." Please make an option to remove or add the ability to disable these messages . Thank you for your attention.

**Comment by 64FF00** [comment]
@Pub4Game Alright! Thanks for your suggestion!

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/commit/69731842a4529914da48bb4179d0676dd77ba260

**Comment by Pub4Game** [comment]
Thanks
