### ISSUE TITLE
Players

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#75]
Why is the file not the player recreates anew? For example, player I deletes his profile and then he comes on the server and you receive this error.

Could not save Config C:\PocketMine-MP\plugins\PurePerms/players/steve.yml: file_put_contents(C:\PocketMine-MP\plugins\PurePerms/players/steve.yml): failed to open stream: No such file or directory
RuntimeException: "file_put_contents(C:\PocketMine-MP\plugins\PurePerms/players/steve.yml): failed to open stream: No such file or directory" (E_WARNING) in "/src/pocketmine/utils/Config" at line 208

**Comment by 64FF00** [comment]
@Pub4Game No clue... What version of PocketMine are you using now? And are you using linux?

**Comment by Pub4Game** [comment]
PM - 1258 OS: Windows 10

**Comment by 64FF00** [comment]
@Pub4Game Can you still reproduce this issue?

**Comment by Pub4Game** [comment]
This error happens on linux

If you delete a player profile and he re-enter to the server, then this error occurs
