### ISSUE TITLE
Call to a member function setPermissions() on null on line 601

### ISSUE THREAD

**Issue by ClanEmo** [PurePlugins/PurePerms#79]
PocketMine-MP Crash Dump Sat Aug 29 13:13:23 UTC 2015

Error: Call to a member function setPermissions() on null
File: /PurePerms_v1.1.9.phar/src/_64FF00/PurePerms/PurePerms
Line: 601
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PurePerms v1.1.9

Code:
[592] 
[593]                 if($permission === "\x70\x70\x65\x72\x6d\x73\x2e\x63\x6f\x6d\x6d\x61\x6e\x64\x2e\x70\x70\x69\x6e\x66\x6f"): $value = true;
[594]                 else: $value = !$isNegative;
[595]                 endif;
[596] 
[597]                 $permissions[$permission] = $value;
[598]             }
[599]         }
[600] 
[601]         $attachment->setPermissions($permissions);
[602]     }
[603] }
[604] 
[605] 
[606] 
[607] 
[608] 
[609] 
[610] 
[611] 

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1214 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux d6fafcd35c6b 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64
PHP Version: 5.6.9
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
LaunchPads 1.0.0 by Philip Shilling for API(s) 1.12.0
LeetTP 0.0.5 by ProjectInfinity for API(s) 1.12.0
LeetAuth 1.0.9 by ProjectInfinity for API(s) 1.12.0
Slapper 1.1.1 by jojoe77777 for API(s) 1.10.0
EconomyPShop 2.0.1 by onebone for API(s) 1.12.0
PurePerms 1.1.9 by 64FF00 for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
xyz 1.0.1 by unerds for API(s) 1.0.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwlz2ziW/itYJVUTb4mybttKubfcjj2TWafjjZ3trWp1pSASlBiTBIcgLStT/d/3ew/gIdmJ
nWN3ZlLdNvEAPLz7AOm/d4ooUZ3ZYDzuH07G/f6o21F5rvPO7O+dYpNhqnP24ezdu7fvOt1OooyR
S4KdyjgWhRZSJCpZqFyEZeoXkU6FUcWlypPIGIzMiz0BWFrGMbaHUUx79y/LXNEa8+F20Bv0jnrZ
Sub7Jvf3P0zH5+f9frOiecL+OEqxf9of/NHtZHG5jFJgay/wdaCI8MnREDMATI5GeBA7/6LwxfOs
plEcHx+LeWc+vzvoVz+mE3oa0lNATyP8GCoa0tM0rCbsjwH94Nlxta6F6qiendq9nb2ZeH4r41KJ
Y1HkpXrJlI4foFTFRrUW/9vzyPyilrKIbt2myUOb0iAK7fS0EsPBA+taMjC/tQa/4yR7pEVyuLP3
D4YetaAEmfb79jDopzX1XBaF9FeJSgvvpx3baBOw95K3Dt1Wi5GUZ58gHDIiepw0j9Pm8aB5PGwe
j+rHQb95HNhHWFGRSx8W81vnWV+8gFoy7d+oIoGdzedXKr9VufeTn0uzelUm2Yu9zu/dzlKlKpcx
mRmmiXYQOehNAnULShdlFAdwp+FgDBvNdaF9jbXDg25HZhGvHAx7faxcRgWG/Sf+w4Zc3sTRgvb0
DhhDmUpy3c5FlJZ3IpiGMvSD0cSfLsSoN+j3+t5weNRT8UHv7nAKzxLPBuLqzaU4zyPxRuZiKgaD
2Wg6Gw/F++tTMewPJsKuBPJslQH1pDftHWH0CTaF4RDDvp38oE11NAA8iHlQ+6YhEZ35OtXJ5uTy
NY0cwS1gtyVEyKV3CIgsi5XODalFp2qB/0nuLL7fIL8+k0CBw/4e1r8H/HvkxiM3HrvxGGPgUalc
xArchBLO1e0EKgNzdBomjQ6LV21AIjnIODrmc2VJBzHz+RYbsZYkocu3V9e/vn138QqgtVqYqFC1
sbn1F5JkuSsMhn6DNNiavshWW9xfwWIMgmoeHXVPYPJ1oZLTWJdtFhtYd8tnRo+zN36Mu6dwBPoS
n86fz99g6jSWxjzCTWdVFNlsf9/h6CVq31n1/n/Yh+MaK5n8uTTFdS5TE6q8xfkWeJv5fm+4zb5Z
6eUq8rMvq5fyxRP5rxDO520ytkeNGK6uT95dv7+8JwQDKSBWrcpFz9fJfoV0fwsLJPDnXC5+lssW
8xVk26qHvYNtvmUclfFmm+vaxysnf9zMvyAIe8J8vgRBC7m0VvAUA9jhXcbqIxwh18C336QKr7KM
IldqP4FcVL5fMQ/JRJfIA8ovdNsyWsC2fBC05LZ4Ll79z5Zsjr5DEMAFb6hP/mZBAI/35vTybL/F
BRi9kCgCV5cyMC1GW8BdB+hvc3q5iuIoE1f4hVSy/GF+kDFe49DO5zFTlIGi+fwCnD/iBS6wXShV
XF+2GbOANlNgqTfZYSrXHyGg12kYpVGx+crY/SVd4njQz0RUv58WomntCSjc4YVBuyo6+n/nhsho
np7G0VUss2wr8FaQbX4GXBK0+PmoP2p1QP/ux59vZcXYo+fz5HHn2q4MLq9WOrtfGljwbm0w+NG1
QTt3f0WdAMfSWV0oVLQ+gemmcWs4bjdz24rbMUTbJ/6wEOH6zvm8JqD1+NU5kne6nNBgafT8V724
r2UC7up4/K9RDX/Ui9oALBtPUP+55PsCg5CyVTA10J1icbdeulbFSuUq+PDjolDrdCqTePDma734
pOR9D/Q7bmJXy8N/oJa/sTmQlpWmB6pZe4Kc7jafWsKh0W7W2YltJTpuELQrkG/VskU3n+Nk/vFY
AdTybEdJo+yHI/aDAXv6D2zmtmL000N0tUHF8QNMKr7U+ydiEgQ1TFrqvsJtozzTefGA27qJbwjO
/2esSktT4381jU9g+L9Rsr9Ta5m3e/QWsMUo4ssXm5HPxaXR9zYpDTlPalKqkkJnZfYqMlksN1vl
4M7EI7XUX1SuqbHrivNY3kalGQx/XI7ZJmWXu8/3H07T1/LuvokScJen0b9eVinkXW3RlqUn6Pzn
HGt8brpbgmlDd0rJnRB1dqvjKxD44zTcOvsJ6q1umtbrdU+BFsLaK274Uknr4CwM0XC1K6QG+Eg/
/ea9Coz8gdVRffLX36MRd74sIJJNz0+JuZ9lSv1GW2cOsm3Jg86jEei7Io079WvCTNXr5Bp9Hrrg
+x1bNbPrlJMfmTPcpey3+VrmSGw6t4bmJzZvpytZ7PRuDNqt2/uPt26DR3lu+qh7TG41DZ/p6Yiw
5um7OzpGwkZcFLH6z6gwW3ZcA3c9dKdmOJfxTZTffG9pu93FX/LF5Bsoe9OSxoKJugFRZPItAh9V
Nr3QkTlYg/NWx/OrsZ6zoUjR259nl/VInOo0jJaC3vfO83n67EoW4qRciuGRGIxm/cPZeFC/cqIF
iS6C41cyvxEgW+b+akNQe4pHhc3xYHowGhBwvQJlXhyZ4liHIUFkmuoy9ekaljKqJ/1VpG4VvXE0
x+hRCFMm16mX2btKaON4MOnzufLO7TIVSMaxXnthHC1X9Ql2u0yjBKrYQpnoRQVYQkKJDtQxowl1
DopqmEO0Qj3j67weZ7eZ2x1EYRj5ZVxsjplN+5ax0LlnVFFE6dIcEzgGY7FHdna81nkcNDCjVNBa
Qq/uj1+dnZ+8v7gmqLUm728lArA7EnaoPSNvlRvfRmrtBRCshDCPR61dOczLLaLHXoa4j+OD43/n
fxWU9TQcHI5pIb0lrG/Ie5skJhMRFGOFz9ZRgj16+05GIiAu4eyWLtTfXMJoxPVKGSUq/oXMlUDH
L2DYBg8wKZ9UX4iFElHqx2WgAjyIe8ZJuK50gp0hIdjFaWSISk/TZYIhlGKRK3kjNrrMHS4RhQJq
jMKIT4AGc9hRvCHEv6h1jW4/UKGEDo1Y6/RPhaB7QJkLEnQCZn3Y1oY+hyhWkbF8r1cqFWW2zGUA
BL15SlZvkc3mqXh2vcoVrF1R4hSxTJelXCpBnzmwyJyHmAjjWAN/9ImFSltPV8p3XGxvBAFVhFNp
bx3dRJkKItnT+XKfRvsXsIEPOvzw+urth+noyBt+oH0QY41oJuaIT8t5hw76dcUXMfQ1iEFAEvRl
iClylm9BL4hiWUBuPM3SZEpBB55UwSoN1G3kK7FCQotZyQkQWxdqjuQ4CLhZlUWgyfns1yhEjH1X
L/xYGxVYsk7IkQUFClAi3CsacRtJ8V/kBFjCzlC9vJnxlxi0Ee3xWkiyUqNBjTvFqko6RKI0MEKE
ZBgCc4fQi5UI7AHJqZnwQNZC00ccFfoz9qkKDzgWFBEEzBUWQaQuNsLZEZY7D6xnGzE8u6LoDwQ6
3SS6NJA5dA9ufUOy9mHEhQKdRHuuyDmJMtKQV1qxVRT9UvIXPPCOE7NJ/WtpbmDA+Q38oUfz7yFT
NreKZlq1ypFycGqB1aYrOBoJF7VggV1wlUAI9gsb4hJJhWBJmcIRaEnPMlFYd4Cv5PoOEbZQcBIw
wJab1qSRkCw5r0NyOP74CI7VFVHxJ/oWKeddgaIQz0a1s1e8AAdQmxjukd8yE55jc8ao5ukudEAO
SSE837A7/jnWCwnrRvYVFgwDS6KCwk6ilnKxKUCkuLLk9ZmgyJAGrTODz3XExEbLJXvC2rN4PAcy
LKswgkUgEiGUp4wqRBioTmRDJAatbpcavGmyfpIjzlkykR4TNhMjVEAcDzj0FognMvgnZ4Aqlor8
4cSRj9ov0hzfYeE31sQ5wjmkL5zPiAGsA74bQMt2hQeLhLUPHSLUJogIpSIayd0+x4IlHeVGzCGT
goldNucMRjhg/9WeypvohLcpLJhSBi/v3V8sIEZX3kHWmfIpsxgWCdFqlWH31gzAvVVmGjZHfcen
2XuQIMf1yHK9lPkCsvZ8Hce2BCJ7flCqrDoixe0Rbg+8J5FpyTmsTQXyewmj2etWXrljNc5sNAlF
cvfI2JPGHHvirU0gPEIgW+kyDmpCIvjwOhUN6ZzQRcakg8Npn0y8Adgxn3zOZngvXLHxWHQ1l2Gu
kyrq0V4377UjQkvJ4Mrpctc2HjCo1j6qOP1Vmd4Yq4AL9j6KUQwkyqggJ2aErUy77Bs5UryxizyK
4VQtNLhYIJXineccTemAHeBw7Kh/pS2yXS1TtKYKxW5rY7Bnu2U/QBKcMTwf1bqysnAmUx1EE3WO
+iKqeZqqgjRUl0ywoNimLLQ9aAeoAJBUXSJTwexclGM/tQWhm7XBbaHq5IViokpSzrCrGYoP+aYg
3F3hDVo2T0mKj/WKihSKY1MbfJqkyIU6ZaTARkSnVrsXQEdTT/wFvQjEe4waFOZ8evm+i72gYIEw
tY6CYmUDKYeBGr3H6GfiwGXwJrcbFkxraU+cBHC7lYxD+t6JQwESKazPHYQjrVXqtO23db5s4WrV
J2d35JHUhsm4a/2fDv41SlG9gS2YjWKDp6T8/jK9rFJ6UytT1UKb+B6YCuU089ywXQuhfVKLcjlz
1cFPYkBVgVWmoWqOp6tKznC4W6mqwps7VXC6r+ozI/apniqNlSoiX2Ba51U911aprqq6jUgGE7ZJ
4aXOsohT1rWtzgIuFXmLZ7fMRIKppSvhwQu/wyZKYW2wT45Scgs/Yis1QUXreMixuE8Nuydr7dkv
b6/PZoLjMv7zS/QzKfoZRhQlWczNM5PnTq7Jq7V7sqUoH6U7gojjlQ2IkxYoIYMpyGiGfZdkKLbZ
3EUWRF0owV3Ccg6/Da7DV9+5o02WC2lU67AXA/jIA6d0xRATg4cmVOH39thfjWpTwZZwTZipm3FX
BEIhJtnzqDiwmuS+sWkoKQZw40G1DEUCGa/lxljcDk/LjrYCOpvRCWr5tJ0RjKugKiKIfMKGxXhk
xBDM57fKHNDA0u7eOSBbtPKQGBwNtzMTcuqD+NjeUmWbuYWy+BcqpLDE9yEUvkgx1TkWuhUHx6xB
eYu8TP1gRD2roh4o27j+3CWmugjiqBHydXoVI11MC8uYl2kD4/W4//FtXjGknJyaYpgK0FbC+6ip
f7HeYmRC1pNw4KRsU7O/ox4ScaWeN/JOyF25oHPxOVk0FkIybtQz7m9ry5Wi79D1l6aFyOlKOnrZ
kR0yZ5y0AfqZp9uA4dd5Nd9ueWUWwNgbftE+K2lp5Au2JsNaOTTdXSWK3n1ZuNi6lhH33eixS+XM
xe1nChjuGeh+Jg6/CVumszJ22Nwzpb024iHRzk7vQfhEtL3D89gsDemFFJMgDxR0jeKgAxd/6G6s
KicrC4GE0jJDdWVrTGvfHJ1sEeNwAcsBF6Xu0hBIJzRcSzqoBjJMJosIirFL3LWcbdhnVZsv+G8Q
qjbe9uLW5qwzuGaijp7c5dOlzTakzldb0GyVRWmoGzNYadI9H9mLlSp6vl8TZm2GZVkfWu2D9O30
zLKap55LsU0dx1Cdta5bTunGja+AVKwzMtEuxoWk+yG4tCuoUF+EqIIV2EKqSSlb0yKXJUuSA9ym
hUS4i/dWJVCibDSFzVVVpHLYSBZ2usLfUGjFQS+wWheaqDhZJnGEzGELgLM7SU5mB1R2AL8jYlZR
w1MwK1NoGNFv9OghX6B3AuB3wmjDV1VRtO8qmYmqF7AdWnVJzK3XQ1ef3MlyQjKc/IntBDVBBEJd
tm6RzqcyAfwk6E6ZnIRjdnPaTJxfnFzPhi8PupOju0F3dDfqDl8OXgZIqjY+vKAvoX3y5ePDvljC
kowdjSd7fDWs7gqV8t/90HuTUySQ1h+bkAm1hojjy/otSObTUjcwf4ujQo3sn8R49g9wPtm/kbGv
shc+SpRVvZ6uHdNA5g3A/oVbNSrzuB6EUcxvlIHafYQeFlk9u2zeyyyTBryCy9g3PVj/0bjXPvYd
Jks7sH+/M+hNHLnJwl6V1ihQ/22yomGxkERx0JLH1eUFI6HPxjIfEb7Zu4FE+A913JOY0McNAzpL
ePS2Zdif9Ed4fP6aOmd/eni4mC4W/qgfjKYyHEl/NA6DYLw4WEwWB4cHoZrgn3hOb5VWJLf6e7VM
m+iu0Ypr3avPKYjfdyp0DSWgfJ4Kw8NF4E8ni/5CyfAwHMtATcP+NDwcH6ppMB4FYXA4nPJ5ZpXo
RrCGPc9scxpZWWJxoW9UipCf15BflbxByLCC4q+SNpLfQVQfAX+KsuqvsSadP/74X+7TBs8=
===END CRASH DUMP===

**Comment by PEMapModder** [comment]
@64FF00 why `endif` :dizzy_face:

**Comment by 64FF00** [comment]
@PEMapModder :'(

**Comment by ClanEmo** [comment]
Wat?
