### ISSUE TITLE
Crash while using PurePerms Api!

### ISSUE THREAD

**Issue by vvzar** [PurePlugins/PurePerms#80]
Error: Call to undefined method _64FF00\PurePerms\PurePerms::setGroup()
File: /var/mcpe/shared/Plugins/TimeRanks_v1.0.2.phar/src/TimeRanks/Main
Line: 81
Type: E_ERROR

In version 1.1.8 all worked fine. What did You changed in new version on setGroup()?

**Comment by 64FF00** [comment]
Contact the TimeRanks author to fix it

**Comment by vvzar** [comment]
is anywere another public changelog about what exactly changed?
Seems to be almost all users that using plugins depended on PP, have to wait untill all dependencies will be updated before they install new version of PP.

**Comment by 64FF00** [comment]
@vvzar Fixed in https://github.com/PurePlugins/PurePerms/commit/f78dd52e583dd1b855d08e0d426df51ace23aba7

**Comment by vvzar** [comment]
Thank You!
