### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SoyPro** [PurePlugins/PurePerms#82]
One feature is /setgroup Ender Member 7 days.this a feature you can add in the next update!or /setgroup Ender Member 3 hours.i think you can add days,hours,minutes,months,years.thanks!

**Comment by Pub4Game** [comment]
I already offered( I was told no

**Comment by 64FF00** [comment]
Use TimeRanks plugin by @luca28pet. http://forums.pocketmine.net/plugins/timeranks.1293/

**Comment by Pub4Game** [comment]
No! You not correctly understood us... We wanted the group were issued at a certain time. And in TimeRanks change groups depending on how much you play.
