### ISSUE TITLE
Crash PlayerJoinEvent

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#89]
"Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PurePerms v1.1.11': Illegal offset type in isset or empty on _64FF00\PurePerms\PPListener" 
RuntimeException: "Illegal offset type in isset or empty" (E_WARNING) in "/PurePerms_v1.1.11.phar/src/_64FF00/PurePerms/PurePerms" at line 499

**Comment by 64FF00** [comment]
@Pub4Game Fixed in https://github.com/PurePlugins/PurePerms/commit/af26c63480ceb7a3d6f7ff7ecc3134f8fdfbb36b
