### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ClanEmo** [PurePlugins/PurePerms#94]
idk what is this but it shows after i join my server  [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PurePerms v1.1.10': Illegal offset type in isset or empty on _64FF00\PurePerms\PPListener  also under of that message is [Server thread/WARNING]: RuntimeException: "Illegal offset type in isset or empty" (E_WARNING) in "/plugin-862.phar/src/_64FF00/PurePerms/PurePerms" at line 627

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/PurePerms/releases/tag/v1.1.11
https://github.com/PurePlugins/PurePerms/releases/tag/v1.1.12
