### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ClanEmo** [PurePlugins/PurePerms#97]
Umm Idk what is going on but this bug is very annoying... the non op players got the message like this "{COLOR_YELLOW}{FORMAT_BOLD}[Guest]{COLOR_WHITE}{FORMAT_RESET} ClanEmos {COLOR_GRAY}> z" even they got PureChat perms ( I didn't edit PurePerms Yet.. I also didnt know where to report if it here or in PureChat, I hope this should be fix soon..

**Comment by AryToNeX** [comment]
This is PurePerms repository, this issue should be reported on PureChat repository. Anyway known bug: PurePlugins/PureChat#19
